### ISSUE TITLE
Sock Shop microservices demo

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#10]
A nice demo that shows a lot of breadth of cloud resource management would be to run Sock Shop using the controllers and resources in this repo.  We should be able to deploy all resources used by Sock Shop with a single yaml file.

* https://microservices-demo.github.io/
* https://github.com/microservices-demo/microservices-demo

**Comment by negz** [comment]
We have something like this in our wordpress examples. I'm going to close out this issue - @jbw976 please reopen if you still think it should be on our backlog.
