### ISSUE TITLE
New versions of a stack should update CRDs installed by previous versions of the stack

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#1013]
### What problem are you facing?

Namespace Stacks (`StackInstalls`) can have multiple instances installed per Crossplane cluster.  Furthermore, they may also be at different versions from each other.  This is described in detail in the [security/isolation design doc](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stacks-security-isolation.md#multiple-versions).

If an existing version of a Namespace Stack is already installed and a new version is attempted to be installed, the Stack Manager will currently see that the CRDs already exist and do nothing.  This means that any new versions of the CRD that are in the new version of the stack will be ignored and not installed.

### How could Crossplane help solve your problem?

The Stack Manager should be smarter about how it handles multiple versions of a namespace stack.  Instead of seeing that a CRD already exists and doing nothing, it should attempt to "update" the existing CRD with the new schema/versions in the new stack.  Example:

Stack `foo:v1` is installed which has CRD `bar.group.io/v1`.  If stack `foo:v2` gets installed which has CRD `bar.group.io/v2`, we should end up with a merged/updated CRD `bar.group.io` that has both versions `v1` and `v2`.

We'll need to think through this carefully, I'm sure there are plenty of pitfalls.

**Homework research problem**: what is the right behavior to do in general (upstream k8s) if a CRD is installed when an older version of it already exists? Is there upstream guidance on this?

**Comment by displague** [comment]
> Homework research problem: what is the right behavior to do in general (upstream k8s) if a CRD is installed when an older version of it already exists? Is there upstream guidance on this?

An interesting feature of the CRD spec is that each version details its own OpenAPI spec.  There is also a conversion option: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions

I think one strategy that we can take is to always adopt the _newer_ CRD and fail a StackInstall if the CRD provided has conflicting (or omitted) version definitions required by installed Stacks.

By doing this, we do not need to hand tweak (merge) CRDs.  Doing so would leave conversion to change, and the CRD author should take control of that.  I don't know enough about the conversion process.  I wonder if the StackManager or controllers would need special roles to trigger a conversion or if a CRD conversion definition introduces an opportunity for (namespaced) Stack installers to get escalated privileges.

**Comment by displague** [comment]
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#webhook-conversion

The ability to convert resources to newer versions will require Stacks to install conversion Services.  I believe the limitations and requirements of these services would be bound to a new service account.  I do not know what requirements should be necessary.  It may be sufficient to initially restrict the Service service account to operate on the kind it is converting.  I don't think remote (url) webhooks pose a problem for Stacks over "service" referencing webhooks.

**Comment by jbw976** [comment]
This content has been merged into #1014 for consolidated tracking
