### ISSUE TITLE
v0.4.0 release tag is not on master

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#1018]
### What happened?

When the v0.4.0 release was tagged, the tag was applied to a [commit](https://github.com/crossplaneio/crossplane/tree/v0.4.0) that occurred after the release-0.4 branch was cut from master. Because of this, the `build` submodule does not acknowledge the `v0.4.0` tag when it [executes a build](https://github.com/upbound/build/blob/a1d803f92e19fff3ae0d60a5e7fa6b6e56586ffb/makelib/common.mk#L193), so new local builds and `master` images being pushed to docker hub are tagged like [v0.3.0-239.g5da3024](https://hub.docker.com/layers/crossplane/crossplane/v0.3.0-239.g5da3024/images/sha256-97bb1a4a71fcf7559821800be63d5a01b10148f4bb07cea823c714df130016e6) even though they are post v0.4.0 commits. I have confirmed that earlier releases (such as [v0.3.0](https://github.com/crossplaneio/crossplane/tree/release-0.3)) were tagged on commits that existed in master.

### How can we fix it?

I see this as more of a problem with the way the `build` submodule selects `VERSION` rather than something that is incorrect about how we are tagging. We should consider updating the `build` submodule to consider all tags, not just those on master.

**Comment by jbw976** [comment]
This is the lingering behavior of #330
