### ISSUE TITLE
aws-provider.html has 404 for AWS setup.sh

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#1068]
While testing with AWS today, we followed the steps outlined here https://crossplane.io/docs/v0.4/cloud-providers/aws/aws-provider.html

I was hoping to run setup.sh, however, the hyperlink for that seems broken

https://crossplane.io/docs/v0.4/cloud-providers/aws/github.com/crossplaneio/crossplane/cluster/examples/setup-aws-provider/setup.sh

![image](https://user-images.githubusercontent.com/284840/68904336-8fa48e80-06f2-11ea-9441-922e99015793.png)

**Comment by hasheddan** [comment]
Fixed by #1070
