### ISSUE TITLE
Support configurable names for provisioned resources (e.g., cluster)

### ISSUE THREAD

**Issue by vadasambar** [crossplaneio/crossplane#1078]
Related: #624 

### What problem are you facing?
When a cluster is provisioned through `crossplane`, it generates a random name like, `gke-0eb7ce43-xxxx-xxxx-xxxx-xxxxxxxxxxxx` for the cluster. This makes it difficult to distinguish between clusters.

### How could Crossplane help solve your problem?
 Adding labels help but being able to control the name of the cluster being provisioned would be great. We can have something like `custom-prefix`-xxxx-xxxx(some uuid with it) or even allow providing static names for the cluster and throw an error if the cluster with the same name already exists. 

I saw some docs referring to `external-name` [here](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#external-resource-name) and [PR](https://github.com/crossplaneio/crossplane-runtime/pull/45) related to it. It seems to implement `external-name` in annotations. I tried setting this in my `kubernetescluster` resource but it doesn't seem to work.

**Comment by muvaf** [comment]
External name annotation isn't used by k8s cluster resources yet. Hopefully, all resources will use it in the 0.6 release.

**Comment by vadasambar** [comment]
External name annotation works in 0.6 release. :smile: 
Closing this issue.

**Comment by jbw976** [comment]
Thank you for following up and confirming @vadasambar! 🤓
