### ISSUE TITLE
Create a list of external stacks in docs

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#1084]
### What problem are you facing?

It can be difficult to know how many Crossplane stacks exist and where they are located.

### How could Crossplane help solve your problem?

Now that the number of stacks that exist outside of the crossplaneio org is increasing, it would be nice to have a list of all community stacks. An end-user requested this feature at Kubecon. Right now, the stacks outside the Crossplane org include:

* https://github.com/vshn/stack-cloudscale
* https://github.com/packethost/stack-packet

**Comment by muvaf** [comment]
`README.md` looks like a decent place to me for this information.
