### ISSUE TITLE
unstructured.Unstructured type is not usable with typed resource templates

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#1086]
### What happened?

I am working on an [application stack](https://github.com/crossplaneio/sample-stack-wordpress/pull/17) that has `Namespace`, `Deployment` and `Service` resources deployed to the remote Kubernetes cluster.

When I create one of these resources in Go, there is no good way to convert them into `*unstructured.Unstructured` type which is what `KubernetesApplicationResource.Spec.Template` expects.
* Casting doesn't work.
* Marshal to json `[]byte` -> Unmarshal to `*unstructured.Unstructured` doesn't work unless you manually specify `TypeMeta` of the object.
  * Even then, the generated json has a field `creationTimestamp: null` because that field is not a pointer, you unmarshal the json into `*unstructured.Unstructured` and send it to api-server and validation fails with `Invalid value: "The edited file failed validation": [unknown object type "nil" in KubernetesApplication.spec.resourceTemplates[0].metadata.creationTimestamp, unknown object type "nil" in KubernetesApplication.spec.resourceTemplates[1].metadata.creationTimestamp` (somehow creation doesn't fail but updates to the resource fail)

One might be able to get it work but I'm afraid it's a bad experience.

### How can we reproduce it?

Try to create a Kubernetes resource and then try to embed it into `KubernetesApplication` as a `KubernetesApplicationResource`.

### What environment did it happen in?
Crossplane version: 0.5.0

**Comment by muvaf** [comment]
I'll try using `json.RawMessage` instead of `*unstructured.Unstructured` as the type of the template and see.

**Comment by negz** [comment]
https://github.com/crossplaneio/crossplane/blob/1fb67d0526b79cefb9949cbfc9c103cdd228c3fd/pkg/controller/workload/kubernetes/resource/resource_test.go#L169

Would `scheme.Convert` help here?

**Comment by muvaf** [comment]
> Would scheme.Convert help here?

Thanks @negz ! That worked. It needs the `*Scheme` object from the manager but that should be OK. Hope others take a look at Wordpress stack and see it easily.
