### ISSUE TITLE
Explore user scenarios with deployment yaml

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#11]
Some of the up front design work we should do would be to work backwards: start identifying some user scenarios and author the yaml that we'd like to support for those scenarios.  This will inform the user experience that we want to provide and help determine the scope and priority of the various controllers and resources.

**Comment by negz** [comment]
This is still probably a good idea, but is pretty broadly scoped. I'm going to close it to cut down on our issue backlog a little. Please reopen if you feel it's still valuable.
