### ISSUE TITLE
Use kubeconfig key in connection secrets to connect to clusters

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#1108]
### What problem are you facing?

With #861 , we have introduced a `kubeconfig` key into all connection secrets of Kubernetes clusters that Crossplane provisions. As of writing, it's purely a UX enhancement for users. However, as stated in that issue, what it actually aims to do is to streamline how we connect to Kubernetes clusters. Current cluster connection logics present in the codebase* takes all the keys that might be filled into consideration and construct a kubeconfig. But if we could just let controller-runtime parse the raw kubeconfig, we'd not have to worry about it. There is also the case that if you want to bring your own cluster, you'd somehow have to provide its kubeconfig manually. Since the auth method in the kubeconfig varies depending on how you initially provisioned the cluster, it's just so much easier to put the kubeconfig and be done with it instead of parsing the kubeconfig manually (or writing a custom script).

*: https://github.com/crossplaneio/crossplane/blob/master/pkg/controller/workload/kubernetes/resource/resource.go#L428 and https://github.com/crossplaneio/stack-rook/blob/master/pkg/clients/client.go#L40

### How could Crossplane help solve your problem?

Use `kubeconfig` key in all `*rest.Config` object construction logics.

**Comment by negz** [comment]
I don't have time to dig through our old issues right now, but I keep meaning to drop a note that I feel like we actually used to do this (use a fully formed kubeconfig as a secret key) but moved away from it for reasons that I do not recall. I suspect there's an old issue or PR that captures that decision.

**Comment by hasheddan** [comment]
@negz is https://github.com/crossplaneio/crossplane/issues/273 the issue you are referencing?

**Comment by negz** [comment]
@hasheddan That's it! I think that was actually the first Crossplane issue I ever worked on. It seems unfortunately though that it doesn't capture _why_ we wanted to move away from using a fully formed kubeconfig file. @jbw976 do you remember?

**Comment by jbw976** [comment]
Honestly, I think it was consistency with the other cloud provider's managed k8s services, which was probably influenced by the desire for portability.  I'm sure the thinking was if we surface the connection information consistently for all cloud providers then it will be easier to make applications more portable.

I bet that was the thinking as opposed to any fundamental reason not to use a fully formed kubeconfig.

**Comment by muvaf** [comment]
It's interesting both issues aim for consistency 🤔 

I think using raw kubeconfig is like common denominator of all kubeconfigs. Some services use tokens, some use username/password. There is also the case where in one kubeconfig you have several clusters but you should go with the selected context, this doesn't happen to us right now since all kubeconfig we had to deal has been fresh directly from the provider. But we'll let people import their kubeconfigs and it's going to be messy. Even without these reasons, IMO importing would be pain in the ass if we require that many fields to be filled out. The advantage with the current structure seems to be that if you'd like to import a service account, it's easier. But there are already tons of scripts that generate a kubeconfig for a given service account.

**Comment by negz** [comment]
Exposing a kubeconfig file seems reasonable to me, though to be safe I think to be safe we should keep publishing any existing keys we publish in addition to kubeconfig.
