### ISSUE TITLE
EasyGCP stack published to registry

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#1122]
### What problem are you facing?
Need to configure all GCP environment resources required to deploy application stacks like [sample-stack-wordpress](https://github.com/crossplaneio/sample-stack-wordpress) including: provider, secret, cluster class, network, subnets, managed service access, resource classes, etc.

### How could Crossplane help solve your problem?
 - Provide an EasyGCP kind that will generate all necessary resources
 - Support easy customization of the Stack by forking / copying the repo

### Related Issues
 - #1096 Design for Easy Stack Resources

**Comment by muvaf** [comment]
Publishing works but Upbound registry doesn't support anonymous registry yet and `*StackInstall` objects do not support private registries. So, this is effectively blocked by https://github.com/crossplaneio/crossplane/issues/505
