### ISSUE TITLE
Is there a way to provide more permissions to stack RBAC? 

### ISSUE THREAD

**Issue by vadasambar** [crossplaneio/crossplane#1128]
It seems that we are adding RBAC for a stack based on the controller CRD

https://github.com/crossplaneio/crossplane/blob/c6d01ceea778b76d212b12961f4d5368f1187d4a/pkg/stacks/unpack.go#L337

### What problem are you facing?
If a controller inside a stack depends on say `Deployment` or creating a another custom resource in the same/source/Crossplane cluster which is not a part of my stack, the controller will not have permissions to do so. Example, if I want to create a GKE Cluster from my controller, I will need RBAC set up to access and create custom resources from another stack or operator already installed in source/Crossplane cluster.

### How could Crossplane help solve your problem?
I think allowing to setup extra RBAC permissions will open the doors for managing operators from controllers inside stacks in a Crossplane native way. Although, one of the caveats can be, we will have to be careful as to what permissions a stack has and it does meddle with other stacks. 

I don't have a solid approach as to how we can go about doing this but one of the ideas can be to provide extra RBAC permissions in the `StackInstall` spec.

**Comment by suskin** [comment]
Hi @vadasambar ! Thanks for the question! We do have some thoughts about this. Have you seen the way permissions are generated from the [dependsOn field for a stack](https://github.com/crossplaneio/crossplane/blob/c6d01ceea778b76d212b12961f4d5368f1187d4a/pkg/stacks/unpack.go#L369) yet? That is the current mechanism for requesting that RBAC permissions be set for a stack for specific Kinds. [Here's a link to an example](https://github.com/crossplaneio/sample-stack-wordpress/blob/bf35149b708b3649fb08fcfa89a5f2ddabf02674/config/stack/manifests/app.yaml#L65) of a stack using it.

**Comment by vadasambar** [comment]
Aha! I wonder how I missed that! Thank you so much @suskin !

**Comment by displague** [comment]
@vadasambar you may also want to take a look at and perhaps offer feedback on #758 and #899.
