### ISSUE TITLE
Publish easy stacks to crossplane org

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#1136]
### What problem are you facing?

Per [resource packs one-pager](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-resource-packs.md), three resource packs are implemented that allow you to create a connected set of resource classes configured for minimal node requirements that you can use with your claims.  For faster prototyping, I worked on them under my account.

### How could Crossplane help solve your problem?

They need to be moved under crossplaneio for better maintenance. Here is the list of the stacks:

https://github.com/muvaf/minimal-gcp
https://github.com/muvaf/minimal-aws
https://github.com/muvaf/minimal-azure

In its current form, the stacks themselves contain almost nothing meaningful other than kustomize `resources` folder and stack metadata. As reconciler, they all use the following generic one:
https://github.com/muvaf/crossplane-resourcepacks (after moving, we should probably name it `resourcepack-runtime` or something else)

Probably, we won't need the generic reconciler after these stacks are ported to template stacks but I still think it should go to crossplaneio org.

**Comment by jbw976** [comment]
@muvaf I have moved all the repos over to the following new crossplaneio repos:

* https://github.com/crossplaneio/stack-gcp-minimal
* https://github.com/crossplaneio/stack-aws-minimal
* https://github.com/crossplaneio/stack-azure-minimal
* https://github.com/crossplaneio/resourcepacks

I think you'll need to follow up with some new PRs to get all the import refs updated to use the moved general reconciller, so I'll assign this issue to you now.

I think we may want to clean up a bit with the naming/terminology.  I think we're not using the term resource pack anymore, but we have code refs and a repo still using that.  Let's consolidate and change repo names if needed.  Let me know if you need help with that.  Thanks @muvaf!

**Comment by muvaf** [comment]
@jbw976 thank you for moving all of them! I'll test them and open fix PRs if needed.

About naming, I think `stack-gcp-minimal` implies that this stack is a minimal version of infra stack `stack-gcp` in the sense that it has less resource support, like a lite version. However, it's a completely different thing. _Minimal_ in that context means that the resource classes have the minimalistic requirements such that when you create a `KubernetesCluster`, you'll get a one-node GKE cluster or if you create a `MySQLInstance`, you'll get a CloudSQL instance with 1 machine.

We could possibly go with `stack-minimal-gcp` or something else but I don't think `stack-gcp-minimal` captures the intent.

About the resource packs, I honestly am not sure what to name that repo. It's a generic reconciler that you can initiate in your controller code in order to deploy the YAMLs in your container image. However, I wouldn't worry too much either since we'll port the easy stacks to template stacks and that `resourcepacks` repo will not be used anymore.

**Comment by jbw976** [comment]
We still need to publish these minimal stacks to dockerhub similar to how we publish the existing cloud provider stacks.

We need to close and follow-up on:

* finalize the naming of the repos, both for github and for the stack packages (e.g., dockerhub)
* set up Jenkins pipelines/automation to build and publish these stacks for every release
* publish the first official builds.  This *could* be done from a developer laptop before Jenkins pipelines are put in place.

@muvaf, can you follow up on this? happy to help out with any of this effort.

I was thinking I'd just build and publish them from local to get us going with images that folks like @rathpc could use, but I'm running into build errors with `make` for missing packages, but `go mod tidy` and `go mod vendor` are also failing for me:
```
verifying sigs.k8s.io/kustomize/api@v0.3.0/go.mod: checksum mismatch
	downloaded: h1:DWNMJBV1xvLruMpihGgnIPznMwHpwUSrxz6v3gnw5kw=
	go.sum:     h1:4jaPCtRzxfQLFdYq4gYo40dBGW1hyPp/f4AuiZB5dAQ=
```
Have you seen that before @muvaf?

**Comment by muvaf** [comment]
@jbw976 Yeah, a few times. It shows up usually if you have go mod cache that was created via go1.12 and try to build the module with go1.13 or vice versa. I've updated my local to go 1.13 and made some updates to the repositories regarding naming. The following PRs build with no problem:

https://github.com/crossplaneio/resourcepacks/pull/1 (I'll open PRs for aws and azure, too, once this is merged)
https://github.com/crossplaneio/stack-minimal-gcp/pull/5 

You should be able to publish `stack-minimal-gcp:v0.1` after checking out https://github.com/crossplaneio/stack-minimal-gcp/pull/5 . I don't have crossplaneio dockerhub access, so, I couldn't publish the image.

@jbw976 is there a doc or anything you can point me to for Jenkins pipeline stuff?

**Comment by muvaf** [comment]
All three of them are published:
https://hub.docker.com/r/crossplane/stack-minimal-gcp
https://hub.docker.com/r/crossplane/stack-minimal-aws
https://hub.docker.com/r/crossplane/stack-minimal-azure
