### ISSUE TITLE
Restrict stacks to a single install per cluster/namespace

### ISSUE THREAD

**Issue by displague** [crossplaneio/crossplane#1150]
### What problem are you facing?

Part of #1036, Counterpart of #1014

Cluster scoped stacks (installed using ClusterStackInstall resources) provide cluster scoped CRDs and ClusterRoles, just as namespace scoped stacks do (installed using StackInstall resources).

Cluster scoped stacks have the ability to create cluster scoped resources, such as infrastructure resources (`GKECluster`, `RDSInstance`).

Namespaced stacks have the ability to create namespaced scoped resources, such as application resources (`WordpressInstance`).  As expressed in #1014, a namespaced resource should be useable in many namespaces.  To support that the controller for these resources must be run in each namespace, and that requires a StackInstall and resultant Stack in each namespace.

Cluster scoped resources, however, should be managed by a single controller and only be represented once in a cluster.  This opinion is bolstered by the notion that infrastructure stacks have a relationship with external resources, for which cluster scoped resources can have a one to one mapping. 

(TODO: improve the argument for why this is and why there should be only one. Maybe this prologue is unnecessary?)

Nothing prevents a user from installing stack-gcp multiple times under different names.  The stack installer will ignore any errors from duplicated CRDs.  This creates an undefined parent labelling relationship and provides no user benefit.

(TODO: why is this a problem for clusterstackinstalls, but not stackinstalls)

### How could Crossplane help solve your problem?

Restrict Cluster stacks to a single install.  ClusterStackInstalls should fail if the CRDs are already present in the cluster, especially when a different owner is in place.

Do we need an issue to limit Stacks to a single occurrence per namespace?

**Comment by jbw976** [comment]
Tracking this scenario in #1052
