### ISSUE TITLE
Crossplane cannot be installed to Kubernetes versions lower than 1.15

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#1164]
### What happened?

If you try to install Crossplane to a Kubernetes 1.13 or 1.14 cluster, it will fail with the following error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.controller.properties.deployment.properties.spec.properties.strategy.properties.rollingUpdate.properties.maxSurge): unknown field "x-kubernetes-int-or-string" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.controller.properties.deployment.properties.spec.properties.strategy.properties.rollingUpdate.properties.maxUnavailable): unknown field "x-kubernetes-int-or-string" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps]
```

The reason is we use a field type called `x-kubernetes-int-or-string` while Kubernetes supports that type only as of 1.15, see https://github.com/kubernetes/kubernetes/pull/78815 and https://github.com/kubernetes-sigs/controller-tools/issues/279

Controller runtime CRD generation tooling started to use that type for string and int fields and we updated to the latest version of controller-tools. I feel like we should keep the support for 1.13 and 1.14 as they are still used (GKE default is 1.13).

### How can we reproduce it?
Install Crossplane to a 1.13 or 1.14 versioned cluster.

### What environment did it happen in?
Crossplane version: 0.6.0
Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by muvaf** [comment]
GKE default version(the one that is pre-selected in the creation menu) is still 1.13 and AWS EKS [latest supported Kubernetes](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) version is 1.14

**Comment by advissor** [comment]
@muvaf , thanks for reporting!
Indeed this is the case and for now it blocks us from trying to use Crossplane with existing envronments in GKE

**Comment by muvaf** [comment]
Apparently, it's the `Stack` CRD having Kubernetes types such as `DeploymentSpec` causing this issue. For example the field `maxUnavailable` of `DeploymentSpec` is represented like the following in CRD:
```yaml
maxUnavailable:
  anyOf:
  - type: integer
  - type: string
  x-kubernetes-int-or-string: true
```
Because its type is like the following in Kubernetes source code:
```go
// +optional
MaxUnavailable *intstr.IntOrString `json:"maxUnavailable,omitempty" protobuf:"bytes,1,opt,name=maxUnavailable"`
```

**Comment by muvaf** [comment]
@advissor It looks like it has to do with `kubectl` version. See https://github.com/kubernetes-sigs/controller-tools/issues/279#issuecomment-573903146

I've tested with GKE 1.13.11-gke.14 cluster and `kubectl` 1.17 and it works. So, updating your `kubectl` to 1.15 or above should be sufficient to get it working.

@hasheddan I remember you having the same problem with AWS EKS, could you check your `kubectl` version?

**Comment by muvaf** [comment]
Workaround for cases where you can't control your `kubectl` version is running kubectl with `--validate=false`.

I opened https://github.com/kubernetes-sigs/controller-tools/issues/392 for client-side validation issue. Closing this now since it's not valid anymore.

**Comment by advissor** [comment]
@muvaf using 1.15 or 1.17 kubectl with 1.13 server is not really right approacht
Kubernetes skew policy says only 1 minor version difference
But I will give it a try anyway :) Thanks!

**Comment by muvaf** [comment]
@advissor opened the following for a more precise situation description: https://github.com/crossplaneio/crossplane/issues/1170

**Comment by hasheddan** [comment]
@muvaf not sure if still relevant but my `kubectl` version:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pfischer8989** [comment]
Changing the client version did not help me. 

Ninefingers:crossplane pfischer$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
Ninefingers:crossplane pfischer$ helm install crossplane crossplane-master/crossplane -n crossplane-system  --devel
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.controller.properties.deployment.properties.spec.properties.strategy.properties.rollingUpdate.properties.maxSurge): unknown field "x-kubernetes-int-or-string" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.controller.properties.deployment.properties.spec.properties.strategy.properties.rollingUpdate.properties.maxUnavailable): unknown field "x-kubernetes-int-or-string" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps]

**Comment by muvaf** [comment]
@pfischer8989 Right, it turned out that `kubectl` version is not relevant. I closed this issue since Crossplane _can_ be installed to Kubernetes versions lower than 1.15, it's just that one needs to disable the OpenAPI validation in the **client**. Hence, I opened the following issue to track the necessary changes in Helm3 and controller-runtime together with workaround: https://github.com/crossplaneio/crossplane/issues/1170
