### ISSUE TITLE
Add gcp-credentials.sh to stack-gcp-minimal to generate credentials & accept project-id param / env-var for clean curl | bash

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#1171]
### What problem are you facing?
was talking with @jbw976 @displague and @rathpc and would like to add a targeted variant of [gcp-credentials.sh](https://github.com/crossplaneio/crossplane/blob/master/cluster/examples/gcp-credentials.sh) to [stack-gcp-minimal](https://github.com/crossplaneio/stack-gcp-minimal) that accept command-line variables or env variables for PROJECT_ID that (a) skips all the prompts if PROJECT_ID is specified and (b) only outputs the creds JSON, so we can provide easy bootstrap instructions so users can:
1. curl | bash [gcp-credentials.sh](https://github.com/crossplaneio/crossplane/blob/master/cluster/examples/gcp-credentials.sh) from an EasyGCP getting started page
1. copy / paste the output of this curl | bash command into the `Provider Secret`

Note that [stack-gcp-minimal](https://github.com/crossplaneio/stack-gcp-minimal) is designed to be forked/copied so infra owners can create a custom infra configs, with more or less resources created as part of their standard configs, which may in turn require more of less service permissions that the generated creds needs to have access to. Keeping the creds init script (secret / service account creation / permissions granting) in the [stack-gcp-minimal](https://github.com/crossplaneio/stack-gcp-minimal) repo is a more maintainable pattern that also simplifies the customization UX when forking/copying.

### How could Crossplane help solve your problem?
Add a targeted variant of [gcp-credentials.sh](https://github.com/crossplaneio/crossplane/blob/master/cluster/examples/gcp-credentials.sh) to [stack-gcp-minimal](https://github.com/crossplaneio/stack-gcp-minimal)as above.

https://github.com/crossplaneio/stack-gcp-minimal/pull/2

**Comment by displague** [comment]
Sounds good - we discussed moving this script to the easy-gcp stack repository so folks looking to create a similar pattern with their stacks can follow the pattern.

We'll add additional services (if needed) to the list those for which the script gets permission.

The output will be simplified to only include the secret, sans base64 if possible.
