### ISSUE TITLE
template stack controller hardening: permissions

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#1184]
### What problem are you facing?

Now that we have an initial version of the template stacks controller, we want to make it more robust. This ticket covers improvements to the permissions and RBAC usage.

### How could Crossplane help solve your problem?

I'm going to list several improvements.

* [ ] RBAC permissions are set correctly
* [ ] The template stack controller's render phase should run with appropriate permissions. Any jobs which are created should also run with appropriate permissions

The stack-manager generates a Deployment and SA for normal stacks.
For these template stacks, the Deployment will be injected into the Stack (ignoring any install.yaml) as the render controller.
SA will need additional privileges from those normal stack controllers get, including:
 * read/watch/list StackConfiguration
 * create Job

The Job should be run with a matching SA absent the create Job rule.
_In support of #1197, the SA and Job must be created in the 'host', and the Job's podSpec must include the Kubernetes context of the tenant and not inherit the host's context._

**Comment by muvaf** [comment]
Should be addressed by https://github.com/crossplaneio/crossplane/issues/1209

@suskin please reopen if I'm missing something.

**Comment by suskin** [comment]
I believe this is relevant for #1211 as well.

In general I prefer to document the problems we're trying to solve in addition to the specific implementations we think we should take to solve the problem, so that the people doing the work can figure out the implementation on their own (when they have the knowledge and skills to do so). This is more of a problem-oriented ticket. I agree that maybe we don't need all of the implementation tickets **and** individual problem tickets, but I'd like to document the problems somewhere so that we use them as part of our definition of done for the work. I'll probably move them into a deliverable-oriented ticket that links to multiple of the implementation tickets so that we have them all in one place.
