### ISSUE TITLE
Update connection secret naming override in databases to pattern in buckets

### ISSUE THREAD

**Issue by lukeweber** [crossplaneio/crossplane#119]
Migrate databases to override the connection secret in the same way that the buckets do. 

Currently in the databases spec there is a connectionSecretRef that can either act as an override name or is set with a default name after the database has been initialized. The reason for the change is to not have the operator need to conditionally update the Spec after initialization and instead only update the status.

The bucket pattern is to move ConnectionSecretRef into status, and to add a override to Spec like the following:
```go
S3BucketSpec struct {
...
ConnectionSecretNameOverride string `json:"connectionSecretNameOverride,omitempty"`
}

S3BucketStatus struct {
...
ConnectionSecretRef v1.LocalObjectReference `json:"connectionSecretRef,omitempty"`
}
```

**Comment by negz** [comment]
I'd hope to resolve this as part of https://github.com/crossplaneio/crossplane/issues/451.
