### ISSUE TITLE
template stack controllers: shut down controllers that are no longer needed

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#1193]
### What problem are you facing?

As part of the template stacks model, we create new controllers for new types that should be watched. The way that we're [currently](https://github.com/crossplaneio/crossplane/blob/d87543bbcef0bb0b54776b9022aee666e7a41422/pkg/controller/stacks/templates/setupphase_controller.go#L151) doing this is by adding a new controller-runtime controller to an existing manager in an existing pod. However, there isn't a good way to shut them down at this time.

### How could Crossplane help solve your problem?

Investigate options for shutting down controllers when they're no longer needed, such as when a watched CRD no longer exists.

There are a couple potential high-level options for this:

* Use controller-runtime code to stop the controllers, by doing one of the following:
  - Add our own
  - Work with controller-runtime folks to add it
* Run controllers in their own pods so they can more easily be shut down when they're no longer needed

**Comment by muvaf** [comment]
Should be addressed by https://github.com/crossplaneio/crossplane/issues/1209
