### ISSUE TITLE
template stack hardening: support host awareness

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#1197]
### What problem are you facing?

As part of making the stack manager host-aware, we'll also want the shared template stack functionality to be host-aware.

This may be covered by the existing work which Hasan is working on, but I'm opening a ticket to track it because there will be at a minimum some syncing and coordination involved.

### How could Crossplane help solve your problem?

Coordinate with Hasan and the existing work to support host awareness.

* [One-pager](https://github.com/crossplaneio/crossplane/pull/1138)
* [Existing PR](https://github.com/crossplaneio/crossplane/pull/1139)

**Comment by displague** [comment]
In support of host-aware environments the template stack Job must be created in the 'host', and the Job's podSpec must include the Kubernetes context of the tenant and not inherit the host's context.
The Render controller will need to create an SA (related #1184) for the existing render Job.

**Comment by muvaf** [comment]
This should be addressed by https://github.com/crossplaneio/crossplane/issues/1209 given that `Stack`s are already host-aware.

@suskin please reopen if I'm missing something.

**Comment by suskin** [comment]
> `Stacks` are already host-aware

@muvaf I suppose I'm not sure what you mean by host-aware in this context. This ticket is referring to the effort (if any) which will be needed to make any deployments, jobs, and kubernetes cluster manipulation work in a [host-aware environment](https://github.com/crossplaneio/crossplane/pull/1138) for any of the template stack logic. What are you referring to?

**Comment by suskin** [comment]
In testing the work that's happening in #1209, #1210, and #1211, it looks like we don't need to do anything extra to get this (like Muvaffak was saying). I'm going to keep this open while that work is still settling, but we shouldn't need to do any work for this. We may want to add host awareness to the list of test scenarios we exercise though.

**Comment by displague** [comment]
@suskin, this was verified during https://github.com/crossplaneio/crossplane/issues/1210 testing. Is there anything left to do here?
