### ISSUE TITLE
GoDoc docs generation for codebase

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#12]
We should be generating and publishing full documentation for the codebase using `godoc`, which means we need to have fully commented code in order to generate the docs.  This is especially important for the library/utility functions that will help developers add support for more resources. This should be published publicly for dev reference.

Links:
https://blog.golang.org/godoc-documenting-go-code
https://godoc.org/golang.org/x/tools/cmd/godoc

**Comment by negz** [comment]
https://godoc.org/github.com/crossplaneio/crossplane/pkg

Our linter has required all public methods and types be commented, and godoc.org automatically exposes our Godoc. Many of our comments need improvement, and much of our code is not exported (when perhaps it should be), but I think this is done. Please reopen if you disagree!

**Comment by jbw976** [comment]
Woah, I didn't know that we were already published on godoc, I don't remember us doing any work to make that happen.  That's great!

**Comment by negz** [comment]
@jbw976 Yep, https://godoc.org polls any repo that can be `go get` on demand when you browse to it. :)
