### ISSUE TITLE
template stacks: Template stack controller should watch TemplateStack resource and generate Stack CR

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#1209]
We have decided to merge the template stack workflow with normal stacks workflow as early as possible to make use of existing mechanisms such as RBAC, host awareness and shutdown of controllers.

This issue represents the part of the implementation where there is a `TemplateStack` (called `StackConfiguration` right now) CR in the cluster and a controller should see and generate a `Stack` object whose deployment section calls the generic controller(s) that will watch the specific CRD(s).

`TemplateStack` CR should include the fields that `StackConfiguration` has today as well as metadata that will be put into the `Stack` CR. It's pretty much like the merger of `StackConfiguration` and `Stack`. Today `Stack.spec` looks like the following:
```go
type StackSpec struct {
	AppMetadataSpec `json:",inline"`
	CRDs            CRDList         `json:"customresourcedefinitions,omitempty"`
	Controller      ControllerSpec  `json:"controller,omitempty"`
	Permissions     PermissionsSpec `json:"permissions,omitempty"`
}
```
and `StackConfiguration.spec`:
```go
type StackConfigurationSpec struct {
	// Important: Run "make" to regenerate code after modifying this file
	Behaviors StackConfigurationBehaviors `json:"behaviors,omitempty"`
}
type StackConfigurationBehaviors struct {
	CRDs   map[GVK]StackConfigurationBehavior `json:"crds,omitempty"`
	Engine ResourceEngineConfiguration        `json:"engine,omitempty"`
	Source StackConfigurationSource `json:"source,omitempty"`
}
```

What we want to do is to enable the stack author to write a fully-fledged Stack metadata if they want while keeping the possibility of making it as minimal as just defining the behaviors. So, the resulting API could look like the following:
```go
type TemplateStackSpec struct {
	AppMetadataSpec `json:",inline"`
	Permissions     PermissionsSpec `json:"permissions,omitempty"`
	Behavior       Behavior `json:"behavior,omitempty"`
}
type Behavior struct {
	GVK   string `json:"gvk,omitempty"`
	EngineConfiguration EngineConfiguration        `json:"engineConfiguration,omitempty"`
	Source Source `json:"source,omitempty"`
}
```

Note that `Controllers` section of `Stack` object is omitted because that will be generated by the template stack controller calling generic controller. `CRDs` of `Stack` object is also moved to `Behaviors.CRDs` to remove the duplication.

Another thing to be aware of is that the generic controller will `GET` this instance of `TemplateStack` object. So, template stack controller needs to append a permission to `PermissionsSpec` to allow the service account of the controller deployment to access that one named instance of `TemplateStack` object by the controller.

There is no change in the `Stack` or `StackInstall` structs. Template stack controller will be smart enough to generate a `Stack` object from the `TemplateStackSpec` above.

**Comment by displague** [comment]
> Another thing to be aware of is that the generic controller will GET this instance of TemplateStack object. So, template stack controller needs to append a permission to PermissionsSpec to allow the service account of the controller deployment to access that one named instance of TemplateStack object by the controller.

That's what I was looking for. Will the generic controller also need to create Job resources?

**Comment by muvaf** [comment]
> Will the generic controller also need to create Job resources?

No. It will directly create the resources with controller-runtime client. The author should fill the `dependsOn` section in `app.yaml` just like they do for normal stacks in order to get the RBAC stuff generated correctly for that generic controller `Pod`.

**Comment by suskin** [comment]
I've created #1214 as an early cut of the data model and expected semantic of the controller, to help us coordinate on this work. After thinking about it a little while starting the implementation, it seems like it'd be the cleanest if we could move the controller generation logic up into the step when/before the stack definition is created, so that the logic that copies the stack definition over to the Stack is as dumb as possible. That seems like it'll make migrating things in the future a little easier.

**Comment by muvaf** [comment]
> it seems like it'd be the cleanest if we could move the controller generation logic up into the step when/before the stack definition is created, so that the logic that copies the stack definition over to the Stack is as dumb as possible.

I think as long as there is a separate object which contains the behavior definitions and can be fetched by the generic controller, it should work.

After our discussion yesterday, in the long term, I was thinking we'd probably end up in a `stack.yaml` that could be either `kind: TemplateStack` or `kind: Stack` and the flow of these two kinds would be independent, meaning `TemplateStack` wouldn't create `Stack` but their controllers would share the same logic for the same things. Also `TemplateStack` kind and its controller would live in another stack (possibly extending https://github.com/crossplaneio/resourcepacks/ to be a template stack manager like crossplane repo with different flags). But that's all long term thinking. For now, an object that has the behavior definitions as well as a `Stack` object that deploys the generic controller should be fine.
