### ISSUE TITLE
template stacks: generic go controller for watching schemaless template stack CRDs

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#1211]
We have decided to merge the template stack workflow with normal stacks workflow as early as possible to make use of existing mechanisms such as RBAC, host awareness and shutdown of controllers.

Part of the implementation plan is that we have a generic controller that runs the templating engines (kustomize, helm) without need to know the CRD schema. This controller should take the following inputs (possibly as flags):
- Name/Namespace of the `TemplateStack` CR.
- GVK to reconcile. Since `TemplateStack` could want to aim more than one CRD, we need to know which one to reconcile.

The engine, hooks and all other information will be fetched from `TemplateStack` CR.

Today we have a render phase controller baked into crossplane binary that creates `Job`s that calls engine binaries (helm, kustomize). However, this won't work for deployments since it will need to continuously run and watch the resources, act on the changes and update the status. I think the [generic controller used in easy stacks](https://github.com/muvaf/crossplane-resourcepacks/) is a good candidate for this job. It already has kustomize engine and is easy to extend to other engines. Things that need to be implemented in that controller:
- Fetch `TemplateStack` CR for configuration.
- It's a library right now. Create a binary that gets the flags such as GVK and `TemplateStack` CR name/namespace.
- Refactor reconciliation to work on `unstructured.Unstructured`; this should be easy since that's almost the case right now given that the resource interfaces are very lean already.

**Comment by suskin** [comment]
> Things that need to be implemented in that controller

Some of the things in the list are already implemented in the render phase controller, so adapting the render phase controller would also work as an approach.

After syncing, we agree that our goal is to get to a working system first, then to make things More Correct later, and we expect that we don't know what the most correct approach will be until the system has settled a bit. We plan to leave the choice of which specific implementation approach to use up to the person who does the work, and want them to be able to factor the goals and the different options into their decision.
