### ISSUE TITLE
Include CRD read access to environment and namespace viewers

### ISSUE THREAD

**Issue by displague** [crossplaneio/crossplane#1232]
### What problem are you facing?

The RBAC refinement offered by #1190, #1215, and #1219 needs additional tweaking.

In order for Namespace or Environment viewers to identify the Stack resources available and examine the UI-Schemas stored in those CRDs, these personas will need access to CRD resources.

### How could Crossplane help solve your problem?

Include CRD read access to environment and namespace viewers.

**Comment by jbw976** [comment]
Fixed by #1234
