### ISSUE TITLE
CloudSQL "invalid" Endpoint Value

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#138]
`CloudSQLinstance` reports `Instance connection name` as an `Endpoint` value.
However, this does not appear to be correct. 

In our initial implementation, we use `cloudsql-proxy` to establish a database connection. 
Later on, we agreed that we do not need `cloudsql-proxy` for connections w/in the same GCP project.

Requested change: Use `Public IP address` value for the `Endpoint`.

**Comment by negz** [comment]
I believe we now expose both the public and private IP.
