### ISSUE TITLE
Use clusterSelector to assign workloads to clusters

### ISSUE THREAD

**Issue by bassam** [crossplaneio/crossplane#153]
We should consider using a `clusterSelector` to assign a workload to a Kubernetes `Cluster`. This work in a similar fashion to `nodeSelctor` on a pod (see [here](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector)).

**Comment by negz** [comment]
Fixed by https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-workload-scheduler.md
