### ISSUE TITLE
Consider renaming Workload to something more representative

### ISSUE THREAD

**Issue by bassam** [crossplaneio/crossplane#157]
The intention of `Workload` is to capture a schedule-able unit of work that runs on target Kubernetes clusters. That could be deployments, ReplicaSets, StatefulSets, helm charts, and many other types of workloads people run on Kubernetes clusters. We might want to call the API Group `workloads.crossplane.io` and be more specific with the Kinds. For example `DeploymentAndService` and `HelmInstall` and others.

**Comment by negz** [comment]
https://github.com/crossplaneio/crossplane/blob/7b60970/design/complex-workloads.md

Per the above design we went with `KubernetesApplication` for the successor to `Workload`. `Workload` still exists, but is slated for removal per https://github.com/crossplaneio/crossplane/issues/456.
