### ISSUE TITLE
Generic Abstract KubernetesCluster properties

### ISSUE THREAD

**Issue by lukeweber** [crossplaneio/crossplane#166]
General Kubernetes Cluster properties should be added to the resource claim (abstract) type and all provider cluster handlers should be updated to honor/resolve them during the provisioning flow.

* Add resolver in *_handler.go
* Add types/fields in KubernetesCluster

Fields:
- KubernetesVersion
- ?

**Comment by negz** [comment]
Related to #870.

**Comment by negz** [comment]
I'm going to close this as superceded by https://github.com/crossplaneio/crossplane/issues/1106. Our current thinking is that infra operators will be able to define their own claim kinds with the fields that are relevant to their interests (and applicable to the infrastructure stacks they use).
