### ISSUE TITLE
Standardize connection secrets

### ISSUE THREAD

**Issue by lukeweber** [crossplaneio/crossplane#168]
Connection Secrets are very similar, but there are small variations across the codebase. Currently, we dynamically set the LocalObjectReference if none was set inside the Spec. 

I would like to standardize on the following:
* Set ConnectionSecretRef in Status, not in Spec
* Add an override field in Spec to make ConnectionSecretName deterministic when needed
* else Default to the name of the object + a random suffix if no name is set. Default should make sure to not overflow max object length and trim the name if necessary.

_Originally posted by @lukeweber in https://github.com/crossplaneio/crossplane/pull/150_

**Comment by negz** [comment]
Relates to #119, I believe. I just went to raise the same issue after I noticed our inconsistent implementation of `ConnectionSecretNameOverride` - I didn't realise I should be including it in types I wrote. Perhaps we need a class we can embed in all Specs that contain common fields like this?

**Comment by negz** [comment]
@lukeweber I forgot you already raised this issue when I was writing up my proposed solution in #518. I'm curious how you feel about said proposal.
