### ISSUE TITLE
RDSInstance cluster reference drift from actual name

### ISSUE THREAD

**Issue by lukeweber** [crossplaneio/crossplane#201]
Working on demos last night, I applied (kubectl apply) the workloads multiple times and ended up with multiple rds instances. And finally the one that I was attached to in my workload had a different instance name that the one that was running. 

Interestingly, the endpoint had the correct url with the correct reference. I'm guessing our name generation may be getting clobbered by by kubectl updates even if the object is unchanged and we probably shouldn't be overwriting an object name if it's already named.

**Comment by negz** [comment]
We've rewritten the RDSInstance controller completely since this issue was raised, so I'm going to optimistically close it out. Please reopen if anyone sees this happening again!
