### ISSUE TITLE
CRD updates should be retried upon conflict (409)

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#208]
When we call `Update` from our controllers to update CRD (status for example), it's possible to get a 409 conflict because another entity has updated the instance and we have a stale reference.  We should retry these updates by reapplying our changes to the latest version and updating again.

There is a helper function in client-go that facilitates this: https://github.com/kubernetes/client-go/blob/master/util/retry/util.go#L61

**Comment by ravisantoshgudimetla** [comment]
> another entity has updated the instance and we have a stale reference.

Which entity are you referring to here? If the entity is one of the custom controllers, can we set up informers/shared informer across those custom controllers, there by avoiding cache duplication and its deduplication?

**Comment by jbw976** [comment]
that's actually a good question @ravisantoshgudimetla. i think there's some more investigation to be done to understand who/what exactly is making changes to the CRD besides the controller responsible for it.

**Comment by negz** [comment]
Don't we effectively retry by requeuing the reconciliation?

**Comment by jbw976** [comment]
I think so @negz, as long as controllers are written correctly and can (attempt to) reconcile observed state with desired state on any `Reconcile` call, this should happen OK.
