### ISSUE TITLE
Adding Provider doesn't actually adds a provider

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#238]
https://crossplane.io/docs/v0.1/cloud-providers.html

We need either update the section title, for example, "Configuring Cloud Provider".
Or, we need to include a step(s) that actually adds a provider, i.e. `kubectl create[apply] -f -`, etc.

**Comment by negz** [comment]
https://crossplane.io/docs/v0.3/cloud-providers.html

As of 0.3 we link through to the services guide that explains how to do this.
