### ISSUE TITLE
Removing Workload does not remove Workload artifacts (secrets)

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#244]
Steps to repo:
1. Deploy a `Workload` from the Getting started examples (any cloud provider)
2. Delete the same `Workload`

- Expected: all `Workload` artifacts are removed from the target clusters (except the namespace)
- Actual: `demo-*-secret` is left behind.

**Comment by ZachEddy** [comment]
I notice that [`_delete`](https://github.com/crossplaneio/crossplane/blob/master/pkg/controller/compute/workload/workload.go#L264) will remove the service and deployment, but I don't see anything related to removing secrets. That seems (maybe?) related. If so, would resolving this issue just be a matter of adding code to `_delete` that removes the secret, or is it a bit more involved than that?

**Comment by jbw976** [comment]
Hey @ZachEddy, I synced up with @ichekrygin and we think it'd be great if you wanted to go ahead and start working on this issue!   The [contributing guide](https://github.com/crossplaneio/crossplane/blob/master/CONTRIBUTING.md) should get you started, I especially make heavy use of the local build/test flow with minikube as described in the [local build guide](https://github.com/crossplaneio/crossplane/blob/master/cluster/local/README.md).  Let us know if you have any questions or issues at all, you can ask here or on the [Slack #dev channel](https://crossplane.slack.com/messages/CEF5N8X08/).

We're pumped to get new contributors to this project, so we're here to help make the contribution process smoother for you, and apply any of the lessons learned from bumps in the road back into our docs to make it easier for the next new contributor 🤕  Thanks!
