### ISSUE TITLE
Controller Reconcile Events

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#25]
Decide on when to record events

```
        // Fetch Provider Secret
	secret, err := r.kubeclient.CoreV1().Secrets(request.Namespace).Get(instance.Spec.SecretKey.Name, metav1.GetOptions{})
	if err != nil {
		r.recorder.Event(instance, corev1.EventTypeWarning, "Error", err.Error())
		return reconcile.Result{}, err
	}

	// Retrieve credentials.json
	data, ok := secret.Data[instance.Spec.SecretKey.Key]
	if !ok {
		setInvalid(&instance.Status, fmt.Sprintf("invalid GCP Provider secret, %s data is not found", instance.Spec.SecretKey.Key), "")
		return reconcile.Result{}, r.Update(ctx, instance)
	}
```
In the first block, we are trying to retrieve a secret, and if the secret is not found (i.e. unmet requirement), we simply break out from the reconciler w/ error, while not changing the provider stats (i.e. it is not invalid nor valid). At the same time, we are recording the event, so that the user has a reference point on why is this provider is not becoming valid.

In the second block, we have retrieved the secret (i.e. all requirements are satisfied), and we begin credentials validation. If the secret format is invalid (in this case we cannot find data element with provided key) - we make this provider as invalid and break out from the reconcile loop. Since we have updated the status, the user has a reference on the status/state of this provider, including the `Reason`.
Next, reconcile iteration will attempt to re-process (re-validate) the secret credentials, possibly resetting state of this provider to `Valid` or `Invalid` (for this or other reasons).

**Comment by negz** [comment]
Related to https://github.com/crossplaneio/crossplane/pull/858

**Comment by negz** [comment]
I'm working on this as part of https://github.com/crossplaneio/crossplane-runtime/issues/104 - I'm going to close this issue and use the newer one to track this.

**Comment by negz** [comment]
This was fixed by https://github.com/crossplaneio/crossplane-runtime/pull/108 - all the crossplane-runtime reconciles now emit events.
