### ISSUE TITLE
Architecture/vision document should be more prominent

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#251]
The arch/vision doc is a fantastic resource, but it's not very prominent on the crossplane docs or readme.  We should make an easier to find link in the readme and docs that point to the [architecture document](https://docs.google.com/document/d/1whncqdUeU2cATGEJhHvzXWC9xdK29Er45NJeoemxebo/edit?usp=sharing) and drive more traffic to it

**Comment by jscharber** [comment]
I don't mind taking this on, just want to talk about structure first.

**Comment by jbw976** [comment]
Hi @jscharber that would be great if you wanted to submit a PR for this.  I was thinking it could be fairly simple.  To my knowledge, the architecture document (which is an awesome read by the way) is listed on these 2 README's:
* https://github.com/crossplaneio/crossplane/blob/master/README.md
* https://github.com/crossplaneio/crossplane/blob/master/docs/README.md

On those pages, it's just mentioned in passing very casually:
> For a deeper dive into Crossplane, see the architecture document.

The simplest thing we could do is to create a new section for it so it is more visible, something like:

## Architecture and Vision
The full architecture and vision of the Crossplane project is described in depth in this [public document](https://docs.google.com/document/d/1whncqdUeU2cATGEJhHvzXWC9xdK29Er45NJeoemxebo/edit?usp=sharing).  Read more about blah blah (just a bit more description of the content)...

What do you think?
