### ISSUE TITLE
Does Crossplane have plan to support bare metal k8s cluster?

### ISSUE THREAD

**Issue by iamzhout** [crossplaneio/crossplane#260]
**What should the feature do:**
Crossplane can support bare metal kubernetes deployment

**What is use case behind this feature:**
For kubernetes deployment on top of bare metals inside company 

**Environment**:
Linux / Windows

**Comment by bassam** [comment]
Yes definitely. One way to do so is to support attaching existing Kubernetes clusters. We would then support deploying workloads on them. Would love to hear about your scenarios. Also please feel free to join our community meeting.

**Comment by iamzhout** [comment]
Hi @bassam Thanks for reply.

My scenario is mainly Kubernetes  cluster on bare metal (on-premises) inside our company network, with workload such as stateless micro-services, so maybe under Crossplane framework, the proper way is to implement dedicated `ResourceClass` for each kind of micro-service per my limited understanding on Crossplane?

And another interesting point to me is that in [Roadmap  v0.2 - Run Real-world Applications](https://github.com/crossplaneio/crossplane/blob/master/ROADMAP.md#v02---run-real-world-applications), it says `Support for automatically creating Kubernetes Clusters`, so will some sig effects will be used such as [cluster-api](https://github.com/kubernetes-sigs/cluster-api), and will it cover cloud providers like (aws, azure, gce) or also including baremetal Kubernetes deployments.

**Comment by bassam** [comment]
> so maybe under Crossplane framework, the proper way is to implement dedicated ResourceClass 

I wonder if you can model these microservices as just workloads.

> And another interesting point to me is that in Roadmap v0.2 - Run Real-world Applications, it says Support for automatically creating Kubernetes Clusters

we already support dynamic provisioning of managed Kubernetes clusters. The feature you point at here is for Kubernetes Clusters to be provisioned based on an autoscaler as in #159

**Comment by negz** [comment]
@iamzhout We now support this feature! Please take a look at https://blog.crossplane.io/crossplane-v0-7-schedule-workloads-to-any-kubernetes-cluster-including-bare-metal/ and let us know if it would solve your use cases.

**Comment by jbw976** [comment]
I'm going to optimistically close this issue with the new support @negz pointed out, but please do weigh in and let us know your thoughts if you get the time @iamzhout :)

**Comment by muvaf** [comment]
For future reference, [provider-helm](https://github.com/crossplane-contrib/provider-helm) is what we use to schedule apps to remote clusters now.
