### ISSUE TITLE
Converge on a consistent controller design

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#269]
This will serve as an epic or umbrella issue for all the issues having to do with figuring out and implementing a consistent pattern and/or best practices for our controllers.

We have some fragmentation across the codebase as different controllers were authored by different developers, so we should converge on a single approach and have consistency across the codebase.

**Comment by negz** [comment]
```
$ go test github.com/crossplaneio/crossplane/pkg/controller/gcp/compute -run "^(TestReconcile)$"                                                  
ok      github.com/crossplaneio/crossplane/pkg/controller/gcp/compute   0.023s [no tests to run]                                                                           

$ go test github.com/crossplaneio/crossplane/pkg/controller/aws/compute -run "^(TestReconcile)$"                                                  
ok      github.com/crossplaneio/crossplane/pkg/controller/aws/compute   0.025s [no tests to run]                                                                           

$ go test -timeout 30s github.com/crossplaneio/crossplane/pkg/controller/azure/compute -run "^(TestReconcile)$"                                   
2019/01/24 12:10:06 fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory                                                                                   
FAIL    github.com/crossplaneio/crossplane/pkg/controller/azure/compute 0.031s
```

I notice the Azure controller has a dependency on `etcd` from Kubebuilder. I considered raising an issue for this, but it seems like a subset of this issue.

**Comment by ichekrygin** [comment]
@negz, you're correct, it is a subset. We should update (rewrite) controller unit test to follow "new" paradigm, i.e. w/out `etcd` + `kubeapiserver` involvement. For example: https://github.com/crossplaneio/crossplane/tree/master/pkg/controller/gcp/compute

**Comment by negz** [comment]
https://github.com/crossplaneio/crossplane/blob/7b6097/design/reconciler-patterns.md

We've iterated once or twice on the design @jbw976 mentions in this issue, with the latest iteration being captured in the above design document. This issue is still very valid, but I believe we need some more work to reach consensus on a design before we proceed with refactoring.

**Comment by negz** [comment]
Relates to https://github.com/crossplaneio/crossplane/issues/447

**Comment by negz** [comment]
Relates to https://github.com/crossplaneio/crossplane/issues/298

**Comment by jbw976** [comment]
Relates to #510

**Comment by muvaf** [comment]
The generic managed reconciler implemented in https://github.com/crossplaneio/crossplane/pull/603 is decided to be used for all controllers as can be seen here #615 , #616 and #617 . 

@jbw976 We can keep this open to signal that it's an ongoing effort or close it as we do have 1 pattern now for (almost) all controllers.

**Comment by jbw976** [comment]
My take is that with the new general managed reconciler now in master, that has captured the intent of this issue.  We are tracking through the provider specific epics the remaining work to update all of the controllers to this new pattern.

Any documentation/guide work around how to use this controller and how to build high quality controllers/reconcilers for partners and contributors will be covered by #610.  I'd like to close this issue now.
