### ISSUE TITLE
General resource controller should be used broadly

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#276]
The [general resource controller](https://github.com/crossplaneio/crossplane/blob/master/pkg/controller/core/resource_controller.go) is currently being used by MySQL and PostgreSQL, but I think it could also be used by other resources such as buckets and clusters.  I think investing in this makes sense from an engineering standpoint to reduce duplicated code and consolidate our efforts into a single well tested and reliable implementation.

**Comment by prasek** [comment]
@jbw976 is this handled with #612 or separate?
