### ISSUE TITLE
Azure resource groups should be modeled

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#277]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** Azure has the concept of a "resource group" that is used for most every API I've come across so far.  We are currently capturing the resource group name in most of our Azure models, but this requires the user to manually create the resource group ahead of time.  It would be better if Azure resource groups were just another resource type that Crossplane could create on behalf of the user and the group could just be referenced from other Azure types.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview#resource-groups

**Comment by HashedDan** [comment]
I'd be happy to take on this issue! Feel free to let me know if there is any additional info that I may need.

**Comment by jbw976** [comment]
awesome @HashedDan! I would recommend as a first step to sketch out a sample `yaml` that shows what you think the experience should look like.  How would the user create a resource group using Crossplane and how would they reference it when creating a resource later on?  Let me know if you have any questions, I'd be happy to work with you on that.

**Comment by HashedDan** [comment]
Closed by #391
