### ISSUE TITLE
Design for workload scheduler

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#278]
The workload scheduler will have a fair amount of complexity and needs to have a design effort authored and collaborated on.  This issue tracks the work of authoring a design doc for the workload scheduler.

**Comment by jorgecotillo** [comment]
For Azure, regarding data plane performance, the scheduler must place storage accounts in the same region (and resources consuming these storage accounts should have VNET peering enabled, to allow communication to happen using Microsoft's backbone connections which improves performance as well). I'd love to collaborate on this design as well.
