### ISSUE TITLE
GitLab deployment

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#284]
GitLab is a complicated application that would make a great real-world use case to target with Crossplane.  This will significantly help to broaden the applicability and usefulness of Crossplane.

GitLab currently supports deploying with a Helm chart as described in the most up to date docs at https://gitlab.com/charts/gitlab/tree/master/doc.

We should work with the GitLab deployment experts to define the experience and required components for deploying the full solution.  At the end of this issue, a user should be able to deploy GitLab in a portable way to any of the supported environments.

**Comment by negz** [comment]
https://github.com/crossplaneio/crossplane/issues?q=is%3Aopen+is%3Aissue+label%3Agitlab

I've created the `gitlab` label to gather all the work we need to do to get Gitlab running seamlessly via Crossplane.
