### ISSUE TITLE
Support deployment of Virtual Machines

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#286]
Similar to #285, to support real-world applications that are heterogeneous, Crossplane should support the portable deployment of Virtual Machines for applications that need server level resources.  We will need to do design work and up front thinking to define what this support should look like.

**Comment by negz** [comment]
Relates to https://github.com/crossplaneio/crossplane/pull/838

**Comment by prasek** [comment]
Relates to https://github.com/packethost/crossplane-provider-equinix-metal/pull/14
