### ISSUE TITLE
`storage` resource claims map to `database` resources.

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#300]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:** Resource claims and resources appear under consistent, intuitive API hierarchies. For example if SQL database resource claims are under the `storage.crossplane.io` API group, I would expect SQL database resources to be under `storage.provider.crossplane.io`, not `database.provider.crossplane.io`.

**How to reproduce it (minimal and precise):**
Compare the content of the `pkg/apis` tree. For example:

https://github.com/crossplaneio/crossplane/tree/master/pkg/apis/storage
https://github.com/crossplaneio/crossplane/tree/7003069/pkg/apis/gcp/database
https://github.com/crossplaneio/crossplane/tree/7003069/pkg/apis/gcp/storage

Note that blob storage buckets and SQL database resource claims both fall under `storage`, but their resources are separated into the `database` and `storage` classes.

**Comment by jbw976** [comment]
Congratulations on fixing your very first opened issue @negz 🎉 lol
