### ISSUE TITLE
Add documentation for how to add support for a new resource

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#302]
In addition to some other new contributor focused documentation that we need to beef up, we should also have documentation for how to add support for a new resource.  The task of adding the API/CRD, controller, unit tests, etc. would definitely benefit from having guidelines and best practices captured.

Some items to include:
- modeling the resource in types.go, choosing API group and version
- generating the CRD and validation with `make manifests`
- generating deep copy code with `make codegen`
- integrating cloud provider library packages, vendoring
- client interfaces and wrappers in `pkg/clients`
- writing a controller/reconciler, structure/patterns, best practices, error handling
- unit tests, testability paradigm, code coverage
- dynamic provisioning, resource classes, resource claims, allowing the resource to be provisioned in a portable way

**Comment by negz** [comment]
I'm interested in working on some of this once I've gone through the process with the Redis controllers.

**Comment by HashedDan** [comment]
@negz I would also love to be part of this when I finish up the azure resource groups

**Comment by hasheddan** [comment]
Might be a cool idea to setup a [Katacoda](https://www.katacoda.com/) tutorial for this.

**Comment by jbw976** [comment]
This will be covered in #610
