### ISSUE TITLE
Investigate if we can remove the client-go Interface object from all controllers

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#319]
As noted in https://github.com/crossplaneio/crossplane/pull/317#discussion_r257371819, our controllers have both a controller-runtime client and a client-go client.  It would be great if we could only use the controller-runtime client and remove the superfluous client-go client.

The usage of the client-go client is around Secrets access right now, and I have a dim memory of the controller-runtime not doing the right thing for Secrets (maybe it couldn't get secrets in other namespaces?).  This will require an investigation to ensure we can use only the controller-runtime client without any loss of functionality, and then clean up and consolidate all references to only use the controller-runtime client going forward.

controller-runtime client: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/interfaces.go#L85

client-go client: https://github.com/kubernetes/client-go/blob/master/kubernetes/clientset.go#L59

**Comment by negz** [comment]
I had also suspected there might be some oddness using the controller-runtime `client.Client` to work with Secrets, but so far I have had no issues using it to implement https://github.com/crossplaneio/crossplane/pull/307. I've been using the following helper, in which `r.kube` is a `client.Client`:

```go
func (r *Reconciler) upsertSecret(ctx context.Context, s *corev1.Secret) error {
	n := types.NamespacedName{Namespace: s.GetNamespace(), Name: s.GetName()}
	if err := r.kube.Get(ctx, n, &corev1.Secret{}); err != nil {
		if kerrors.IsNotFound(err) {
			return errors.Wrapf(r.kube.Create(ctx, s), "cannot create secret %s", n)
		}
		return errors.Wrapf(err, "cannot get secret %s", n)
	}
	return errors.Wrapf(r.kube.Update(ctx, s), "cannot update secret %s", n)
}
```

**Comment by negz** [comment]
FWIW having written a few controllers at this point I've never found a reason to need to use the `client-go` client directly. I think we should remove it.

**Comment by jbw976** [comment]
I found that I had to use it for the `GetLogs` functionality in the extension request controller: https://github.com/crossplaneio/crossplane/blob/master/pkg/controller/extensions/request/extensionrequest.go#L467

Perhaps that could be done using a raw REST client as described in https://stackoverflow.com/a/32984298/467462

**Comment by negz** [comment]
That's good context! FWIW I don't think we should remove it purely for the sake of removing it, more that we should only use one client (the controller-runtime one) in cases where that is possible such as CRUD-ing secrets.

**Comment by negz** [comment]
I think I've removed all instances of the client-go client during my simple resource class selection work.

**Comment by negz** [comment]
> I think I've removed all instances of the client-go client during my simple resource class selection work.

Sadly not quite. It's gone from the GCP and Azure stacks, but we're still using it to push a configmap to EKS clusters in the AWS controller.

**Comment by negz** [comment]
Eh, there's one controller left and it will very likely go away when we port EKS over to the managed resource reconciler. I'm calling this investigated, and closing. ;)
