### ISSUE TITLE
Failed to set resource binding status due to BindingState JSON marshal failure

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#343]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Creating a PostgreSQL database claim is failing to bind to its CloudSQL concrete type with the following error:
```
    - LastTransitionTime: 2019-03-12T09:02:43Z
      Message: 'json: error calling MarshalJSON for type v1alpha1.BindingState: invalid
        character ''B'' looking for beginning of value'
      Reason: Failed to set resource binding status
      Status: "True"
      Type: Failed
```

This appears to be a regression from #325 

**Expected behavior:**
Resources and Resource Claims should be bound together successfully

**How to reproduce it (minimal and precise):**
Walk through steps in https://crossplane.io/docs/master/postgresql.html

**Environment**:
* Crossplane version (tag, release, helm chart version): https://github.com/crossplaneio/crossplane/commit/82dc64666c7bf7247924423007f5072904518e67
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Minikube

**Comment by negz** [comment]
Whoops! I'll take a look at this.
