### ISSUE TITLE
Support injecting connection info into application configuration files

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#361]
**Is this a bug report or feature request?** Feature Request

**What should the feature do:** Support injecting connection URIs and credentials into application specific configuration files.

**What is use case behind this feature:** Currently Crossplane resources and resource bindings expose their connection URIs as part of their status object. Connection URIs and credentials are also exposed as a `Secret` that is propagated to the Kubernetes cluster to which a `Workload` is scheduled. `Secret` data may be exposed to a container as either a file or environment variable. Unfortunately, not all applications that may run as part of a `Workload` support loading this configuration from an environment variable or as a single variable in a file. Many applications require connection strings and usernames in particular to be specified as part of a configuration file with an application specific schema. 

Ideally it would be straightforward to write a `Workload` in such a way that connection URIs and credentials could be discovered from Crossplane and injected into application configuration. I could see a handful of ways to do this that don't require `Workload` to support templating.

The first two options solve the issue for connection URIs _and_ credentials, but are effectively conventions that put the onus on the `Workload` author:
1. Mount the Crossplane generated `Secret` into an `initContainer` which runs a script that injects it into the configuration file required by the application.
1. Mount the Crossplane generated `Secret` as part of a `Job` that injects it into the configuration file required by the application and writes out said config file as a new `ConfigMap` (or `Secret`).

Crossplane could automate the problem away completely for connection URIs by propagating connection URIs to the hosting Kubernetes cluster as an [`ExternalName` type `Service`](https://kubernetes.io/docs/concepts/services-networking/service/#externalname). These `Services` configure the cluster's internal DNS to create a `CNAME`, so we could ensure  `tcp://myredis.somenamespace:6379` was always a `CNAME` to the actual endpoint of the Crossplane managed Redis instance (for example).

**Comment by negz** [comment]
This is relevant to our Gitlab work in a few places:

* Gitlab expects Kubernetes secrets containing storage bucket credentials to exist and be formatted in a specific way per https://gitlab.com/charts/gitlab/tree/master/examples/objectstorage.
* The Gitlab Helm chart only supports reading passwords from files - everything else appears to be inlined in config files. That said, most Gitlab config files seem to be ERB templates that could be updated to also read connection URIs and usernames from files.

**Comment by WarheadsSE** [comment]
>  That said, most Gitlab config files seem to be ERB templates that could be updated to also read connection URIs and usernames from files

Nailed it. And, we've added `extraVolumes` / `extraVolumeMounts` that could be used to inject these items.

**Comment by negz** [comment]
I think we have some better ideas around how this might be implemented in #70 and #489. I'm going to close this.
