### ISSUE TITLE
Jenkins Builds Failing on Build

### ISSUE THREAD

**Issue by Defilan** [crossplaneio/crossplane#372]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When running a build in Jenkins, the following error occurs:
```
13:23:28  Step 1/7 : FROM arm64v8/alpine:3.7
13:23:28   ---> e013d5426294
13:23:28  Step 2/7 : RUN apk --no-cache add ca-certificates bash
13:23:28   ---> Running in e241d13d63c1
13:23:28  [91mstandard_init_linux.go:190: exec user process caused "no such file or directory"
13:23:28  [0mThe command '/bin/sh -c apk --no-cache add ca-certificates bash' returned a non-zero code: 1
13:23:28  20:23:27 [31m[FAIL][0m
13:23:28  Makefile:16: recipe for target 'img.build' failed
```

**Expected behavior:**
Successful Build 

**How to reproduce it (minimal and precise):**
PRs/Manual Reruns in Jenkins 

**Environment**:
* OS (e.g. from /etc/os-release): Jenkins Linux Environment (GCE)

**Comment by Defilan** [comment]
The GCE template that was being used by Jenkins was almost a year old. A newer template was created back in February 2019. After switching the template from the older one to the newer template, the issue resolved itself. 

Builds are running again at this time.

**Comment by jbw976** [comment]
We saw this recently in #364 also, right?  Was this a different root cause? Do we think the issue is fixed for good now? :)
