### ISSUE TITLE
Consider shortening logger names

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#388]
As discussed in the following PR comments, our logging names are somewhat verbose:
https://github.com/crossplaneio/crossplane/pull/385#discussion_r274086143
https://github.com/crossplaneio/crossplane/pull/385#discussion_r274089142

e.g. `controller.account.storage.azure.crossplane.io`

We can consider shortening these logger names somehow, without losing the knowledge of what part of the code base each logger belongs to.  The rook project uses abbreviated names instead of fully qualified type names, such as `edgefs-op-cluster`.

**Comment by negz** [comment]
I like the idea of copying the controller-runtime pattern in which the loggers are named simply `crossplane.controller`, but have a value with the controller name. For example:

```
# A Crossplane log
2019-06-25T18:58:11.560Z        DEBUG   crossplane.controller   Reconciling     {"controller": "resourceclaim.crossplane.io", "request": "default/ekscluster"}

# A controller-runtime log
2019-06-25T18:58:11.065Z        DEBUG   kubebuilder.controller  Successfully Reconciled {"controller": "kubernetescluster.eks.compute.aws.crossplane.io", "request": "default/ekscluster"}
```

**Comment by negz** [comment]
I'm experimenting with this as part of https://github.com/crossplaneio/crossplane-runtime/issues/104.
