### ISSUE TITLE
Consider removing calls to log.Fatal and log.Panic in unit tests

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#389]
As discussed in https://github.com/crossplaneio/crossplane/pull/385#discussion_r274091661, we should consider updating the pattern for failing and bailing upon extraordinary errors in unit tests.

We are currently relying on `log.Fatal` and `log.Panic`, but to completely remove all references to the standard `log` package, we should consider a separate pattern.

Does our new logging libraries expose this `Fatal` type of functionality?  Should we use `os.Exit`?

**Comment by jbw976** [comment]
Here are all the remaining usages of the standard `log` package, gathered with this command:
```
grep -F -R -l --exclude-dir=vendor '"log"' * | xargs grep -F 'log.'
```

https://gist.github.com/jbw976/235fde37fe09271927a2e0047526af4a

**Comment by hasheddan** [comment]
@jbw976 is this still something that we want to fix?

**Comment by jbw976** [comment]
I think so @hasheddan.  It looks like all offenders are in the https://github.com/crossplaneio/crossplane/blob/master/pkg/test/envtest.go file.
