### ISSUE TITLE
Controllers should support parallel processing of resources

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#4]
All controllers should support the processing of their resources in parallel, i.e. a long operation to create a cloud provider resource should not block the creation of other instances of that same type of resource.

We also need to consider the allowed parallelism for managing a single resource instance.  For example, if a long operation is running in a controller for a specific resource instance, and the CRD for that instance is updated, should the controller process that update at the same time? should it block until the first update is done?  All controllers should have a level triggered (as opposed to edge triggered) design, but how should new resource events be handled when an existing event is already being processed?

This is also very related to locking, resiliency and idempotence.

**Comment by negz** [comment]
I thiiiink we support this. The only place it's really come in as a concern has been some of the Azure controllers that don't easily let you discover ongoing long running operations. I'm going to CC @muvaf and optimistically resolve this issue.
