### ISSUE TITLE
Add support for Database resource 

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#402]
### Overview
Currently, crossplane provides support for Database Instance resources across 3 cloud providers:
- AWS: RDS (mysql & PostgreSQL)
- Azure: MySQLServer  & PostresqlServer
- GCP - Cloudsql (mysql & postgresql)

While some applications perform the initial database create (which requires a privileged user account), it is widespread for consuming applications to expect an existing database and existing user with grants to this database.

By adding support to Database as a resource, we can provision a database on a database instance, and pass it for consuming application.

**Comment by negz** [comment]
Do our existing cloud providers provide API calls to create new databases, or will Crossplane need to use SQL clients to do so?

**Comment by negz** [comment]
Closing as a dupe of https://github.com/crossplaneio/crossplane/issues/29.
