### ISSUE TITLE
Update Tests cases names to CamelStyle in TableDrivenTest

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#412]
Currently, we use mixed styling when comes down to Test case names in TableDriveTests: https://github.com/golang/go/wiki/TableDrivenTests.

As @negz pointed out in https://github.com/crossplaneio/crossplane/pull/408#discussion_r277411144, we should converge on CamelCase.

**Comment by HashedDan** [comment]
Will have PR up for this shortly!
