### ISSUE TITLE
Remove forked CreateOrUpdate once running controller-runtime >=0.2.0

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#426]
https://github.com/crossplaneio/crossplane/pull/420#discussion_r279626247

Per the above comment https://github.com/crossplaneio/crossplane/pull/420 introduces a fork of the `CreateOrUpdate` function from an unreleased version of https://github.com/kubernetes-sigs/controller-runtime. We should remove our fork and return to mainline once we bump controller-runtime to 0.2.0 or above.

**Comment by negz** [comment]
Upgrading to controller-runtime 0.2.0 is tracked in #502.

**Comment by hasheddan** [comment]
Closing in favor of crossplaneio/crossplane-runtime#2

**Comment by hasheddan** [comment]
Closing in favor of crossplaneio/crossplane-runtime#2
