### ISSUE TITLE
Gitlab demo base64 encoding step incorrect

### ISSUE THREAD

**Issue by infinitecompute** [crossplaneio/crossplane#437]
* Bug Report
The base64 encoding of credentials are incorrect at:
https://github.com/crossplaneio/crossplane/blob/master/docs/gitlab/gitlab-gcp.md

1. The following instructions should use a ```cat``` command rather than ```echo```

```echo gcp-credentials.json | base64 -w0```
and
```echo gcp-credentials.json | base64 -w0```

2. Minor issue: It should used the term _encoded_ rather than _encrypted_ in "Generate BASE64ENCODED_GCS_PROVIDER_CREDS encrypted value"
3. It would be good to note that Mac does not have a ```base64 -w0``` flag and that ```base64``` is sufficient on Mac.

**Comment by thephred** [comment]
@infinitecompute @ichekrygin this seems fixed can it be closed?

**Comment by ichekrygin** [comment]
I believe so, @infinitecompute could you please confirm?

**Comment by negz** [comment]
This document is now defunct, so I'm going to resolve this.
