### ISSUE TITLE
Remove "selector" from Resource Claim specs

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#440]
https://github.com/crossplaneio/crossplane/blob/master/pkg/apis/compute/v1alpha1/types.go#L32

I think the selector was added by mistake. Currently, it is not used and I don't see any use cases for this selector at this level.

**Comment by negz** [comment]
I notice that at least RedisCluster and PostgresqlInstance also expose this field. I wasn't able to find any consumers of either, and the field name is vague enough that I can't tell what its intended purpose is. We should probably remove it from all Resource Claim types, or rename it to make it more obvious what it's for.
