### ISSUE TITLE
Consider breaking up pkg/util

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#448]
It's generally considered a mispattern in the Go world to create package names like `util`, or `common`. The preferred alternatives are typically one or more of:
* Breaking out functions into targeted packages with self documenting names like `strings`, `metadata`, etc.
* Tolerating the existence of duplicate instances of simple utility functions like `util.ToLowerRemoveSpaces` defined closer to where they're used.
* Avoiding such extremely simple utility functions altogether.

Sources:
* https://blog.golang.org/package-names (See "Bad package names")
* https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common
* https://rakyll.org/style-packages/

**Comment by hasheddan** [comment]
Closing in favor of crossplaneio/crossplane-runtime#1

**Comment by hasheddan** [comment]
Closing in favor of crossplaneio/crossplane-runtime#1
