### ISSUE TITLE
EKS YAML is missing some values

### ISSUE THREAD

**Issue by infinitecompute** [crossplaneio/crossplane#449]
**Is this a bug report or feature request?**
* Bug Report

https://github.com/crossplaneio/crossplane/blob/master/cluster/examples/kubernetes/aws/cluster.yaml

**Deviation from expected behavior:**
Maher hit some issues spinning up the EKS cluster. The YAML is missing some expected items.

The changes will be added here.

**Comment by negz** [comment]
I'm going to close this since the referenced example no longer exists. :)
