### ISSUE TITLE
Make code coverage requirements mandatory (again)?

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#480]
We've tweaked our code coverage requirements a few times after much debate, most recently landing on _requiring_ 80% coverage of new lines by requiring the Sonar check pass. I lobbied for making the Sonar check (and all checks) [required](https://help.github.com/en/articles/about-required-status-checks) because I feel strongly that optional checks provide a poor user experience for both maintainers and contributors. (I feel like I've written about that at length, but can't find where at the moment.)

We recently made the Sonar check optional in order to merge https://github.com/crossplaneio/crossplane/pull/476. I think this was a mistake; the packages touched by this PR had very low coverage and I believed Sonar required me to increase the _package_ coverage to 80% (from 30%). In retrospect I think it only wanted me to add a test for the function I refactored, which I think is in most cases a reasonable expectation.

While reading up on checks I noticed that it's possible to skip checks for a particular commit by adding `skip-checks: true` to the end of the commit message. I think this may be a good compromise because it allows the PR author to override a required check but requires them to indicate their intent to do so explicitly, and leaves an artifact of that decision in their commit message.

**Comment by negz** [comment]
Source for the `skip-checks` thing - https://help.github.com/en/articles/about-status-checks

I think this could be similar to the `// nolint` comments we add to override linter warnings. It allows us to bypass requirements where they don't make sense, but requires us to leave an artifact making our intent explicit, and communicates to reviewers that the PR author feels their PR is ready for review.

**Comment by ichekrygin** [comment]
~Couple~ Few questions:
- Does `skip-checks` allow to skip all checks wholesale?
- Can *any* contributor activate `skip-checks` functionality?
- Are we sure if this is a good approach?

**Comment by negz** [comment]
I think it does skip all checks, which is unfortunate. I'm not sure who is allowed to skip the checks - when @lukeweber tested it didn't skip checks at all, so this might not be a good path.

**Comment by ichekrygin** [comment]
I believe we should spend a day (or a week) or two to refactor and clean up the code so the lack of coverage is no longer an issue.

**Comment by negz** [comment]
I'd like to ensure Sonar and our linter (golangci-lint) are aligned before we make it mandatory again. Currently there are different heuristics, for example Sonar considers every TODO comment a 'code smell', calculates cyclomatic complexity differently.

It has been suggested that we could do away with golangci-lint and instead use https://www.sonarlint.org/, but I don't believe that supports Go at this time per https://github.com/SonarSource/sonarlint-intellij and https://github.com/SonarSource/sonarlint-visualstudio.
