### ISSUE TITLE
Caching of helm chart index prevents the most recent builds from being installed

### ISSUE THREAD

**Issue by infinitecompute** [crossplaneio/crossplane#484]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
We are serving a stale cache version of the master index.yaml.  It is not a problem with the local cache, but with a cache-control header.  See this thread for some hints on the problem.
https://github.com/helm/helm/issues/2453

**Expected behavior:**
https://charts.crossplane.io/master/index.yaml has much more recent builds listed in it: 0.0.0-628.02f0c23

**How to reproduce it (minimal and precise):**
When you curl, you will see that the most recent version is 0.0.0-615.5885d89
```curl -v --silent https://charts.crossplane.io/master/index.yaml 2>&1 | less```

https://github.com/helm/helm/issues/2453

**Comment by bassam** [comment]
https://github.com/upbound/build/pull/60 should solve this problem
