### ISSUE TITLE
Make status fields for cluster name consistent across EKS and GKE

### ISSUE THREAD

**Issue by infinitecompute** [crossplaneio/crossplane#487]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
For EKS and GKE, we have to pull the cluster name from two different status fields.  

kubectl get gkecluster [GKE_CLUSTER_REF] -n crossplane-system -o jsonpath='{.status.clusterName}'

kubectl get ekscluster [EKS_CLUSTER_REF] -n crossplane-system -o jsonpath='{.status.resourceName}'

**What is use case behind this feature:**
Consistency of the model

**Comment by ichekrygin** [comment]
Duplicate of #243
