### ISSUE TITLE
Resource claims can have failed and ready conditioned status simultaneously

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#495]
We've observed that resource claims can have the `Failed` and `Ready` conditioned statuses simultaneously. For example:
 
```
    - LastTransitionTime: "2019-05-20T22:26:59Z"
      Message: ""
      Reason: ""
      Status: "True"
      Type: Ready
    - LastTransitionTime: "2019-05-20T22:29:00Z"
      Message: 'cannot update instance crossplane-system/redis-e4a01610-7b4d-11e9-9bb0-42010a8a0094:
        Operation cannot be fulfilled on cloudmemorystoreinstances.cache.gcp.crossplane.io
        "redis-e4a01610-7b4d-11e9-9bb0-42010a8a0094": the object has been modified;
        please apply your changes to the latest version and try again'
      Reason: Failed to set resource binding status
      Status: "True"
      Type: Failed
```

I believe this is because we don't unset conditions when we set failed in https://github.com/crossplaneio/crossplane/blob/3ee2da/pkg/controller/core/resource_controller.go#L257

**Comment by ichekrygin** [comment]
Not sure if this is relevant in this case, however, the resource can have multiple conditions ready.
In this case, it appears resource became READY at 22:26, followed by any possible error which activated FAILED at 22:29. 

Just because FAILED condition is activated does not mean that resource is not ready.

**Comment by ichekrygin** [comment]
@negz please confirm and let's update or resolve this issue.

**Comment by negz** [comment]
> Just because FAILED condition is activated does not mean that resource is not ready.

We should change this. It does not make sense given the meanings of the words "ready" and "failed" for something to be both ready and failed.

It seems like this could be a phrasing issue. I believe that "ready" only ever reflects the state of the resource, while "failed" represents _either_ the state of the resource, or the state of an operation upon the resource. Often at the moment we'll set the status to "failed" because we encounter a problem such as an error while reconciling the resource, which could be temporary. In this case it would make more sense for the condition to be named "Error", "ReconcileFailed" or similar - "Failed" reads as it the resource has failed, which implies it's no longer ready.

I raised this issue after myself, @thephred, and @lukeweber were all confused as to how something could be ready and failed at the same time while debugging the Gitlab Controller, which I think is evidence that this is quite unintuitive.

**Comment by thephred** [comment]
Yes, I think the main thing is we need to distinguish between total failure that is terminal and temporary failures that will be retried/resolved.

**Comment by negz** [comment]
The more I think about this, the more I suspect we'd be better served by two (maybe three) conditioned statues; `Ready` (or `Available`), `Synced`, and (maybe) `Deleting`.

To recap, today we have the following:
```go
const (
	// Pending means that the resource create request has been received and is waiting
        // to be fulfilled.
	Pending ConditionType = "Pending"

	// Creating means that the resource create request has been accepted and the
        // resource is in the process of being created.
	Creating ConditionType = "Creating"

	// Deleting means that the resource is in the process of being deleted.
	Deleting ConditionType = "Deleting"

	// Failed means that the resource is in a failure state, for example it failed to
        // be created.
	Failed ConditionType = "Failed"

	// Ready means that the resource creation has been successful and the resource
        // is ready to accept requests and perform operations.
	Ready ConditionType = "Ready"
)

// Condition contains details for the current condition of this pod.
type Condition struct {
	Type               ConditionType
	Status             corev1.ConditionStatus
	LastTransitionTime metav1.Time
	Reason             string
	Message            string
}

type ConditionStatus string

// These are valid condition statuses. "ConditionTrue" means a resource is in the condition.
// "ConditionFalse" means a resource is not in the condition. "ConditionUnknown" means kubernetes
// can't decide if a resource is in the condition or not. In the future, we could add other
// intermediate conditions, e.g. ConditionDegraded.
const (
	ConditionTrue    ConditionStatus = "True"
	ConditionFalse   ConditionStatus = "False"
	ConditionUnknown ConditionStatus = "Unknown"
)
```

Note that each condition has two states, and some context, so the opposite of `Ready=ConditionTrue` is not `Failed=ConditionTrue`, but rather `Ready=ConditionFalse`. Given this, I would suggest:

`Ready`[1] maintains its current meaning - i.e.:
  * `ConditionTrue`: We expect the resource to be online and available to handle work.
  * `ConditionFalse`: We expect the resource to be offline or otherwise unable to handle work.

`Synced` (or `InSync`) means:
* `ConditionTrue`: We're confident we synced our desired with actual state on the most recent reconcile.
* `ConditionFalse`: We know we did not sync our desired with actual state on the most recent reconcile.

`Synced` would effectively replace `Failed`. If we encountered an error creating, reading, updating, or deleting a resource we would set `Synced=ConditionFalse`, and `Ready=ConditionUnknown` where appropriate. The fact that are not in sync due to an error would be represented by the reason and message; i.e. the `Reason` would be `Error` and the message would be `error.Error()`.

I'm on the fence about whether we really need `Deleting`. I think we could communicate that we're deleting a resource using only the `Ready` ConditionedStatus. i.e. When we delete an object we set `Ready=ConditionUnknown`, and `Reason=Deleting`

**Comment by negz** [comment]
Note that in my above proposal `Creating` would be replaced with `Ready=ConditionFalse`, `Reason=Creating`.

**Comment by ichekrygin** [comment]
I like this change. Good analysis and great suggestion!

**Comment by negz** [comment]
Thanks @ichekrygin! I started experimenting with an implementation of this pattern on the flight home from Kubecon. I'll submit a draft PR for the changes to `ConditionedStatus` so we can make sure we're on the same page before I undertake the task of refactoring the various Crossplane controllers.
