### ISSUE TITLE
Support "BYO bare metal" clusters

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#497]
**Is this a bug report or feature request?** Feature Request

**What should the feature do:** Crossplane users with existing bare metal clusters that are not managed by Crossplane would like to be able to deploy workloads to said clusters. It may be possible to support this by manually creating a `KubernetesCluster` resource and its associated connection secret, representing the bare metal cluster. We may need to ensure our controllers don't attempt to act on these resources - perhaps by adding a `metal` "provisioner" (as opposed to EKSCluster, GKECluster, AKSCluster, etc).

**What is use case behind this feature:** One or two folks asked for this at Kubecon EU 2019. One use case I recall was using Crossplane in a lab environment to coordinate testing containerised distributed systems across many clusters.

**Comment by jbw976** [comment]
I think this scenario of "BYO / bring your own" existing Kubernetes cluster may also have value beyond just bare metal.  Existing cloud managed clusters (GKE) may also be useful to import into Crossplane so that workloads can be scheduled to them.

**Comment by negz** [comment]
Relates to (possibly a dupe of?) #409.

**Comment by jbw976** [comment]
ah, i thought we had an issue covering this already, i couldn't find it though! I'm going to clean this up so we are tracking in only one place.

**Comment by jbw976** [comment]
Closing as a dupe of #409

**Comment by hasheddan** [comment]
Reopening this issue because I believed the BYO Kubernetes cluster scenario is somewhat isolated from the general importing of resources if we follow @negz design outline in [this comment](https://github.com/crossplaneio/crossplane/pull/841#discussion_r329227306).

Adding a Kubernetes `Provider` type would allow for usage of any Kubernetes cluster that a client could connect to.

**Comment by negz** [comment]
Crosslinking to https://github.com/crossplaneio/crossplane/pull/1101.

**Comment by negz** [comment]
I believe we now support this thanks to the `KubernetesTarget` work. :)
