### ISSUE TITLE
Support binding claims to existing resources?

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#517]
This issue is half feature request, half speculation.

Much of Crossplane's design is inspired by that of Kubernetes's `PersistentVolume` support. Both designs manage concrete 'external' resources - a `PersistentVolume` or a managed resource such as an `RDSInstance`. Both designs support provisioning the external resources on demand using parameters set in a 'class' when a 'claim' is created.

One notable difference is that a `PersistentVolumeClaim` can be satisfied by an existing but unbound `PersistentVolume`, whereas creating a Crossplane resource claim will always provision a brand new external resource. I suspect this is due to another key difference in the designs - it's not (practically) possible to consume a `PersistentVolume` directly - the `PersistentVolume` must be bound to a `PersistentVolumeClaim` before it can be consumed by a `Pod`. This has the nice property that an unbound `PersistentVolume` can be presumed to be available for binding to a new `PersistentVolumeClaim`.

Conversely, there's not currently any way for a Crossplane claim (or user) to distinguish whether a resource is in use or available. Resources write out their connection secrets (i.e. URL, username, password, etc) at create time, at which point something may or may not start consuming them.

Is the ability to claim an existing resource a desirable property for Crossplane? The main benefit I can think of is that it would allow operators to pay the time cost of provisioning resources up front so that developers may bind and consume them almost instantaneously.

**Comment by negz** [comment]
If we did want to support binding claims to existing resources one (flawed) option is to wait until a resource is bound before we expose its connection details.

Many resources require us to pass in our desired credentials at creation time and provide no way to discover them after the fact, so we'll always need to store credentials either before or at resource creation time. We could however avoid exposing connection URI details (hostnames, ports, etc) in the managed resource's secret and status, and instead expose them only as part of the resource claim.

Of course this won't work for all resources, including buckets, that can generally be addressed by a name we must pass in at creation time and that do not require credentials to consume.

**Comment by negz** [comment]
CC @bassam - this relates to our discussion last Friday afternoon around whether it should be possible to consume a managed resource directly without first making a resource claim.

**Comment by hasheddan** [comment]
Just wanted to add in here that things like Resource Groups actually do allow you to "bind" to an existing group due to the fact that they call a `CreateOrUpdate` API method. Other resources would have to have this functionality built into Crossplane though.

**Comment by negz** [comment]
> Things like Resource Groups actually do allow you to "bind" to an existing group

@hasheddan  it sounds like you might be thinking about binding a Crossplane managed resource (i.e. the Kubernetes resource) to an existing managed resource living somewhere in your cloud. i.e. You have an RDS instance running somewhere and want to retroactively associate that with a Crossplane `RDSInstance`.

I'm thinking of a slightly different case; binding a Crossplane resource claim to an existing Crossplane managed resource, i.e. You have a Crossplane `RDSInstance` and want to create a `PostgreSQLInstance` resource claim of that instance. Today our resource claim controller would provision a brand new `RDSInstance` even if there was already a compatible one sitting around unused.

**Comment by hasheddan** [comment]
@negz thanks for clarifying! This could be an interesting feature for separation of concern in an organization. I am thinking of a situation where an operator may be responsible not only for defining the class, but also creating the Crossplane resource, and then a developer could just bind to that existing resource.

**Comment by negz** [comment]
I realised today that we do already support all of the functionality I proposed in this issue. The resource claim controller skips provisioning a resource if a claim has a resource reference set, and you can tell a resource is claimed when it has a claim reference set.

I think it's still worth considering requiring a resource claim in order to consume a resource; I'll open a separate issue for that.

**Comment by jbw976** [comment]
One aspect of this issue that I thought it was covering was a "bring your own" scenario, e.g. so that a user could import some of their existing clusters into Crossplane so that workloads could be scheduled to them.

Existing Kubernetes clusters have the strongest case for being imported into Crossplane, that scenario may not make sense for other types of resources.

We cover this a bit from the bare metal perspective in #497.  That issue may be good to track importing any type of existing k8s cluster into Crossplane for scheduling workloads to.

**Comment by negz** [comment]
> One aspect of this issue that I thought it was covering was a "bring your own" scenario, e.g. so that a user could import some of their existing clusters into Crossplane so that workloads could be scheduled to them.

Yeah, I think there's two "layers" to this problem. The first being "importing" a cloud managed resource into Crossplane. In this scenario the managed resource exists in GCP, AWS, etc but is not modeled at all in Crossplane. I imagine part of the import process would be creating a concrete Crossplane managed resource (e.g. a `CloudSQLInstance`) to represent the imported managed resource.

The second layer, which I wrote this issue for, is about binding an abstract resource claim to an existing Crossplane-managed-resource. So in this second scenario a `CloudSQLInstance` already exists, and we want to bind a `PostgreSQLInstance` claim to said existing instance rather than creating a new one.

I think these two concepts were mixed up here due to the overloaded term "resource", which can mean "a thing that exists in the cloud", "a Crossplane custom resource representing a thing that exists in the cloud" or "something you store in a Kubernetes API server" depending on the context. :(

**Comment by hasheddan** [comment]
The ability to "import" existing infrastructure would be an incredibly powerful feature. There is a lot of effort around this type of functionality for various IaC tools, but even cloud providers themselves can have trouble translating account resources to their own IaC tools (i.e. [CloudFormer](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-using-cloudformer.html))
