### ISSUE TITLE
Require explicit connection secret references

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#518]
Currently both Crossplane resources and resource claims create connection secrets - a Kubernetes `Secret` that stores details required to consume a managed resource such as connection URI, username, password, etc.

There's very little consistency in the implementations. Most resources allow the user to specify a secret name in `.spec` but will generate a secret name if said name is omitted. This generated name is typically just the resource's name. Some resources record the generated name by updating `.spec`, while others record the generated name by updating `.status`.

All resource claims write their secret name to `.status.credentialsSecret`. Most claims simply name their secrets after themselves, but some support fields like `.connectionSecretOverride` to specify an explicit name.

I propose we do away with all this inconsistency and complication, and _require_ both resources and claims to include a `corev1.LocalObjectReference` at `.spec.writeConnectionSecret`. This avoids any surprise or ambiguity for the user about where connection secrets will be written, and simplifies the logic of our applications.

**Comment by negz** [comment]
Relates to #70, #119, #451, #489, and #450.

...and kind of duplicates #168.

**Comment by lukeweber** [comment]
Seems like a very reasonable option to simplify things.

Does a required object reference fail to create if the underlying object doesn’t exist?

What would happen in the event of a conflict on the secret name? I think generating the secret name has the advantage that you could assume that there is no conflict, kind of similar to deployments creating unique pods. 

We really needed the static name override specifically to realize Wordpress demo, but I’m still unsure if this is the most useful or safe consumption model as compared to unique secrets that wouldn’t collide.

**Comment by negz** [comment]
> Does a required object reference fail to create if the underlying object doesn’t exist?
No, nothing tests whether the referenced object actually exists. It will happily create pointing to nothing.

> What would happen in the event of a conflict on the secret name?
The same thing that (almost certainly) all controllers do today; the two resources trying to use the same secret will race to update it resulting in constant churn. We (mostly?) set owner references when we create secrets, but I haven't seen any examples of us checking for an owner reference before updating an existing secret. We should probably use a controller reference instead, check we own stuff before touching it per #450.

I'd like the idea of randomly generated secret names as much or more than this proposal if it weren't for the fact that we almost certainly can't get away with them and would still need to allow for overrides, especially for resource bindings in which consumers will often need to know exactly where and how their connection details will be and look ahead of time in order to reference them from other resources.

**Comment by negz** [comment]
The randomly generated secret name pattern does have symmetry with the token secrets generated by Kubernetes service accounts, but they enjoy special handling in which Pods dereference the secret name via the service account `.secrets` array.
