### ISSUE TITLE
Examples are out of date, inconsistent, and undocumented

### ISSUE THREAD

**Issue by displague** [crossplaneio/crossplane#519]
The examples in https://github.com/crossplaneio/crossplane/tree/master/cluster/examples are falling out of date and need revisiting:

* documentation is out of date (references to files that have been moved or removed)
* example variables are not consistent with each other between examples
* examples are not indexed or defined any where
* Some examples have hard coded project ids with no clear direction that these should be replaced 
* Some `gcloud` commands are missing (for example, linking a billing account to a new project)

These improvements may have some bearing on #367

**Comment by hasheddan** [comment]
Happy to help out here @displague !

**Comment by suskin** [comment]
I've just noticed that we have multiple folders with `wordpress` examples in the examples folder; is that intended? It seems a bit confusing. There are some examples in `wordpress`, and some in `workloads`.

**Comment by jbw976** [comment]
This will be covered by the #625 epic, all our examples and guides should be good for the 0.3 release from the issues covered in that epic.
