### ISSUE TITLE
Update docs for AWS Wordpress examples to use KubernetesApplication workloads

### ISSUE THREAD

**Issue by displague** [crossplaneio/crossplane#523]
The Wordpress workloads docs for [AWS](https://github.com/crossplaneio/crossplane/blob/master/docs/workloads/aws/wordpress-aws.md) currently follow the compute examples: https://github.com/crossplaneio/crossplane/tree/master/cluster/examples/compute

These documents are out of date:
* They refer to files that do not exist (they point to the examples/workloads directory instead of the examples/compute directory).
* They should be revised to follow the newer KubernetesApplication workload pattern

Relates to #519, #520

**Comment by hasheddan** [comment]
@displague saw that you addressed the GCP docs in #520, I would be happy to take care of AWS and Azure, but don't want to step on toes if you're already working on it :)

**Comment by displague** [comment]
Thanks, @hasheddan! 

Let's see how the review of #520 goes before jumping into this one.  The WP example is changing from documenting the old workflow process to the newer kubernetesapplication proceess.

Filenames, namespaces, entity names, and general documentation should ultimately be consistent between examples but I don't think that will be ironed out until 520 is merged.

**Comment by hasheddan** [comment]
Sounds good!

**Comment by displague** [comment]
I'm going to rephrase this for AWS updating only and clone the task for Azure.  I'm going to take on the AWS side to get myself bootstrapped with that provider.
