### ISSUE TITLE
ref counting for StackInstall to Stack

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#526]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** When multiple `StackInstall` all point to the same underlying `Stack`, we should do the following:
* only install the underlying `Stack` once
* only remove the underlying `Stack` once all `StackInstalls` that reference it have been removed

**What is use case behind this feature:** It is possible that multiple `StackInstalls` could all request the same underlying `Stack`, so we should handle this scenario cleanly.

**Comment by negz** [comment]
🤔 Were we calling `StackInstall` `ExtensionRequest` at some point?

**Comment by jbw976** [comment]
This will be tracked by the scenario solved by #1051
