### ISSUE TITLE
Update docs for Azure Wordpress examples to use KubernetesApplication workloads

### ISSUE THREAD

**Issue by displague** [crossplaneio/crossplane#538]
The Wordpress workloads docs for [Azure](https://github.com/crossplaneio/crossplane/blob/master/docs/workloads/azure/wordpress-azure.md) currently follow the compute examples: https://github.com/crossplaneio/crossplane/tree/master/cluster/examples/compute

These documents are out of date:

They refer to files that do not exist (they point to the examples/workloads directory instead of the examples/compute directory).
They should be revised to follow the newer KubernetesApplication workload pattern

Relates to #519, #520

**Comment by ngoduykhanh** [comment]
Hi, 
Is the docs for those examples being updated? Will there any changes except the file path? I tried to create the aks cluster with master branch of crossplane but it nerver created.

**Comment by displague** [comment]
@ngoduykhanh The v0.3 release will include updates to change the Wordpress example from the legacy compute workloads to the "complex" KubernetesApplication workload format.  These changes have been merged into the master branch for GCP and AWS.

I haven't gone through this process myself on Azure, yet, but I did work on the documentation and yaml changes for the GCP and AWS. These pull requests should help to describe the necessary changes.
* GCP (merged in master): https://github.com/crossplaneio/crossplane/pull/520
* AWS (open): https://github.com/crossplaneio/crossplane/pull/546

In short, there are three relevant `yaml` files.

* `provider.yaml` This file is expected to be different between providers.  The documentation for configuring the [Azure provider](https://github.com/crossplaneio/crossplane/blob/master/docs/cloud-providers/azure/azure-provider.md) should still be relevant and accurate when applied to the existing [Azure Wordpress Workload documentation](https://github.com/crossplaneio/crossplane/blob/e311b8cefa7c937e2b43c4b499ce61a63d7e227f/docs/workloads/azure/wordpress-azure.md#administrator-tasks).
https://github.com/crossplaneio/crossplane/blob/e311b8cefa7c937e2b43c4b499ce61a63d7e227f/cluster/examples/compute/wordpress-azure/provider.yaml
* `cluster.yaml` The cluster.yaml is generally similar, the GCP version does not specify the `provider`, so it can be used for reference in an Azure deployment: https://github.com/displague/crossplane/blob/e6cdbb4a25125a4081fa65bf0fd6aea8702ca15d/cluster/examples/workloads/kubernetes/wordpress-gcp/cluster.yaml
* `app.yaml` This file should not require any changes between providers! https://github.com/crossplaneio/crossplane/blob/e311b8cefa7c937e2b43c4b499ce61a63d7e227f/cluster/examples/workloads/kubernetes/wordpress-gcp/app.yaml

Aside from the incorrect filenames in the Azure Wordpress documentation, be careful with the commands that detect the status of the deployments.  Adapt these commands from the updated GCP documentation. https://github.com/crossplaneio/crossplane/blob/master/docs/workloads/gcp/wordpress-gcp.md#application-developer-tasks

**Comment by jbw976** [comment]
Closing this in favor of #650, which is part of the v0.3 Azure epic.
