### ISSUE TITLE
Package/Resource UI configuration metadata

### ISSUE THREAD

**Issue by rathpc** [crossplaneio/crossplane#544]
**Problem:**
Currently, if you are generating a CRD via a UI you have to hard code the specific UI configuration fields for a resource.

**Proposal:**
Adding a UI configuration file to the initial package file that will be associated to the initial spec and also allow for extending the validation requirements for given fields.

This will allow someone to drive the unique configuration fields displayed in the UI from their initial package file and thus no longer require any sort of hard coded UI elements on the frontend.

**Comment by displague** [comment]
The design is covered, but this was reopened to address the implementation.

**Comment by jbw976** [comment]
Fixed in #706
