### ISSUE TITLE
Produce a one-pager design for Crossplane's resource reclaim policy.

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#550]
Crossplane's claim to resource relationship is modeled upon, but not identical to, Kubernetes' persistent volume claim to persistent volume relationship. Both patterns leverage a "reclaim policy" setting on the concrete resource (i.e. the Crossplane resource, and the Kubernetes persistent volume). These settings work slightly differently across implementations.

In Kubernetes a persistent volume's reclaim policy determines whether the volume is deleted when its bound volume claim is deleted. Note that "deleting the volume" in this context means both the Kubernetes `PersistentVolume` resource representing the volume, and the actual volume, are deleted.

In Crossplane the delete options provided when deleting a resource claim determine whether its bound resource is deleted when the claim is deleted, because the resource claim is a Kubernetes owner reference of the resource. The resource's reclaim policy determines whether the actual cloud resource is deleted when the Kubernetes resource that represents it is deleted.

We should determine whether the current Crossplane implementation is appropriate, whether we want to more closely mimic the persistent volume pattern, or whether we should do something else completely. This seems like a design decision well scoped to a one-pager.

This issue was originally raised as a bug. I've maintained the body of the original issue below for reference.

---
### What happened?
Deleting a Crossplane managed resource from the Kubernetes API server (i.e. deleting an `CloudSQLInstance`, `ReplicationGroup`, etc) does not necessarily delete the managed resource from the cloud provider; instead it decides whether to delete the managed resource based on its `ReclaimPolicy`. Per [this search](https://github.com/search?l=&p=4&q=ReclaimPolicy+repo%3Acrossplaneio%2Fcrossplane+extension%3Ago+path%3A%2Fpkg%2Fcontroller&ref=advsearch&type=Code&utf8=%E2%9C%93), most resources exhibit this behaviour.

Based on a conversation with @bassam today, I believe this behaviour to be a misinterpretation of the intent of the `.spec.reclaimPolicy`, which is intended to communicate whether the resource's Kubernetes CR (i.e. the `RDSInstance`) should be deleted along with its claim (i.e. the `PostgreSQLInstance`) , not whether the actual RDS instance in AWS should or should not be deleted when the `RDSInstance` CR is deleted.

I believe this design was inspired by the `.spec.persistentVolumeReclaimPolicy` [field](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#persistentvolume-v1-core) of the `PersistentVolume` kind, which is described as:

> What happens to a persistent volume when released from its claim.

i.e. Deleting the `PersistentVolume` resource _always_ deletes its associated volume in the cloud provider; the reclaim policy defines whether the `PersistentVolume` resource (and thus the actual cloud volume) should be deleted when its `PersistentVolumeClaim` is deleted.

### How can we reproduce it?
Create a Crossplane managed resource of a kind that appears in [this search](https://github.com/search?l=&p=4&q=ReclaimPolicy+repo%3Acrossplaneio%2Fcrossplane+extension%3Ago+path%3A%2Fpkg%2Fcontroller&ref=advsearch&type=Code&utf8=%E2%9C%93) with `.spec.ReclaimPolicy` set to `Retain`. Once the resource has created, delete it from the API server. The managed resource it created in the cloud will still exist.

### What environment did it happen in?
Crossplane version: Current master, aka b6c3976

**Comment by negz** [comment]
To be explicit, I think that a managed resource CR's `.spec.reclaimPolicy` should determine whether said CR is deleted when its claim is deleted. I believe that deleting a managed resource CR should always delete its associated cloud resource.

**Comment by displague** [comment]
> I believe that deleting a managed resource CR should always delete its associated cloud resource.

I can go along with that so long as there is some `persistentVolumeReclaimPolicy` like mechanism in place to override that behavior.  When allocating existing cloud resources by name to kubernetes resources, having a `kubectl delete` destroy that cloud resource is unexpected behavior for users.

https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/#why-change-reclaim-policy-of-a-persistentvolume

--- 

#### StorageClass

> *reclaimPolicy* Dynamically provisioned PersistentVolumes of this storage class are created with this reclaimPolicy. Defaults to Delete.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#storageclass-v1-storage-k8s-io

#### PersistentVolumeSpec

> *persistentVolumeReclaimPolicy* What happens to a persistent volume when released from its claim. Valid options are Retain (default for manually created PersistentVolumes), Delete (default for dynamically provisioned PersistentVolumes), and Recycle (deprecated). Recycle must be supported by the volume plugin underlying this PersistentVolume. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#reclaiming

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#persistentvolumespec-v1-core

**Comment by negz** [comment]
@displague This topic feels difficult to discuss in writing due to how overloaded the term 'resource' is.

The [first link you shared](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/#why-change-reclaim-policy-of-a-persistentvolume) appears to document that PVs and PVCs exhibit the behaviour I am suggesting our claims and resources should exhibit, not the behaviour they exhibit today. Put otherwise, I believe that link is stating that the reclaim policy specified in the `PersistentVolume` spec defines what happens to that `PersistentVolume` (Kubernetes) resource when the `PersistentVolumeClaim` is deleted, not what happens to the (cloud) volume when the `PersistentVolume` is deleted.

I just tested this in practice to confirm the volume behaviour:

1. I created a GCP volume via the web console
1. I created a Kubernetes PV explicitly referencing said existing volume with `persistentVolumeReclaimPolicy` `Delete`
1. I created a Kubernetes PVC explicitly referencing said PV
1. I deleted said Kubernetes PVC 
1. Both the Kubernetes PV and the GCP persistent volume were deleted

Then:
1. I created a GCP volume via the web console
1. I created a Kubernetes PV explicitly referencing said existing volume with `persistentVolumeReclaimPolicy` `Retain`
1. I created a Kubernetes PVC explicitly referencing said PV
1. I deleted said Kubernetes PVC 
1. Both the Kubernetes PV and the GCP persistent volume still exist

Interestingly when I create a GCP volume via the web console, create a Kubernetes PV explicitly referencing said existing volume, then delete said PV without ever binding it the GCP volume is never deleted regardless of whether I set the reclaim policy to `Delete` or `Retain`.

**Comment by negz** [comment]
> When allocating existing cloud resources by name to kubernetes resources, having a kubectl delete destroy that cloud resource is unexpected behavior for users.

We don't currently support "importing" existing cloud resources to Crossplane management (tracked in #409).

I'm not sure I agree that it would be surprising to users if `kubectl` deleting the Kubernetes resource that represents a cloud resource deleted that resource. Creating a Kubernetes resource via `kubectl` would (typically) create a corresponding cloud resource, and updating the Kubernetes resource via `kubectl` would update the corresponding cloud resource, so it seems reasonable that deleting the Kubernetes resource would delete the cloud resource in the same way that pod containers aren't left around when you delete the pod that manages them.

I do agree with the principle though that if we allow users to import existing cloud resources into Crossplane management we should also allow them to orphan those resources from Crossplane management somehow.

I worry that having a "claim level" reclaim policy _and_ a "manage resource level" reclaim policy in which they former specifies what happens to the `RDSInstance` resource when the `PostgreSQLInstance` claim is deleted, and the latter specifies what happens to the actual RDS instance when the `RDSInstance` is deleted could be confusing for users to mentally model. That said, no better solution comes to mind.

**Comment by negz** [comment]
I've noticed that deleting a Crossplane resource claim seems to delete its corresponding (Kubernetes) managed resource (regardless of said resource's reclaim policy). It seems this is happening due to our (mis?)use of owner references.

Currently each of our resource claim controllers have a series of handlers that use the resource claim and its class to produce a Kubernetes resource representing a cloud resource. e.g. The `PostgreSQLInstance` controller uses these handlers to produce an `RDSInstance` resource. When it does so it sets the `PostgreSQLInstance` as an owner reference of the produced `RDSInstance`.

Crossplane (Kubernetes) resources are created in the namespace of their resource class, not the namespace of their resource claim for historical reasons documented in #92, so it's common for resources to be created in a different namespace from their resource claim. Per https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#OwnerReference owner references are not supposed to work across namespaces:
>  An owning object must be in the same namespace as the dependent, or be cluster-scoped, so there is no namespace field.

You can see here that we're setting an owner reference to an object in a different namespace:

```
$ kubectl -n crossplane-system get bucket.storage.gcp.crossplane.io gcs-b5e5d144-989c-11e9-89bd-080027055211 -o json|jq .metadata.ownerReferences
[
  {
    "apiVersion": "storage.crossplane.io/v1alpha1",
    "kind": "bucket",
    "name": "demo-gcp-bucket",
    "uid": "b5e5d144-989c-11e9-89bd-080027055211"
  }
]

$ kubectl -n crossplane-system get bucket demo-gcp-bucket
Error from server (NotFound): buckets.storage.crossplane.io "demo-gcp-bucket" not found

$ kubectl -n default get bucket demo-gcp-bucket
NAME              STATUS   CLASS                 PREDEFINED-ACL   LOCAL-PERMISSION   AGE
demo-gcp-bucket   Bound    standard-gcp-bucket                                       8m
```

It appears though that the Kubernetes garbage collector still honors this supposedly invalid reference, presumably because it includes the owner's UID:

```
$ kubectl -n crossplane-system get bucket.storage.gcp.crossplane.io
NAME                                       STORAGE_CLASS    LOCATION   CLASS                 RECLAIM_POLICY   AGE
gcs-b5e5d144-989c-11e9-89bd-080027055211   MULTI_REGIONAL   US         standard-gcp-bucket   Delete           11m

$ kubectl -n default delete bucket demo-gcp-bucket
bucket.storage.crossplane.io "demo-gcp-bucket" deleted

$ kubectl -n crossplane-system get bucket.storage.gcp.crossplane.io
No resources found.

$ kubectl apply -f cluster/examples/storage/gcp/resource-claim.yaml 
bucket.storage.crossplane.io/demo-gcp-bucket created

$ kubectl -n crossplane-system get bucket.storage.gcp.crossplane.io
NAME                                       STORAGE_CLASS    LOCATION   CLASS                 RECLAIM_POLICY   AGE
gcs-76b8be52-989e-11e9-89bd-080027055211   MULTI_REGIONAL   US         standard-gcp-bucket   Delete           13s

$ kubectl -n default delete bucket demo-gcp-bucket --cascade=false
bucket.storage.crossplane.io "demo-gcp-bucket" deleted

$ kubectl -n crossplane-system get bucket.storage.gcp.crossplane.io
NAME                                       STORAGE_CLASS    LOCATION   CLASS                 RECLAIM_POLICY   AGE
gcs-76b8be52-989e-11e9-89bd-080027055211   MULTI_REGIONAL   US         standard-gcp-bucket   Delete           52s
```

The `--cascade` option corresponds to the 'Orphan' [delete `PropagationPolicy`](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#DeleteOptions). So in summary today in Crossplane:

* The Kubernetes delete propagation policy determines whether a (Kubernetes) resource is deleted when its resource claim is deleted. This is true regardless of binding status, because nothing ever clears out the owner reference.
* The (Kubernetes) resource reclaim policy determines whether the (cloud) resource is deleted when the (Kubernetes) resource is deleted.

**Comment by ichekrygin** [comment]
I just re-read this issue 3rd time and still confused what is the problem :)

**Comment by ichekrygin** [comment]
> I've noticed that deleting a Crossplane resource claim seems to delete its corresponding (Kubernetes) managed resource (regardless of said resource's reclaim policy). 

IIRC Crossplain resource claims `MySQLInstance` or `KubernetesCluster` etc. do not provide `ReclaimPolicy` definition. 

They (Claims) do have a Parent-Child relationship with the `Concrete Resources` (CloudSQLInstance, RDSInstance, etc) via Owner Reference, thus deleting `Claim` will trigger the deletion of the `Concrete Resource`.

**Comment by ichekrygin** [comment]
> Create a Crossplane managed resource of a kind that appears in this search with .spec.ReclaimPolicy set to Retain. Once the resource has created, delete it from the API server. The managed resource it created in the cloud will still exist.

I think It could be helpful to put an example CRD instead of the search link.

**Comment by negz** [comment]
@ichekrygin I raised this issue after a discussion with @bassam today in which (if I understood him correctly) he indicated that the `ReclaimPolicy` is _intended_ to configure, for example, whether the `GKECluster` resource  a `KubernetesCluster` resource is bound to is deleted.

So the intention, if I understand it correctly, is that if the `GKECluster` has `ReclaimPolicy: Delete`, then deleting its bound `KubernetesCluster` claim should delete the `GKECluster`. If the `GKECluster` has `ReclaimPolicy: Retain` then deleting its bound `KubernetesCluster` claim should _not_ delete the `GKECluster`. This is how `PersistentVolume` reclaim policies work - they specify what to do with a `PersistentVolume` (not the actual underlying volume) when their `PersistentVolumeClaim`  is deleted.

As you point out, this does not match our actual implementation. Today the fact that the `KubernetesCluster` is an owner reference of the `GKECluster` dictates whether deleting the `KubernetesCluster` also deletes its `GKECluster`. The `ReclaimPolicy` instead determines whether the actual GKE cluster is deleted from GCP when the `KubernetesCluster` is created.

Obviously this all works fine functionally - you can use delete options to specify whether the `GKECluster` gets deleted along with its `KubernetesCluster` and you can use `ReclaimPolicy` to specify whether the actual GKE cluster gets deleted along with its `GKECluster`.

**Comment by negz** [comment]
It's also worth pointing out that while the parent -> child relationship between resource and claim seems to work in practice, it goes against the owner reference spec, which states that owner references should not cross namespaces.

**Comment by negz** [comment]
Putting this in a more "user story" fashion, my understanding is that the original intent behind our `ReclaimPolicy` setting was that cluster operators could create a bunch of `RDSInstance` resources with `ReclaimPolicy: Retain`. Then a developer could come along and bind to one of those instances using a `PostgreSQLInstance` claim. One day when the developer was done using their `PostgreSQLInstance` they could delete it, at which point the cluster operator can see the `RDSInstance`, still modeled in the API server, still managed by Crossplane, but now unbound.

**Comment by ichekrygin** [comment]
@negz I think this could be a misunderstanding of the semantics.

Let's forget about the `Claim` (`KubernetesCluser`) objects for a second and focus only on the `Concrete Resource` (`GKECluster`) objects. The most (if not all) properties of the `GKECluster` are there to "govern" CRUD of the actual cloud resource, i.e. `GKECluster`->`GCP GKE Cluster`:
```yaml
  providerRef:
    name: gcp-provider
  connectionSecretRef:
    name: gke
  clusterVersion: 1.10.9-gke.0
  machineType: n1-standard-1
  numNodes: 1
  zone: us-central1-a
  reclaimPolicy: Delete # or Retain
```
To emphasize this point, the property `reclaimPolicy` is dedicated to managing deletion of the actual `GKE cluster` when/if `GKECluster` Kubernetes object is deleted, just like `zone` is dedicated to creation  of the actual `GKE cluster` when/if `GKECluster` Kubernetes object is created, i.e. the `GKECluster object` -> `Actual GKE Cluster` relationship scope. 
Thus:
> So the intention, if I understand it correctly, is that if the GKECluster has ReclaimPolicy: Delete, then deleting its bound KubernetesCluster claim should delete the GKECluster

No, it is not. GKECluster has ReclaimPolicy: Delete means, what to do when the user deletes GKECluster and not any other object (parent or otherwise).

There is no (or at least there was no intent to) define Deletion Policy that affects `Claim` (`KubernetesCluster`) -> `Concrete Resoure` (`GKECluster`) relationship, and current it is governed solely by the `OwnerReference`. Thus, deletion of the `Claim` should trigger deletion of the `Concrete Resource`, if it doesn't - it is a bug!

If we do want more nuanced "Deletion" handling between `Claim`->`Concrete Resource`, then we should replace `OwnerReference` with `ReclaimProperty`, but such should be defined at the `Claim` level, i.e. `KubernetesCluster` type should have a `reclaimProperty` as a part of its spec dedicated how to handle clean up of the `GKECluster` child object. TBH, I am not sure if we want this though.

**Comment by bassam** [comment]
> GKECluster has ReclaimPolicy: Delete means, what to do when the user deletes GKECluster and not any other object (parent or otherwise).

That's not how `persistentVolumeReclaimPolicy` works which we modeled this after, and not the intention I personally had for this either. The behavior of `reclaimPolicy` should be tied to operations that happen on binding and releasing a `claim`, and not the `resource` itself.

I don't believe the `bind` relationship between claim->resource can be modeled as an `ownerReference` (parent/child). The semantics are different.

If we wanted to control the behavior between `Kubernetes resource` and `external resource`, maybe we should add `externalResourcePolicy`. Calling it `reclaimPolicy` ties it to the claim :-)

**Comment by ichekrygin** [comment]
> That's not how persistentVolumeReclaimPolicy works which we modeled this after,

The `Concrete Resource` modeling was inspired by `PVClaim`, in reality, it is something else altogether. In my understanding: `ResourceClaim` ~= `PVClaim`, whereas `ConcreteResource` is somewhere in between. 

I am not saying: "This is how it should work", I am saying this is how it is modeled currently.

**Comment by ichekrygin** [comment]
If we want a closer model, then we should move "ReclaimPolicy" property from the `ConcreteResource`, and have it in the context of `ResourceClass` + `ResourceClaim`.

With that said, we did not spend any significant effort on defining `Static Provisioning`, which is the integral part of this model.

**Comment by negz** [comment]
We discussed this during Upbound's Crossplane standup today, and I believe all the Upboundlings on this issue are on the same page in that we recognise:

* The current Crossplane `ReclaimPolicy` implementation works.
* The current Crossplane `ReclaimPolicy` works differently from the `PersistentVolume` `ReclaimPolicy` implementation.
* This is in part because the Crossplane claim -> Crossplane resource relationship works differently from the `PersistentVolume` -> `PersistentVolumeClaim` implementation.
* It is potentially confusing that the two implementations are seductively similar, use the same "reclaim policy" term, but work differently.

We think the best path forward is for someone to write a one pager capturing and achieving community buy-in for how we want this to work in Crossplane. I'm going to update this issue to reflect that.

**Comment by hasheddan** [comment]
I can take this!

**Comment by jbw976** [comment]
Is there a follow-up issue that will track the implementation/behavior change described in https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-resource-reclaim-policy.md#goals?

@hasheddan @negz
