### ISSUE TITLE
Getting started should be more streamlined for the admin

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#560]
### What problem are you facing?
Currently, there is a lot of manual and clunky work that the admin needs to do to get started doing useful things with Crossplane after initially deploying the control plane:

* import cloud provider credentials
* define resource classes for each flavor of service/resource/cloud
* figure out regions, networking, security, etc.

Jason Plum from GitLab (@WarheadsSE) did a good job of summarizing the difficulty with the experience of getting started with Crossplane in https://gitlab.com/charts/gitlab/issues/1155:

> At this point in time, there is a high cost of initial setup for the Crossplane deployment capabilities themselves. The installation of Crossplane itself is simple thanks to their chart, however many items need to be pre-configured by hand through direct creation of YAML & deployment via kubectl apply. I hope to see improvement on reducing efforts required in regards to networking & security configuration in the future, as this was a major stumbling block during testing.

### How could Crossplane help solve your problem?
I'm not sure of the specific solutions here, but we need an overall streamline of the experience that results in less manual operations, more prescriptive guidance, more intuitive steps, less knowledge ramp-up, fewer concepts to learn, etc.

**Comment by jbw976** [comment]
One potential idea here for resource classes is that a stack could contain a set of "recommended" resource classes for the services it depends on, a la recommended or minimum hardware requirements for an operating system.

It is doubtful that these recommended resource classes would be used as-is in production scenarios, but they could be a helpful start for people to kick the tires on a given app with minimal friction. They could also serve as starting points for an admin to tweak the resource classes further for their particular needs and environment.

**Comment by jbw976** [comment]
The goal of this issue to make the initial experience easier is related to #568

**Comment by displague** [comment]
Proposed in https://github.com/crossplaneio/crossplane/issues/568#issuecomment-509414208 is the idea of a Crossplane UI that is deployed with Crossplane.  

I don't know if this thought has legs, but I'll offer it up again here.

### Provider Configuring Web-UI

This UI would be `kubectl run` or deployed with Crossplane.  The service would then be accessed locally via [`kubectl proxy`](https://kubernetes.io/docs/tasks/access-kubernetes-api/http-proxy-access-api/) and would use OAuth2 and related web-services to guide a user through configuring the base `Provider` and `Secret` for Crossplane to interact with a given cloud.

### Example Helpers?

If additionally pre-provisioning steps are necessary for a specific example, or common deployment, the web UI may be able to guide or automate the provisioning of those features.

Ultimately, however, the goal would be for the infrastructure stack to provide support for provisioning all prerequisite resources.  Example Helpers would only be needed for resources that are out of reach based on the current capabilities of Crossplane.

**Comment by jbw976** [comment]
I think the streamlined experience offered by the minimal (easy) environment stacks go a long way to addressing this original complaint.  I'm going to close this now.

* https://github.com/crossplaneio/stack-minimal-gcp/
* https://github.com/crossplaneio/stack-minimal-aws/
* https://github.com/crossplaneio/stack-minimal-azure/
