### ISSUE TITLE
Exclude Add(manager.Manager) boilerplate from test coverage

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#562]
Crossplane controllers have a good chunk of the `controller-runtime` scaffolding code. 
Specifically: 
```go
func Add(mgr manager.Manager) error {
	r := &Reconciler{
		Client:  mgr.GetClient(),
		factory: &operationsFactory{mgr.GetClient()},
	}
...
```

`controller-runtime` does not provide (at the time of this issue) an interface for `Manager` structure, thus it is inconvenient to unit-test this section of code. 

The side effect of this "lack of unit-test" is lower than the expected code coverage, which in turn violates PR checks (SonarCloud).

One way to side-step around this issue is to put "scaffolding" `controller-runtime` code into a separate file and exclude that file from the coverage report. 

As an experiment `gcp.database` controller uses `add.go` file to define all `Add()` functions.

If this is something that we want to adopt, consider refactoring all controllers to follow a similar pattern.

**Comment by negz** [comment]
If we do decide testing the `Add()` functions is a worthwhile effort we may be able to define our own interface that is slightly smaller and more approachable than controller-runtime's `manager.Manager`.

That said, these functions are mostly boilerplate instantiations akin to a lengthy `NewFoo()` function, so I feel comfortable leaving them untested.

**Comment by negz** [comment]
I don't think this is a priority - I'm okay with a "real" coverage report, including the fact that some boilerplate code is not covered. Please reopen if anyone disagrees.
