### ISSUE TITLE
Introduce concept of Stacks and its initial design thinking 

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#571]
In the [2019-07-09 Community Meeting](https://docs.google.com/document/d/1q_sp2jLQsDEOX7Yug6TPOv7Fwrys6EwcF5Itxjkno7Y/edit#heading=h.q83jmi2f62wj), we discussed the concept of Crossplane "Stacks".

We should introduce this concept more formally with a 1-pager for its goals, design, experience, etc.  This will allow the community to understand and provide feedback on this direction.

A short summary of the discussion from the community meeting:

* Stacks takes the idea of “extensions” further
* Currently Crossplane can be extended with new functionality for new services, providers, applications, etc.
  * each extension is implemented with new CRDs and new controllers to manage them
  * required to write full fledged custom controllers which requires knowledge of golang, Kubernetes API, state management, etc.
* We should enable other options that have a lower barrier to entry
    * templates, metacontroller style function hooks, Domain Specific Language (DSL)
* The team will explore this effort to help grow the Crossplane community and ecosystem

What we've been calling "extensions" should probably be renamed to "stacks", for example the [extensions issue label](https://github.com/crossplaneio/crossplane/labels/extensions), the [extension manager design](https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-extensions.md), etc.

**Comment by displague** [comment]
When addressing the `Extension` to `Stacks` code changes, we may wish to rename the API to `stacks.crossplane.io` or similar, per @negz https://github.com/crossplaneio/crossplane/pull/573#discussion_r302299659

**Comment by jbw976** [comment]
This is completed in the [Stacks design doc](https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-stacks.md).
