### ISSUE TITLE
Implement a shared managed resource reconciler

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#584]
### What problem are you facing?
As a Crossplane maintainer I'd like to encourage and enable others to extend Crossplane by adding support for more managed resources. Each managed resource kind is handled by its own controller. These controllers are scaffolded by kubebuilder and the controller-runtime, but the implementation is otherwise unopinionated. A few generations of reconciler logic exist today in Crossplane. We've explored standardising on a single pattern and written a [design doc](https://github.com/crossplaneio/crossplane/blob/ad8653/design/design-doc-reconciler-patterns.md) to that effect.

### How could Crossplane help solve your problem?

The resource claim controllers were recently rewritten such that a single `Reconciler` with pluggable logic is used by all controllers. A similar pattern was followed to implement the default resource class reconciler. We've speculated that we might be able to follow a similar pattern for managed resources.

Most (all?) managed resource reconcilers follow a similar pattern; they lookup their provider, get its connection secret, create a client for their external resource API, then use that client to either create, delete, or sync the external resource. We may be able to achieve this using a single `Reconciler` with pluggable connect, create, delete, and sync logic. This scaffolding would provide an additional layer of standardisation and direction for Crossplane contributors seeking to write new managed resource controllers. If/when Crossplane is broken up into many controller manager binaries we may consider packaging such `Reconciler` scaffolds as a `crossplane-runtime` supplement to the `controller-runtime`.

**Comment by jbw976** [comment]
This was implemented in #603
