### ISSUE TITLE
GCP CloudSQL: Instance names must start with a letter

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#585]
### What happened?

When walking through the wordpress demo with GCP, I ran into an issue fulfilling a CloudSQL claim:

```
  status:
    conditions:
    - lastTransitionTime: "2019-07-17T00:40:44Z"
      message: 'googleapi: Error 400: Invalid request: instance name (82b2acd2-a82b-11e9-8c7f-025000000001).,
        invalid'
      reason: Encountered an error during managed resource reconciliation
      status: "False"
      type: Synced
```

### How can we reproduce it?

* Create a new CloudSQL claim; here's the excerpt from the wordpress demo:
```
$ kubectl apply -f cluster/examples/workloads/kubernetes/wordpress-gcp/app.yaml
```
* Check for a stuck claim; `$ kubectl -n crossplane-system get cloudsqlinstance -o yaml` can be used to list the details of cloudsqlinstances, and the output can be further filtered to look for a dead one. It should show up immediately.
* If there isn't a dead instance yet, try again until the UID happens to start with a non-letter.

### What environment did it happen in?
Crossplane version: `master`

### Thoughts

[Here is where it's defined](https://cloud.google.com/sql/docs/mysql/instance-settings) that instance names must start with letters. I chatted with @negz and @ichekrygin before filing this, and as part of fixing this issue, it'd be great to use a unified naming scheme for at least CloudSQL resources, and ideally all of them. Leading ideas included: use a common prefix per resource type, like `cloudsql-` for CloudSQL instances; or use the configured `metadata.name` of the claim.

**Comment by jbw976** [comment]
This is somewhat surprising, if all cloudsql instance names had to start with a letter, I'd expect for us to be running into this error 10/16 times (ratio of numbers to letters in hex values).  I've never personally hit this myself, have I just been lucky?

**Comment by suskin** [comment]
Potentially, but it also seems the behavior [changed recently to use UUIDs](https://github.com/crossplaneio/crossplane/pull/556/files#diff-b2f116d1d8ff16292384e5f6c9ea3059R245) instead of [prefixing the name with the Kind](https://github.com/crossplaneio/crossplane/pull/556/files#diff-acf4d7d8f425187334e67c237ea3be68L108). The other day when it came up, it sounded like @ichekrygin had more context.

**Comment by suskin** [comment]
I'm putting together a pull request to address this.
