### ISSUE TITLE
Update documentation with strongly typed resource classes

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#595]
Update existing documentation that has drifted due to strongly typed resource classes, and add section on defaulting using `Policies`.

Part of #613 

Related to #588 

### What seems to be the problem?

The implementation of strongly typed resource classes requires changes to the way that `ResourceClaims` reference `ResourceClasses` as detailed in #594. This is not yet reflected in existing documentation. In addition, there is not a section in the docs that describes resource class defaulting behavior or provides a walk-through.

### What could Crossplane do to help?

Portions of the Crossplane docs that use `ResourceClaims` should be updated to match the new pattern. Some of this work will be completed by updating examples that are referenced from the docs. In addition, a section of `Policies` and resource class defaulting should be added as a stand-alone concept. There may also be opportunity to incorporate defaulting into other existing deployment walk-throughs.

### What does it look like when we're done?
A user can:

* Use walk-throughs in the documentation to successfully provision resources.
* Use walk-throuhgs in the documentation to successfully provision resources that do not have an explicit class reference and utilize defaulting.
* Read the docs and understand how to apply defaulting policies to resources that are not explicitly walked-through in the docs in the examples.

### Todo
- [ ] Update existing documentation that uses the old pattern of class references in resource claims.
- [ ] Add a new section to documentation describing `Policies` and default class references.

**Comment by jbw976** [comment]
I think we can call this issue done after all the examples have been updated in #696.  The remaining work to update all the user guides is being tracked via the epic for each cloud provider, e.g., #615, #616, #617
