### ISSUE TITLE
Release pipeline

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#6]
part of #864 

The build pipeline described in #2 should also be able to release and publish artifacts such as docker images, helm charts, documentation, etc.  The Rook project has a good example of this.

* [Rook release readme](https://github.com/rook/rook/tree/master/build/release)
* [Rook Jenkinsfile release step](https://github.com/rook/rook/blob/master/Jenkinsfile#L106)

**Comment by bassam** [comment]
Here are the steps I did manually for the v0.1 release. First tag the release:

```
make tag VERSION=v0.1.0
git checkout release-0.1
```

Now publish:
```
build/run make -j4  publish BRANCH_NAME=release-0.1 AWS_ACCESS_KEY_ID="..." AWS_SECRET_ACCESS_KEY="..." GIT_API_TOKEN="..."
```

Then promote:
```
Build/run make -j4  promote BRANCH_NAME=release-0.1 VERSION=v0.1.0 CHANNEL=alpha AWS_ACCESS_KEY_ID="..." AWS_SECRET_ACCESS_KEY="..."
```

We need to get Jenkins doing this. For some reason it did NOT pickup the tag and resulting in the wrong release. I think its a  jenkins config to sync tags that we are missing.

**Comment by jbw976** [comment]
@Defilan we'd like to get a Crossplane v0.2 release out this week.  Please sync with me about the automation gaps and what it will take, thanks!

**Comment by jbw976** [comment]
Note that it may be OK to have some manual steps for v0.2, but having an understanding for a smooth release is important.

**Comment by jbw976** [comment]
The tag and promote Jenkinsfiles were removed from the `upbound/build` repo with this commit: https://github.com/upbound/build/commit/ab8c075886f671ec257918414053b1e805a73605.  There's not much context about why they were removed, perhaps because they are not easily generalized and therefore are a better fit for individual repos that are consuming the build repo as a submodule?

**Comment by jbw976** [comment]
We have decided that properly implementing and testing the automated Jenkinsfile and release pipelines has too much risk for the short timeline left for v0.2. @Defilan will work on this properly and at high quality for v0.3.

**Comment by jbw976** [comment]
@Defilan will you be able to work on this release pipeline for v0.3?

**Comment by jbw976** [comment]
We are committing to adding this release pipelines for v0.4 as part of #864.  This should cover not only the main Crossplane repo, but also the stacks that we are actively developing and maintaining, e.g. the cloud provider stacks.

**Comment by jbw976** [comment]
I have opened a series of PRs to add the same `tag` and `promote` pipelines to the stacks repos that have already merged into Crossplane master

* https://github.com/crossplaneio/stack-gcp/pull/67
* https://github.com/crossplaneio/stack-aws/pull/53
* https://github.com/crossplaneio/stack-azure/pull/47
* https://github.com/crossplaneio/stack-rook/pull/12

**Comment by jbw976** [comment]
Release pipelines for tagging and promoting have been added to main crossplane repo, stack-aws, stack-gcp, stack-azure, and stack-rook.  I believe this issue is now completed.
