### ISSUE TITLE
Stacks Manager: app vs. infra stacks, namespace isolation, annotation support

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#609]
Stack Manager enhancements that will allow both infrastructure and application stacks to be created by the community, installed with appropriate RBAC permissions and namespace isolation, and annotations for systems using stacks.

Part of the [0.3 release](https://github.com/crossplaneio/crossplane/blob/master/ROADMAP.md#v03---enable-partners-to-build-infra-stacks)

### Why? What problem are we solving with this epic?
The current implementation of the Stack Manager is fairly primitive and lacking some important features needed for wider adoption of Stacks by various partners.  This epic covers the addition of new features to the Stack Manager that will allow both infrastructure and application stacks to be created by the community, as well as potential UI experience to be built around installing and managing stacks.

### What does it look like when we're done?
All desired features have been included into the Stack Manager such that both infrastructure and application stacks can be built and installed into Crossplane.  UI can be described in Stack metadata and then generated for each CRD that a Stack installs into the control plane.

* Developers (partners) can build both infrastructure and application stacks
* Cloud admins can install infrastructure related stacks at the cluster (control plane) level
* App operators can install application related stacks at the namespace level
* CRD annotations can be embedded in a stack and applied to CRDs at install time by the Stacks Manager

### How could this be demonstrated?
1. Crossplane user reads the blog post describing this new functionality
1. Click through to the updated user guide
1. Try out the updated example(s)

Including:
 * steps to get a sample stack working with the updated stack manager
 * manually write stack yamls & controller Dockerfile?
   * app.yaml - what is this, so a new user browsing 0.3 roadmap understands what this is?
   * rbac.yaml - what is this?
   * ui.yaml - what is this?
 * add an infra stack and go into cluster names
 * add portable wordpress app stack #572 and have it go into a namespace
 * deploy wordpress instance from installed #572
 * TBD based on the design doc

### CLI/Dev UX in this timeframe?
TBD based on design doc
```
kubectl apply infra-stack.yaml
kubectl apply app-stack.yaml
```

### Related Issues
* Design doc #580
* Rename all remaining wording of 'Extension' to 'Stack' #668 
* Implement isolation model for app and infra stacks #663 
* Package standardization: consistent file on disk layout, etc. #507 
* Applying annotations at stack install time #544 
* Short blog post to blog.crossplane.io about this new functionality! #TBD

**Comment by prasek** [comment]
@jbw976 will #92 be closed with this as well?

**Comment by prasek** [comment]
also #89
