### ISSUE TITLE
TRACE-level logging

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#611]
This is somewhat related to #331 . I was working with crossplane and the wordpress gcp example locally, and was wanting more detail in the logs for debugging issues (such as the issue described in #597). But, the information to debug this type of issue seems like it's at an even more verbose level than `logging.Debug`, which is the only level we support now.

I feel it would make sense to create another logging level, `logging.Trace`, which could be used for extra-verbose debug statements. An example of a statement at `Trace` could be "syncing of the cache instance is done because it hasn't been created yet", and other messages about enter and exit conditions.

What do other folks think? Does this seem like a good idea? /cc @jbw976 @negz

**Comment by negz** [comment]
My current thinking is to avoid this, somewhat explained by the logging package doc in https://github.com/crossplaneio/crossplane-runtime/pull/108. I agree debug logging is important, but I think it should be an on or off thing - not at multiple levels. Please comment on that pull if you disagree!
