### ISSUE TITLE
Managed resources should be high fidelity

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#621]
### What problem are you facing?

As a cloud administrator I'd like Crossplane to support as many of the features of the managed resource kinds I work with as possible. For example if I'm creating a `CloudSQLInstance`, I want to be able to set any of the settings the CloudSQL instance API supports.

### How could Crossplane help solve your problem?

Crossplane could support "high-fidelity" managed resources, [per these examples](https://github.com/crossplaneio/crossplane/blob/49f3b4/design/one-pager-resource-connectivity-mvp.md#low-fidelity-managed-resources). A high fidelity managed resource is essentially a direct translation of the underlying cloud provider's API object to a Crossplane managed resource CRD, with all writable fields under `.spec`, and all read-only fields under `.status`.

Crossplane's `CloudSQLInstanceSpec`, for example, should be as close as reasonably possible to the fields exposed by the GCP [`DatabaseInstance`](https://godoc.org/google.golang.org/api/sqladmin/v1beta4#DatabaseInstance) excluding the "output only" fields (which are good candidates to expose in `CloudSQLInstanceStatus` instead). The value of one field may influence which other fields are writable. My opinion is that at the managed resource level we should faithfully expose all the knobs to the managed resource author and let them figure it out.

Consider how the CloudSQL SDK works; the author is expected to understand the API documentation and know that if they set `InstanceType: CLOUD_SQL_INSTANCE` then they should not set `MasterInstanceName`. My guess is that `MasterInstanceName` is simply ignored if `InstanceType: CLOUD_SQL_INSTANCE` is set, but for the sake of this example let's assume the API returns an error when a `DatabaseInstance` is submitted with `InstanceType: CLOUD_SQL_INSTANCE` and `MasterInstanceName: mycoolmaster`.

I propose that Crossplane, at the managed resource level, does nothing to stop the managed resource author writing this nonsensical managed resource, just as the CloudSQL Go SDK does nothing to prevent the author submitting this nonsensical `DatabaseInstance`. I propose that Crossplane faithfully translate the `CloudSQLInstanceSpec` into a `DatabaseInstance`, try create it, and return the inevitable error to the author by way of a `ReconcileError` `ConditionedStatus`.

This makes the mental model for managing Crossplane resources as close as possible to the mental model of using the underlying cloud provider API (which is typically well documented, and has Googlable error strings). It also keeps the path a little clearer for generating `Reconciler` code from a cloud provider API specification.

**Comment by negz** [comment]
I suspect could be a good first issue because we already translate Crossplane managed resource API definitions into the relevant cloud provider Go SDK API objects, which are typically close representations of the cloud provider's actual HTTP API. The work here would be to make our existing API definitions match said cloud provider Go SDK API objects more closely.

It very likely makes sense to address #602 at the same time as this issue.

**Comment by muvaf** [comment]
These two issues seemed duplicate to me https://github.com/crossplaneio/crossplane/issues/530

**Comment by muvaf** [comment]
@negz do you think we can close this issue since we are applying https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-managed-resource-api-design.md across the board now?

**Comment by negz** [comment]
I do! Thanks for scrubbing these old bugs @muvaf and @hasheddan.
