### ISSUE TITLE
External resource names should be configurable

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#624]
### What problem are you facing?

As a cloud administrator I would like control over the names of the external resources created by Crossplane. Crossplane does not currently offer much control or consistency in this area. For example at least the following are used to name external resources:

* A prefix plus the managed resource's `.metadata.UID`
* A prefix plus a hash of the managed resource's `.metadata.UID`
* The managed resource's `.spec.Name`
* The managed resource's `.metadata.Name`
* The managed resource's `.spec.NameFormat`, which is passed along with the managed resource's `.metadata.UID` to [`util.ConditionalStringFormat`](https://godoc.org/github.com/crossplaneio/crossplane/pkg/util#ConditionalStringFormat)

### How could Crossplane help solve your problem?

If Crossplane moves toward high fidelity managed resources per #621 it would make sense for any external resource that typically has the caller configure its name via an API Object field have a corresponding field under the managed resource's spec. For example in [the CloudSQL API](https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/instances#resource) the field is simply named `Name`, and thus `.spec.Name` is appropriate.  In the [CloudMemoryStore API](https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances/create) the field is named `InstanceId`, and thus `.spec.InstanceId` is appropriate.

One consideration is that managed resources are frequently dynamically provisioned to satisfy a resource claim, using a resource class. If the above `.spec.InstanceId` were simply read from a resource class we'd end up with two external resources attempting to use the same name. `ConditionalStringFormat` is one approach to address this.

I suggest that external resource names _always_ be static and explicitly specified as part of the managed resource `.spec`. In cases where managed resources are dynamically provisioned it should be the responsibility of the [`ManagedConfigurator`](https://godoc.org/github.com/crossplaneio/crossplane/pkg/resource#ManagedConfigurator) to set the managed resource's external resource name in a fashion that will avoid collisions.

**Comment by negz** [comment]
Relates to #211 and #458.

**Comment by suskin** [comment]
This ticket sounds like it is related to having a common API pattern for specifying resource names. In a past conversation, the idea came up of having a reusable mechanism for setting the name, or at least for generating a default name if nothing was in the resource. I want to make a note of that idea in this ticket, since they seem related, and there isn't a ticket (yet) tracking the concept of a reusable default naming mechanism.

**Comment by displague** [comment]
> I suggest that external resource names always be static and explicitly specified as part of the managed resource .spec

Names are often optional fields which are fulfilled by the providers' own name generation.
As a user of IaC tools, I'm often confused when confronted with multiple `name` and `label` fields, where it is not clear how the two fields will be distinguished, especially if that convention is not upheld between resources.

**Comment by displague** [comment]
Kubernetes `generateName` and Kustomize `namePrefix` and `nameSuffix` are prior art worth investigating.

https://github.com/eBay/Kubernetes/blob/master/docs/devel/api-conventions.md#idempotency
https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#nameprefix

Here's a little more on `generateName` (see the idempotency link first).
```
$ kubectl explain job.metadata.generateName
KIND:     Job
VERSION:  batch/v1

FIELD:    generateName <string>

DESCRIPTION:
     GenerateName is an optional prefix, used by the server, to generate a
     unique name ONLY IF the Name field has not been provided. If this field is
     used, the name returned to the client will be different than the name
     passed. This value will also be combined with a unique suffix. The provided
     value has the same validation rules as the Name field, and may be truncated
     by the length of the suffix required to make the value unique on the
     server. If this field is specified and the generated name exists, the
     server will NOT return a 409 - instead, it will either return 201 Created
     or 500 with Reason ServerTimeout indicating a unique name could not be
     found in the time allotted, and the client should retry (optionally after
     the time indicated in the Retry-After header). Applied only if Name is not
     specified. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#idempotency
```

**Comment by negz** [comment]
> Names are often optional fields which are fulfilled by the providers' own name generation.

We're seeing something like this for the AWS network types where the caller has no control over the resource names, which are randomly generated by the cloud provider.
