### ISSUE TITLE
Overall 0.3 docs

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#625]
Crossplane has made a ton of progress since 0.2, so the docs need to be updated to match. Enable users to rapidly understand Crossplane, get started, and find the information they're looking for.

Part of the [0.3 release](https://github.com/crossplaneio/crossplane/blob/master/ROADMAP.md#v03---enable-partners-to-build-infra-stacks)

### What seems to be the problem?
Crossplane has made a ton of progress since 0.2 and the common docs need to be updated to reflect the 0.3 enhancements, provide a better new user on-boarding experience, and make it easier for contributors to get started.

### What could Crossplane do to help?
Reflect v0.3 enhancements, provide a better on-boarding UX, make it easier to get started.

Our current thinking is that the documentation should be updated to reflect the changes. An example of changes which could be made would be:
* A glossary of terms is published and used consistently everywhere
* Crossplane docs have been curated and updated to reflect the 0.3 release
* README.md is updated to provide a great new user eval and on-boarding UX. User scenarios include:
  * evaluate if Crossplane will solve your problems in < 1 min
  * get started with Crossplane in < 5 minutes with real examples
  * easily find the infra stacks dev guide #610, to learn how to contribute controllers or whole infra stacks for unsupported clouds
* ROADMAP.md is updated to reflect 0.3, 0.4, and 0.5 releases through end of 2019
  * understand the current and future state of the project in < 5 minutes, including quality level of the functionality
* Summary (e.g. table) of infra stack capabilities, API version level, etc.

### What does it look like when we're done?
The user should be able to easily find things they're looking for, and shouldn't have to worry about sifting through content which is not relevant.

* Terms are defined, consistently used, and the definitions are easy to find
* The documentation reflects the 0.3 release
* Unnecessary content has been removed
* User scenarios (such as getting started) should be well-documented, easy to find, and brief, including:
  * Evaluating Crossplane for a user's use-case
  * Getting started with Crossplane
  * Evaluating and consuming infra stacks (including comparing infra stack capabilities and maturity)
  * Developing infra stacks
* Documentation of past, present, planned, and possible future directions can be found and understood in under 5 minutes
* Note: website updates handled in crossplaneio/crossplaneio.github.io#22

### How could this be demonstrated?

See the [complete v0.3 docs plan](https://docs.google.com/document/d/11SQHf1v_1iisgVqbGwdRnEOmpoAMpbiEglb_H664To4/edit?usp=sharing) for more detail
           
### Related Issues
* [ ]  v0.3 release notes <- crossplane/PendingReleaseNotes.md 

* #781 Update overall [crossplane.io documentation](https://crossplane.io/docs/master/), including:
   - #777 S0 [P1]: [Quick Start Guide](https://docs.google.com/document/d/1NtMEEzRqYCn9-H_pE75nGLb1DqOn7KqXLbEc01GjAUA/edit?usp=sharing): Static provisioning of managed DB
   - #778 S1 [P0]: [Services Guide](https://docs.google.com/document/d/1C_Z1Ic95NFHsXw_gWcM3IvdLVhcPNaOAVhbTb3BtcrA/edit?usp=sharing): Dynamic provisioning of managed DB on single k8s cluster 
   - #779 S3 [P0]: [Stacks Guide](https://docs.google.com/document/d/1jJncy5hZcarZU6w9YpqHeO_z1f1wx0pw9tDXS0tyUGE/edit): Deploy Portable Wordpress App Stack
   - S4 [P1]: Hello world: Build your own app stack in < 5 min: link to [crossplane-cli](https://github.com/crossplaneio/crossplane-cli)
   - #780 S5 [P1]: Cluster Guide - deploy a managed k8s cluster from kubectl
   - #610 S5 [P0]: [Infra Stack] Developer Guide

* #782 Curate, update, and test all Crossplane examples for v0.3: AWS, GCP, Azure

* #783 Update [crossplaneio/crossplane](https://github.com/crossplaneio/crossplane) repo docs

* #658 Update readme.md for stack-gcp, stack-aws, stack-azure

* Website updates handled in [crossplaneio/crossplaneio.github.io#22]

* #671 - v0.3 announcement blog post

* #763 Generate Crossplane (Custom Resource) API
   * core crossplane repo
   * stack-gcp
   * stack-aws
   * stack-azure

**Comment by hasheddan** [comment]
Linking relevant issues to this epic:
#588 #594 #595
