### ISSUE TITLE
Bring your own resource scenario

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#628]
### What problem are you facing?

I have a fleet of resources in my cloud account that I bought on a discount. Reserved EC2 instances on AWS could be an example. I'd like crossplane to use these resources and not dynamically provision new ones unless all of them are scheduled for use by crossplane.

### How could Crossplane help solve your problem?

Few options:
- Define a way to import my resources into crossplane.
One way could be that I create `Managed Resource` CRs that have cloud provider identifier. Crossplane can detect that the cloud provider identifier is given and it exists, well, make this ready in terms of provisioning.
- Define a resource class that enforces use of _existing cloud resources_. 
This makes _all_ existing resources in that account available for Crossplane to use instead of specifically importing them. Labeling on cloud provider level and specifying that label in ResourceClass could be an option.

For both cases one has to consider that whether we should allow crossplane to `delete` or `update` individual resources that were statically provisioned. I think the question here is that what level of granularity we want to have as option for the user to choose in terms of object manipulation operations. Is `mutable/immutable` enough? Or `update allowed,deletion not` kind of granularity?

**Comment by jbw976** [comment]
@muvaf this looks to me like a duplicate of #409, what do you think? If so, can you update that issue with any new thinking from your write-up here and then close this issue?

**Comment by muvaf** [comment]
Yes, I wasn't aware of that. Closing in favor of https://github.com/crossplaneio/crossplane-runtime/issues/22 (409 has been moved to 22)
