### ISSUE TITLE
Create a Stacks CLI design doc

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#641]
Related to #614 

### What seems to be the problem?

As part of working on #614, we're going to want some sort of design doc for the tool, so we can discuss it and try to identify design holes early.

### What could Crossplane do to help?

Research some options enough to create a design doc which can be used to focus discussion about the direction we want to go with the CLI. 

### What does this look like when it's done?

The design doc should contain things such as:
* Goals and experience
* Guiding principles
* High-level structure
* The operations and how they might be implemented
* Open questions

**Comment by suskin** [comment]
The document is in review still, but in the meantime I've been making progress on the prototype: https://github.com/suskin/crossplane-stack-cli/pull/1

**Comment by suskin** [comment]
I expect that it'll make sense to put the document into a pull request in the very near future, as first suggested by @prasek

**Comment by suskin** [comment]
I've put the design document into a pull request in #730 .

**Comment by jbw976** [comment]
Fixed with #730
