### ISSUE TITLE
Azure: Update API status table for infra stack capabilities, API version level, etc.

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#656]
Update the API status table following the completion of the `v1alpha2` Azure infrastructure stack.

Part of #617
Depends on #572, #647, #648, #649
### What seems to be the problem?

The Azure infrastructure stack API version should be updated to represent the new functionality and structure.

### What could Crossplane do to help?

Update the API Status and version in the [API status table](https://github.com/crossplaneio/crossplane#api-status).

### What does it look like when we're done?
A user can:

* Identify the current status and version of the Azure infrastructure stack by viewing the API status table.

### Todo
- [ ] Update API status table to match the state of the Azure infrastructure stack.

**Comment by negz** [comment]
This should be fixed by #806.

**Comment by jbw976** [comment]
Fixed by #806
