### ISSUE TITLE
Update readme.md for stack-gcp, stack-aws, stack-azure

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#658]
Part of #612

### What seems to be the problem?
As part of #612, we will be splitting out the cloud providers into their own repos and creating a stack for each of them.  The Crossplane community will be unfamiliar with this new concept and how to use it.

### What could Crossplane do to help?
  * basic install, uninstall, usage - e.g. in install.md
  * link to https://crossplane.io/docs/ instead of deploy.html
  * API status table for stack apiVersions
  * link to generated CRD docs

High quality documentation and getting started user guide are being provided in #781 and #625 that will be replacing https://crossplane.io/docs/v0.2/deploy.html with the portable wordpress app stack deploy guide. 

Additional stacks created by the community will not have documentation auto-included in the https://crossplane.io/docs/. It would help each stack stand on it's own if it included simple instructions to install, uninstall, and use the stack and link to the  https://crossplane.io/docs/ for getting started. 

One option is to add an install.md to each cloud provider stack repo that covers the basic the installation, uninstallation, and most basic usage of the stack as a pattern for other stacks to follow.

### What does it look like when we're done?
* Each cloud provider infra stack has published:
  * basic instructions to install and uninstall the stack, e.g. in an install.md linked from readme.md that include examples for install, uninstall, and most basic usage of the stack
  * should end up with a very simple flow here, a single short page of doc

### Todo
Update readme.md

add basic install, uninstall, and usage instructions (e.g. install.md)
- [ ] stack-gcp
- [ ] stack-aws
- [ ] stack-azure

replace link to deploy.html with https://crossplane.io/docs/ for getting started
- [x] stack-gcp
- [x] stack-aws
- [x] stack-azure

add API status table
- [ ] stack-gcp
- [ ] stack-aws
- [ ] stack-azure #656

link to autogenerated CRD docs for stack
- [ ] stack-gcp
- [ ] stack-aws
- [ ] stack-azure

**Comment by negz** [comment]
https://github.com/ahmetb/gen-crd-api-reference-docs/

We should consider using the above project to generate documentation from CRDs.

**Comment by jbw976** [comment]
This work is being tracked via the epic for each cloud provider, e.g., #615, #616, #617

**Comment by jbw976** [comment]
This issue actually still has more work to do that is independent of the cloud provider stacks.  We'll want to have some Stacks intro and usage documentation.

- what a stack is - stack introduction
- how do you build one and what components does it need
- how to publish
- how to consume and use

**Comment by negz** [comment]
#806 contains API status tables for all cloud providers. If we want to duplicate these in our README files you're welcome to copy and paste from that PR.

**Comment by suskin** [comment]
The readmes refer the reader over to the full crossplane docs for things like installation, so that may be good enough for now.

**Comment by jbw976** [comment]
The readme's have appropriate information and link to the docs for more help and the API status tables were included in v0.3.
