### ISSUE TITLE
Publish v0.3 announcement blog post

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#671]
Blog post for 0.3 milestone release theme, planning & backlog, to solicit community awareness & feedback.

Part of #625

### What seems to be the problem?
What's new and exciting in the v0.3 release?

### What could Crossplane do to help?
Announcement blog post. 

### What does it look like when we're done?
New blog post on blog.crossplane.io

### Todo
- [x] draft blog post
- [ ] review
- [ ] publish

**Comment by negz** [comment]
Pretty sure this one got done too, so removing from the board.
