### ISSUE TITLE
Wordpress sample stack end-to-end setup

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#674]
Related to #572 

### What seems to be the problem?

As part of #572, we want to set up a wordpress stack to use as a sample of using a controller in a stack. When we're setting that up, there will be some chunk of work which is some initial setup and configuration, and isn't related to the functionality.

### What could Crossplane do to help?

This is probably part of the user story tracked by #638, but for ease of work-tracking I am splitting the setup work into its own deliverable.

However, this could also be used to do some initial exploration and experimentation around what the stack development workflow might look like.

### What does this look like when it's done?

* We have a repo which has all the boilerplate done for developing a stack
* The stack repo should have solutions for everything needed for developing the stack:
  - Bundling
  - Publishing locally
  - Installing locally
  - Uninstalling locally
* The stack should have some minimal functionality which can be used to validate that everything works end-to-end. This could be something as simple as watching a custom resource type and printing something out when it's found

**Comment by jbw976** [comment]
Fixed in https://github.com/crossplaneio/sample-stack-wordpress/pull/2
