### ISSUE TITLE
Blog post on "classes of service": portable, non-portable, and default classes

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#689]
Part of #775

### What seems to be the problem?
Crossplane added a new model of support for "classes of service" with portable, non-portable, and default classes that enable new functionality and fundamentally change the way that all dynamic provisioning takes place. We want to make it clear how strongly typed resource classes are different from the generic `ResourceClass` pattern and provide our motivation for the shift.

### What could Crossplane do to help?
Give a detailed breakdown of how managed resources were being passed configuration details using the generic `ResourceClass` pattern, and how it differs with strongly typed resource classes. Explain how defaulting makes things easy and what improvements we're thinking about for the future. In addition, the changes in examples and docs should be pointed out and linked.

### What does it look like when we're done?
New blog post on blog.crossplane.io

### Todo
- [x] draft blog post
- [ ] review
- [ ] publish

**Comment by negz** [comment]
I'm going to suggest we don't do this given that by the time we get around to it they won't exist anymore - should be replaced by an 0.4 blog post about simple resource class selection.
