### ISSUE TITLE
Blog post on updated Crossplane Stacks functionality for new users

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#710]
### What seems to be the problem
Need a blog post on updated Crossplane Stacks functionality for new users.

Part of #609

### What does it look like when we're done
 * More accessible than the design doc, which is in a Crossplane-centric view
 * Broad strokes of configuration
 * Annotations not a headline topic
 * See a catalog of these stacks: GCP, AWS, Azure
 * Orient existing users to using infra stacks for GCP functionality, what's the experience?
 * Idea of the app stack, link to the WP stack in that situation
 * Q: is this the top-level blog post for stacks?
 * Goal for time to read: 5 min tops?

**Comment by negz** [comment]
Is this still something we want to do?

**Comment by jbw976** [comment]
I vote to close out these older blog post related issues and open new ones as needed for new topics.
