### ISSUE TITLE
Stacks CLI to build & publish a Stack

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#711]
Related to #614 

### What seems to be the problem?

As part of working on #614, I need to build & publish a Stack from source.

### What could Crossplane do to help?

Provide a CLI utility I can use to build a Stack.

### What does this look like when it's done?
* kubectl plugin command to build a Stack
* kubectl plugin command to publish a Stack
* docs & examples

**Comment by suskin** [comment]
I'm working on this in a separate repo, and have an initial set of changes: https://github.com/suskin/crossplane-stack-cli/pull/1

`publish` is the least tested of the commands so far, but I'm feeling pretty good about the `init`+ local `build` flow. I'll be creating a document to describe a quick start with the commands.

**Comment by suskin** [comment]
I've made good progress on this and have a quick start guide which gives an overview of the commands. It's in the [README of the personal repo](https://github.com/suskin/crossplane-stack-cli) that I'm currently doing this work in.

**Comment by suskin** [comment]
The code and initial documentation for `build` is checked into [crossplaneio/crossplane-cli](https://github.com/crossplaneio/crossplane-cli), but `publish` isn't quite polished enough yet to be considered done.
