### ISSUE TITLE
Stacks CLI command to init a new kubebuilder v2.0 Stack

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#712]
Related to #614 

### What seems to be the problem?

As part of working on #614, I need to init a scaffolding for a new kubebuilder v2.0 Stack.

### What could Crossplane do to help?

Provide a CLI utility I can use to init a Stack.

### What does this look like when it's done?
* kubectl plugin command to init a Stack
* docs & examples

**Comment by suskin** [comment]
I am working on this in a separate repo, and have an initial set of changes: https://github.com/suskin/crossplane-stack-cli/pull/1

**Comment by suskin** [comment]
I've made good progress on this and have a quick start guide which gives an overview of the commands. It's in the [README of the personal repo](https://github.com/suskin/crossplane-stack-cli) that I'm currently doing this work in.

**Comment by suskin** [comment]
The code and initial documentation for this is checked into [crossplaneio/crossplane-cli](https://github.com/crossplaneio/crossplane-cli), so I'm going to close this.

**Comment by suskin** [comment]
The code and initial documentation for this is checked into [crossplaneio/crossplane-cli](https://github.com/crossplaneio/crossplane-cli), so I'm going to close this.
