### ISSUE TITLE
User can install and use the Stacks CLI

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#713]
Related to #614 

### What seems to be the problem?

Need to understand how to get started with the new Stacks CLI, e.g. install and use.

### What could Crossplane do to help?

Docs to get started with using the CLI. Pre-reqs. Commands.

Easy to get the Stacks CLI on my system.

### What does this look like when it's done?
* Getting started docs for install and use of Stacks CLI
* Repo and distribution channel setup

**Comment by suskin** [comment]
The code and initial documentation for this is checked into [crossplaneio/crossplane-cli](https://github.com/crossplaneio/crossplane-cli), so I'm going to close this. If we do some release-cutting as part of the milestone, let's track that in a separate issue.
