### ISSUE TITLE
Stacks CLI example: hello world!

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#714]
Related to #614 

### What seems to be the problem?

Examples are a great way to get started, so an easy hello world stack would help a lot.

### What could Crossplane do to help?

Create a hello world stack that I can create using the new Stacks CLI init, build, publish commands.

### What does this look like when it's done?
* Docs on how to create the hello world example.
* Tutorial can be done in < 5 min
* Example repo time permitting

**Comment by suskin** [comment]
The first version of this is done and documented in https://github.com/suskin/crossplane-stack-cli . I'm going to consider this as satisfying the scope of this ticket. I may open other tickets to track the work to:
* Use the `install` and `uninstall` commands
* Move the code into a crossplane org repo
* Have a tested external publish flow
* Create a repo with the fully-rendered hello world

**Comment by suskin** [comment]
The documentation for this is checked into [crossplaneio/crossplane-cli](https://github.com/crossplaneio/crossplane-cli), so I'm going to close this.
