### ISSUE TITLE
Separation of levels between Cloud Spec and Crossplane Spec in CR

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#728]
### What problem are you facing?

Right now, an example CR looks like this:
```
apiVersion: compute.gcp.crossplane.io/v1alpha1
kind: Network
metadata:
  creationTimestamp: "2019-08-28T17:39:24Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 2
  name: my-legacy-network
  namespace: crossplane-system
  resourceVersion: "29218"
  selfLink: /apis/compute.gcp.crossplane.io/v1alpha1/namespaces/crossplane-system/networks/my-legacy-network
  uid: 55de6569-0085-43d2-8931-4a0da76cb682
spec:
  name: monus-legacy-network-res
  providerRef:
    name: monus-gcp
    namespace: crossplane-system
  reclaimPolicy: Delete
  routingConfig:
    routingMode: REGIONAL
  writeConnectionSecretToRef: {}
status:
  IPv4Range: 10.240.0.0/16
  conditions:
  - lastTransitionTime: "2019-08-29T05:55:16Z"
    reason: Successfully reconciled managed resource
    status: "True"
    type: Synced
  creationTimestamp: "2019-08-28T10:45:27.445-07:00"
  gatewayIPv4: 10.240.0.1
  id: 75666386684937048
  kind: compute#network
  name: monus-legacy-network-res
  routingConfig:
    routingMode: REGIONAL
  selfLink: https://www.googleapis.com/compute/v1/projects/crossplane-playground/global/networks/monus-legacy-network-res
```
As you see the cloud provider specifications and Crossplane fields are on the same level both in `Spec` and `Status`. As you can see, the fields that are retrieved from cloud provider have collision possibility since they are not that special, like `name` or `creationTimestamp` or more in the future. I'd like to know that what fields are cloud provider info what fields belong to Crossplane itself.

### How could Crossplane help solve your problem?
I believe that we should have a field named `specForProvider` in `Spec` and `statusAtProvider` in `Status`. It'd look like the following:
```
apiVersion: compute.gcp.crossplane.io/v1alpha1
kind: Network
metadata:
  creationTimestamp: "2019-08-28T17:39:24Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 2
  name: my-legacy-network
  namespace: crossplane-system
  resourceVersion: "29218"
  selfLink: /apis/compute.gcp.crossplane.io/v1alpha1/namespaces/crossplane-system/networks/my-legacy-network
  uid: 55de6569-0085-43d2-8931-4a0da76cb682
spec:
  providerRef:
    name: monus-gcp
    namespace: crossplane-system
  reclaimPolicy: Delete
  writeConnectionSecretToRef: {}
  specForProvider:
    name: monus-legacy-network-res
    routingConfig:
      routingMode: REGIONAL
status:
  conditions:
  - lastTransitionTime: "2019-08-29T05:55:16Z"
    reason: Successfully reconciled managed resource
    status: "True"
    type: Synced
  statusAtProvider:
    IPv4Range: 10.240.0.0/16
    creationTimestamp: "2019-08-28T10:45:27.445-07:00"
    gatewayIPv4: 10.240.0.1
    id: 75666386684937048
    kind: compute#network
    name: monus-legacy-network-res
    routingConfig:
      routingMode: REGIONAL
    selfLink: https://www.googleapis.com/compute/v1/projects/crossplane-playground/global/networks/monus-legacy-network-res
```

We'd guarantee that field names match the corresponding cloud's Go SDK field names so that the translation is easy. A couple benefits of this pattern:
- Prevents name collision between fields. As you see above, cloud Network object has fields called `name`, `creationTimestamp` which are same with what we have in our `metadata`. While it's not that easy to confuse them, I do see scenarios where Crossplane-owned spec field names collide with what provider's struct has. It doesn't have to be exact match but even close similarity could be confusing for users.
- Easier consumption since you know that under `specForProvider` or `statusAtProvider`, the fields are known to be _exactly_ all the information we are able to get from cloud provider.

**Comment by negz** [comment]
@muvaf I feel like I've seen these field names (`specForProvider` and `statusAtProvider`) in some other tool. Am I just imagining things?

**Comment by muvaf** [comment]
Just Googled but couldn't find any reference. Deja vu maybe? :)

**Comment by soorena776** [comment]
@muvaf 
FYI, I have been using `TypeExternalStatus`
https://github.com/crossplaneio/stack-aws/blob/master/aws/apis/identity/v1alpha2/iamrole_types.go#L63

**Comment by muvaf** [comment]
@soorena776 If I understood correctly, you're still embedding the struct `TypeExternalStatus` though. The issue is more about not embedding that type, and having a name for it in all resources.

IAMRoleExternalStatus `json:",inline"`  

would become 

statusAtProvider IAMRoleExternalStatus `json:"statusAtProvider,omitempty"`

**Comment by hasheddan** [comment]
@muvaf is this now closed by your `forProvider` pattern? :)

**Comment by muvaf** [comment]
@hasheddan yes! We can close this now as #840 is getting implemented across the board.
