### ISSUE TITLE
Investigate Using Pointers for Optional Fields

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#741]
Currently, there are many *optional* fields in Crossplane CRD definitions (denoted with `omitempty`) that are not of pointer type. This can lead to issues to unintended behavior when these fields are omitted from a `yaml` definition. This is particularly hairy with type `bool`. If a `bool` field is excluded in a CRD instance, it is assigned its zero value (`false`). However, this is weak defaulting behavior because any controllers are unable to determine if the value was omitted or explicitly set to `false`.

We have avoided issues with this by implementing `ToBoolPtr()` functions in the provider client libraries ([AWS](https://github.com/crossplaneio/crossplane/blob/7e22a8d5b83cf08b1c27d214a67d7025aa841efb/pkg/clients/aws/aws.go#L146), [Azure](https://github.com/crossplaneio/crossplane/blob/7e22a8d5b83cf08b1c27d214a67d7025aa841efb/pkg/clients/azure/azure.go#L170)). It would be nice to follow [Kubernetes best-practices](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required) and instead make these fields `*bool`, then deal with `nil` values appropriately. This would allow for consistent behavior across the Crossplane API.

*Note: `bool` is used as an example, but this should be implemented for all field types that are `omitempty`.*

### Related
Related Issues: #530 #602 #621 

### Detail
List of `bool` / `omitempty` field:
```
./gcp/apis/storage/v1alpha1/types.go:	IsLocked bool `json:"isLocked,omitempty"`
./gcp/apis/storage/v1alpha1/types.go:	Enabled bool `json:"enabled,omitempty"`
./gcp/apis/storage/v1alpha1/types.go:	DefaultEventBasedHold bool `json:"defaultEventBasedHold,omitempty"`
./gcp/apis/storage/v1alpha1/types.go:	RequesterPays bool `json:"requesterPays,omitempty"`
./gcp/apis/storage/v1alpha1/types.go:	VersioningEnabled bool `json:"versioningEnabled,omitempty"`
./aws/apis/cache/v1alpha1/replication_group_types.go:	AtRestEncryptionEnabled bool `json:"atRestEncryptionEnabled,omitempty"`
./aws/apis/cache/v1alpha1/replication_group_types.go:	AuthEnabled bool `json:"authEnabled,omitempty"`
./aws/apis/cache/v1alpha1/replication_group_types.go:	AutomaticFailoverEnabled bool `json:"automaticFailoverEnabled,omitempty"`
./aws/apis/cache/v1alpha1/replication_group_types.go:	TransitEncryptionEnabled bool `json:"transitEncryptionEnabled,omitempty"`
./aws/apis/cache/v1alpha1/replication_group_types.go:	ClusterEnabled bool `json:"clusterEnabled,omitempty"`
./azure/apis/storage/v1alpha1/account.go:	UseSubDomainName bool `json:"useSubDomainName,omitempty"`
./azure/apis/storage/v1alpha1/account.go:	Blob bool `json:"blob,omitempty"`
./azure/apis/storage/v1alpha1/account.go:	File bool `json:"file,omitempty"`
./azure/apis/storage/v1alpha1/account.go:	Table bool `json:"table,omitempty"`
./azure/apis/storage/v1alpha1/account.go:	Queue bool `json:"queue,omitempty"`
./azure/apis/storage/v1alpha1/account.go:	EnableHTTPSTrafficOnly bool `json:"supportsHttpsTrafficOnly,omitempty"`
./azure/apis/cache/v1alpha1/redis_types.go:	EnableNonSSLPort bool `json:"enableNonSslPort,omitempty"`
./azure/apis/compute/v1alpha1/types.go:	DisableRBAC bool `json:"disableRBAC,omitempty"` //--disable-rbac
./azure/apis/database/v1alpha1/sql_types.go:	GeoRedundantBackup  bool `json:"geoRedundantBackup,omitempty"`
```
Command used to obtain list:
```grep -r --exclude-dir=vendor " bool \`json" .```

**Comment by hasheddan** [comment]
cc// @muvaf @negz

**Comment by negz** [comment]
Per https://github.com/crossplaneio/crossplane/blob/1fb67d0526b79cefb9949cbfc9c103cdd228c3fd/design/one-pager-managed-resource-api-design.md we've adopted this practice for v1beta1 managed resources. I'd consider this to be considered and recommended.
