### ISSUE TITLE
Add new "overview" field in both app.yaml and resource.yaml

### ISSUE THREAD

**Issue by rathpc** [crossplaneio/crossplane#745]
### What problem are you facing?
Currently there is only a `description` field as a part of **app.yaml** and **resource.yaml**.
 
### How could Crossplane help solve your problem?
It would be useful to have an additional field called `overview` as a part of **app.yaml** and **resource.yaml** that you could use to add in a summary/descriptive text area about the stack or resource respectively. This would be different from the description which is specifically tailored as a delivery system for the README of the stack or resource. Instead this could be used as more of a marketing, human readable intro describing what this stack or resource is.

**Comment by lukeweber** [comment]
I don't see overview as being needed as it currently stands because description can simply be a rich markdown of sections and anything needed to describe the application.

**Comment by jbw976** [comment]
Let's sync up @lukeweber @rathpc on what is needed to be added to the Stacks package format spec in v0.3.

**Comment by rathpc** [comment]
I will throw something on our calendars @jbw976

**Comment by rathpc** [comment]
@jbw976 As per our recent meeting, here are the takeaways:

We will be modifying the spec to reflect the following:

### Within `app.yaml`

- The **description** field will be renamed **readme**.
- A new field, **overview** will be created which should accept plain text only.
- A new field **overviewShort** will be created which should accept plain text only.

### Within `resource.yaml`

- The **description** field will be renamed **readme**.
- A new field, **overview** will be created which should accept plain text only.
- A new field **overviewShort** will be created which should accept plain text only.

**Comment by displague** [comment]
@rathpc `group.yaml` follows the same conventions and should be updated too.

**Comment by displague** [comment]
There may be an advantage to using a `README.md` in the leaf directories.  We may need to use `README-kind.md` (or similar) to disambiguate between crd files being described.  This would also incur ambiguity between group and resource README files.

The advantage would be that stack creators do not have to work on markdown within yaml indentations.  They can use featureful markdown editors.

**Comment by rathpc** [comment]
I think that could make sense to me, and I have no problem with a file versus a field as long as it ends up being parsed into an annotation the same way a field in the YAML would have.
