### ISSUE TITLE
Establish pattern for browsing generated resources and their parent child relationships

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#752]
### What problem are you facing?
Controllers in Crossplane, for example the controller installed by a stack, are likely to create multiple resources as part of their normal operations.  It would be a useful experience for the user to be able to view and browse all of these resources. But how can they find them?

Take for example the [WordPress stack](https://github.com/crossplaneio/sample-stack-wordpress/).  In response to the user creating a `WordPressInstance`, the wordpress controller will create multiple resources such as `MySqlInstance` and `KubernetesCluster` claims, `KubernetesApplication` and associated `KubernetesApplicationResources`, etc.

How can the user easily find, browse, and view all of these resources that the stack's controller generated, as well as the hierarchical parent child relationships between them?

### How could Crossplane help solve your problem?
One approach to provide an experience around this would be for the user or the stack to specify a selector that can be used to query all the API objects the stack has generated.  The stack's controller would add these lables/annotations to each resource it generates.  For example:
```
 # a selector for all the API objects generated by this stack
 selector:
   matchLabels:
    core.crossplane.io/name: "wordpress"
```

How can these easily be queried, considering there are multiple different types in play, and the Kubernetes API is completely type centric?  Would a query need to be sent off for every known type in the API? That sounds suboptimal.

We need to do some thinking to establish the pattern here, then document it or build  functionality in a library that each stack can reuse to easily implement this.

**Comment by jbw976** [comment]
/cc @rathpc @thephred 

@rathpc were you already doing some thinking and prototyping on this topic? Is there any write-up of your learnings that you can share here?

**Comment by turkenh** [comment]
I was also trying to figure out this in the context of trace cli #744.

> Take for example the WordPress stack. In response to the user creating a WordPressInstance, the wordpress controller will create multiple resources such as MySqlInstance and KubernetesCluster claims, KubernetesApplication and associated KubernetesApplicationResources, etc.
> How can the user easily find, browse, and view all of these resources that the stack's controller generated, as well as the hierarchical parent child relationships between them?

Currently, all resources generated as a result of creating a WordPressInstance has owner reference set  back to the WordPressInstance. Thanks to jsonpath support of kubectl, these resources can be found by the following _ugly_ command (putting here as a workaround until we have a better solution):

```
kubectl api-resources --verbs=list --namespaced -o name | grep '.crossplane.io' | xargs -n 1 kubectl get --show-kind --ignore-not-found -o=jsonpath="{.items[?(@.metadata.ownerReferences[*].name=='my-wordpressinstance')]['.metadata.name','.metadata.namespace']}"
```

However, this query does client side filtering by getting _all_ resources and takes quite some time already on my test cluster. 

I agree this is not optimal and we need to better establish a pattern probably with labels which enables server side filtering.

**Comment by rathpc** [comment]
I had been doing some thinking on this as well...

Migrating over some notes from a duplicate issue I had created.

My thought was that we could use labels defined on child resources that declare their respective parent resource.  It looks like there is already a label structure defined by k8s that fulfills this need.

The clearest example of what I am referring to is shown on this page https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels within the `app.kubernetes.io/part-of` label.

With this defined and in place on all crds we would be able to do something like this:

For the CRD: `example-x`

Get all resources that have a `app.kubernetes.io/part-of` value of `example-x`

**Comment by rathpc** [comment]
Is there already an in-progress one-pager for this design spec?

**Comment by jbw976** [comment]
No @rathpc, unfortunately there is no existing on-pager or design write-up for this topic 😞

**Comment by rathpc** [comment]
> No @rathpc, unfortunately there is no existing on-pager or design write-up for this topic 😞

@jbw976 Ok, I have started a One-Pager. Once it is in a fairly stable place I will open a PR and reference this issue
