### ISSUE TITLE
GitLab: Resource classes are not created

### ISSUE THREAD

**Issue by lavbox** [crossplaneio/crossplane#753]
### What happened?
While creating the Crossplane Resource Classes needed to provision GitLab applications, the command run successfully but verification steps shows no results. It causes the overall deployment failure because the gitlab-demo-unicorn pod fails to initialize with the following error.
```PG::ConnectionBad: could not translate host name "gitlab-demo-postgresql" to address: Name or service not known```

### How can we reproduce it?
Follow the steps mentioned in document `https://crossplane.io/docs/master/gitlab/gitlab-gcp.html`.

At the step where we create the Resource Classes, run the command
```kubectl create -f cluster/examples/gitlab/gcp/resource-classes/```

This returns the following output
```bucketclass.storage.gcp.crossplane.io/standard-gcp-bucket created```
```cloudsqlinstanceclass.database.gcp.crossplane.io/standard-gcp-postgres created```
```cloudmemorystoreinstanceclass.cache.gcp.crossplane.io/standard-gcp-redis created```

But when we verify by running the command
```kubectl get resourceclasses -n crossplane-system```

we get the following output
```No resources found.```
### What environment did it happen in?
Crossplane version: crossplane-0.0.0-956.aa77d92
Cloud Provider: Google Cloud Platform (GKE)
Kubernetes version: 1.13
OS: Debian GNU/Linux 9 
Kernel : x86_64 GNU/Linux

**Comment by hasheddan** [comment]
Hi @lavbox! With the move to [strongly-typed resource classes](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-strongly-typed-class.md) we no longer have a general `ResourceClass` kind, so we cannot "get" them all as the same resource type. To get each of the resource classes above you would need to run:
```
kubectl -n crossplane-system get bucketclasses
kubectl -n crossplane-system get cloudsqlinstanceclasses
kubectl -n crossplane-system get cloudmemorystoreinstanceclasses
```
Unfortunately the docs are currently out of sync with the examples, but you should see updates rolling out this week! Please feel free to reach out on [Crossplane slack](https://slack.crossplane.io/) if you further specific questions :)

I am going to close this issue in favor of the following: #615 #616 #617
