### ISSUE TITLE
stacks cli: update to use new dependency and rbac model

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#754]
### What seems to be the problem?

The contract for stacks, especially around rbac and dependencies, will be [changing](#663), based on some of the things described in recent design doc changes around the security model.

### What can Crossplane do to help?

Once we've updated the stack manager to use dependencies and the rbac model described in recent design doc changes, we'll want to update the stack cli to match.

We should also update the sample wordpress stack to match.

- [x] Update `stack install`, `stack uninstall`, and `stack list` to use new types
- [x] Update `stack init` to generate install samples using the new types, and to generate an app.yaml with the new types
- [x] Update wordpress sample to specify `dependsOn` and the install type
- [x] Update wordpress sample's install samples to use the new types

**Comment by displague** [comment]
I have draft PRs up in:
* crossplaneio/stack-gcp#19
* crossplaneio/stack-azure#5
* crossplaneio/stack-aws#5
* crossplaneio/sample-stack#2
* crossplaneio/sample-stack-wordpress#8
* crossplaneio/crossplane-cli#11

I'll add `dependsOn` to those drafts once I understand what each depends on.

**Comment by displague** [comment]
Closed by crossplaneio/sample-stack-wordpress#11, crossplaneio/sample-stack-wordpress#8, and crossplaneio/sample-stack-wordpress#14
