### ISSUE TITLE
Generate Crossplane (Custom Resource) API documentation

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#763]
### What problem are you facing?

Currently Crossplane relies on a directory of hand curated example YAML to document what custom resources exist and what their fields are. This is suboptimal for a number of reasons:

* It's prone to becoming stale and inaccurate as the codebase changes.
* It's typically not possible to write a working example that uses all resource fields, meaning many of our supported managed resource and resource class parameters are undocumented.
* Examples typically do not explain what each field actually configures, i.e. examples will show you can configure `.spec.numCores`, but does not explain what `numCores` means.
* It's a lot of work for Crossplane contributors to manually update all examples when making wide ranging changes to the codebase such as introducing strongly typed resource classes.

It makes sense for Crossplane to publish some examples to show how our various concepts fit together, but once a potential Crossplane user moves past examples and wants to write their own classes and claims they're forced to go read the Crossplane source code.

### How could Crossplane help solve your problem?

https://github.com/ahmetb/gen-crd-api-reference-docs/

The above tool is used by a small handful of Kubernetes ecosystem projects (Knative, Kubeflow, etc) to automatically generate API documentation from their Go API definitions. Note in this context "API" means the custom resources they add to the Kubernetes API server, not their developer facing Go APIs. I recommend Crossplane:

* Use this tool (or one like it) to generate API documentation for each release.
* Scale back our use of hand-maintained examples to important concepts.

**Comment by negz** [comment]
An example output: https://knative.dev/docs/reference/eventing/

**Comment by negz** [comment]
Cross linking https://github.com/crossplaneio/crossplaneio.github.io/issues/26.

**Comment by negz** [comment]
Below are some examples of how this will render on https://crossplane.io once https://github.com/crossplaneio/crossplaneio.github.io/pull/24 is merged. We'll need to add a sidebar link to the `api.html` - I presume this requires a PR against the website repo.

The entrypoint:
<img width="1272" alt="Screen Shot 2019-09-16 at 11 19 03 PM" src="https://user-images.githubusercontent.com/1049349/65016193-7e005f80-d8d8-11e9-96c0-100d3d12b186.png">

A page of generated API reference documentation:
<img width="1299" alt="Screen Shot 2019-09-16 at 11 19 30 PM" src="https://user-images.githubusercontent.com/1049349/65016194-7e005f80-d8d8-11e9-9feb-8cd05b5598cc.png">

**Comment by jbw976** [comment]
> We'll need to add a sidebar link to the `api.html` - I presume this requires a PR against the website repo

If you're referring to the left-hand table of contents navigation area, there's nothing that needs to be changed on the website code itself.  That is all generated from headers at the top of each markdown file, such as the below example from https://raw.githubusercontent.com/crossplaneio/crossplane/master/docs/install-crossplane.md.

The greater the `weight` value, the further down in the list the entry appears.

Note that only 2 levels of indentation are supported: Indented or not indented.

```
---
title: Install
toc: true
weight: 320
indent: true
---
```
