### ISSUE TITLE
wordpress stack: add automated publishing

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#764]
### What seems to be the problem?

Now that we have an image going into dockerhub for the [sample wordpress stack](https://github.com/crossplaneio/sample-stack-wordpress), we should automate the publishing of it, so that we don't need to remember to do it by hand every time.

### How can Crossplane help?

Add some automation to the sample wordpress project so that images are automatically published for commits that get into the master branch. The easiest way to do this would probably be to use the existing CI systems that we have set up (CircleCI and Jenkins), and to add another project/configuration.

**Comment by jbw976** [comment]
I'd call this one covered by #1235
