### ISSUE TITLE
Stacks CLI: cut 0.1.0 and 0.2.0 release

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#767]
Related to #614 

### What seems to be the problem?

There are a bunch of little things we want to do to cut the 0.3 release, so this ticket will be used to help us track them.

### What does it look like when we're done?

Release cutting steps
- [ ] Create a branch for the release
- [ ] Update release notes
- [ ] Point install instructions in the docs to the latest stable release
- [ ] Create a tag for the release
- [ ] Delete the branch
- [ ] Point links to the documentation to the latest stable release

**Comment by jbw976** [comment]
@suskin can we rename this issue to cut v0.0.2 release of CLI? Are you tracking this effort though any other means?  I'm realizing that the CLI repo is inconsistent with the release process for the rest of our repos, we may want to normalize that process in future releases.

**Comment by jbw976** [comment]
This has been completed:

* `v0.1.0`: https://github.com/crossplaneio/crossplane-cli/releases/tag/v0.1.0
* `v0.2.0`: https://github.com/crossplaneio/crossplane-cli/releases/tag/v0.2.0
