### ISSUE TITLE
Consider updating SetPortableClassItems() logic for panics 

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#787]
### What problem are you facing?

The `SetPortableClassItems()` method was required on all portable `___ClassList` objects following crossplaneio/crossplane-runtime#13. Implementation consisted of ignoring objects that were not the correct type for the class list's items:

```go
// SetPortableClassItems of this RedisClusterClassList.
func (rc *RedisClusterClassList) SetPortableClassItems(r []resource.PortableClass) {
	items := make([]RedisClusterClass, len(r))
	for i, item := range r {
		if rcItem, ok := item.(*RedisClusterClass); ok {
			items[i] = *rcItem
		}
	}
	rc.Items = items
}
```

### How could Crossplane help solve your problem?

It is not clear that this is the desired behavior for this method. Alternatives were proposed by @negz in [comment](https://github.com/crossplaneio/crossplane/pull/786#discussion_r323918294).

**Comment by negz** [comment]
If https://github.com/crossplaneio/stack-gcp/pull/39 and friends are merged this change will need to be made as part of angryjet, which would generate these methods.

**Comment by hasheddan** [comment]
Portable classes no longer exist so this issue is no longer needed!
