### ISSUE TITLE
Stack permissionScope value invalid

### ISSUE THREAD

**Issue by rbwsam** [crossplaneio/crossplane#797]
According to [the stacks design doc](https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-stacks.md#example-appyaml) the value of the field `permissionScope` may only be one of `Cluster, Namespace` but currently [config/stack/manifests/app.yaml](https://github.com/crossplaneio/sample-stack-wordpress/blob/master/config/stack/manifests/app.yaml) has the value `Namespaced`.

**Comment by jbw976** [comment]
The stacks security and isolation design doc is correct: https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stacks-security-isolation.md#stack-package-author

So we just need to update https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-stacks.md#example-appyaml

**Comment by jbw976** [comment]
PR to fix this in #798 @rbwsam
