### ISSUE TITLE
KubernetesApplicationResource never reconciles after success

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#810]
### What happened?

KubernetesApplicationResource reconciler never reconciles after the reconcile loop has completed successfully (waited for 20 minutes). For example, if a service has been deployed to the remote cluster successfully and the subsequent patch calls are successful, there is no more event on the KubernetesApplicationResource in the crossplane cluster. Hence, it never goes to remote cluster to retrieve the status, external IP and other things. 

### How can we reproduce it?

Go through GCP Stack Guide https://github.com/crossplaneio/crossplane/pull/802 
Do not delete crossplane pod and watch service KubernetesApplicationResource service object. It doesn't get the external IP from the remote cluster.

I think this happens because KubernetesApplicationResources are not always in failed state anymore since the fix of https://github.com/crossplaneio/crossplane/issues/428 .

As far as I see, that is the expected behavior, see https://github.com/crossplaneio/crossplane/blob/master/pkg/controller/workload/kubernetes/resource/resource.go#L203

### Suggestion

We should use a constant resync period of 30 seconds or 1 minute in success return statements such as https://github.com/crossplaneio/crossplane/blob/master/pkg/controller/workload/kubernetes/resource/resource.go#L203
### What environment did it happen in?
Crossplane version: master c29b611278f2ddba64a63eb674b55d9fd6d19e2b

**Comment by negz** [comment]
@muvaf From my read of the code your assessment sounds accurate. I agree that we should switch the sync method to return `RequeueAfter: 30 * time.Second` or similar.
