### ISSUE TITLE
Support Helm 3

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#839]
### What problem are you facing?

Helm 3 brought some breaking changes on how Helm works and what flags its CLI accepts.

When you fix your CLI flags to the new ones a few problems arise:
* Our helm chart does not have `crossplane-system` namespace, hence we're not able to do `helm3 install crossplane -n crossplane-system` because that behavior is identical to how kubectl namespace works now, i.e. you get `namespaca is not found`.
* Just raw `helm3 install crossplane crossplane-alpha/crossplane --version 0.3.0` doesn't work, it returns `Error: customresourcedefinitions.apiextensions.k8s.io "kubernetesapplicationresources.workload.crossplane.io" already exists` on a fresh cluster. The actual resource changes randomly.

### How could Crossplane help solve your problem?

I haven't invested so much time into this, these are my initial observations. Helm3 is still in beta phase, so, not sure when we want to support it. Wanted to track this here.

**Comment by suskin** [comment]
I also haven't invested time into this, but I am wondering whether creating the namespace ahead of the installation command would be sufficient to make things work. Did you happen to already try that @muvaf ?

**Comment by muvaf** [comment]
@suskin If the namespace doesn't exist, it says the namespace is not found just like kubectl does. I cleaned the cluster, created namespace beforehand and got the `crd already exists` error.

**Comment by suskin** [comment]
Dang, ok. Thanks for clarifying @muvaf !
