### ISSUE TITLE
Log format for cloud provider stacks is not human-friendly

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#849]
### What problem are you facing?

I was debugging an issue I was running into when following the Crossplane Stacks Guide using AWS, and I took a look at the logs for the AWS Stack as part of that process. I noticed that the format appears to be json, like this:

```
{"level":"error","ts":1569442751.2482467,"logger": . . .
```

I find the core crossplane pod's format much more human-friendly, which looks more like this:

```
2019-09-25T17:53:07.031Z        DEBUG
```

I am filing this under crossplane instead of the individual stack because I am not sure whether it also applies to other stacks too.

### How could Crossplane help solve your problem?

As a human operator I would prefer that the log format is more like the core crossplane pod's output than the AWS stack pod's output.

**Comment by negz** [comment]
@suskin I believe using the `--debug` flag produces the user friendly format. It could be that core Crossplane has that on by default at the moment. IMO the default should be machine friendly rather than human friendly logs.

**Comment by suskin** [comment]
@negz thanks for explaining! I tested setting the `--debug` flag locally, and I can confirm that setting it does produce the human-friendly format. My crossplane pod does appear to have the flag set.

**Comment by suskin** [comment]
I suppose the takeaways for me would be:

* Discovering the difference in functionality is not something I have figured out how to do yet
* The difference between the default for crossplane and the default for the AWS stack was confusing

**Comment by jbw976** [comment]
agreed with this @suskin, I would have liked to have DEBUG logging on by default for the stacks similar to how we do for core crossplane and stack manager.

This is actually making me think about how configuration can be influenced for stacks at install time, similar to how you may want to influence what version of the controller the stack starts up when it is installed.  Both debug logging and controller version are hard coded in the stack's `install.yaml` file currently, so it would require editing it and rebuilding and publishing the stack which is not a great solution.  Wonder if we can do better here and allow configuration to be specified for the stack at stack install time?

Example: https://github.com/crossplaneio/stack-aws/blob/master/config/stack/manifests/install.yaml#L20

**Comment by suskin** [comment]
Good point @jbw976 ; I agree that it would make sense to be able to do some configurationing at install time. I remember talking about this being useful for some other use-case also, but I don't remember what the use-case was right now. It may have been for being able to specify a different source for the controller image at install time.

**Comment by negz** [comment]
> I would have liked to have DEBUG logging on by default

I really don't think this is a good practice. How often do you run software that _defaults_ to debug level logging? My suggestion would be to disable debug logging being on by default on Crossplane and all stacks, but make it straightforward and well documented how to do so.

**Comment by negz** [comment]
I strongly feel that our default mode of operation should assume a production deployment and thus machine parseable, aggregatable logs. We may want to ensure there is an _option_ to turn on debug logging for development etc when installing an infrastructure stack, but I think that is a separate issue. I am going to close this issue as won't fix. Please reopen if you disagree.
