### ISSUE TITLE
Add schema validation for resource properties

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#85]
For example: `RDSInstance` 
```
--db-instance-identifier (string)

The DB instance identifier. This parameter is stored as a lowercase string.

Constraints:

Must contain from 1 to 63 letters, numbers, or hyphens.
First character must be a letter.
Can't end with a hyphen or contain two consecutive hyphens.
```

We should be able to assert these constraints via schema validation.

**Comment by negz** [comment]
We can do this using [CRD validation markers](https://book.kubebuilder.io/reference/markers/crd-validation.html). We do so for resource claims (whose schemas we define), but have chosen not to do so for managed resources. Our managed resources are high fidelity representations of the underlying provider APIs, and chasing the valid values of those APIs is a losing game. We prefer to submit the values to the cloud provider APIs and return any to the user in the cloud provider's words.
