### ISSUE TITLE
AWS: Managed resources appear to be deleted and recreated for no reason

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#854]
### What happened?

I have been going through the Stacks Guide using AWS, and I noticed a strange behavior. I am not sure exactly what causes it.

I started going through the guide a few days ago, using a Crossplane control cluster running on my MacOS laptop in Docker Kubernetes.

Today, I noticed that the EKS cluster and MySQL instance I had been working with had been deleted and recreated in Crossplane. It appears to have happened around the time I got into the office and connected to the network.

I have been closing my laptop and moving around the office throughout the day to go to meetings. Recently, I locked it and took a break for a bit, during which the laptop presumably went to sleep. When I came back and checked on my managed resources, the EKS clusters I had been managing with Crossplane had just been deleted and recreated, about at the time when I would have been logging into the laptop.

The claims have been around the whole time, and were not deleted and recreated.

The first time I noticed this, the EKS cluster was active. The second time I had two EKS clusters, and I believe one was active and one was creating.

I am creating this in the main crossplane repository in case it affects other cloud provider stacks or some shared code. I have not checked.

### How can we reproduce it?

I am not entirely sure yet what the minimum reproduction steps are, but I imagine that it involves using the AWS Stack to manage an EKS cluster or MySQL instance using a Crossplane control cluster on a laptop, then letting the laptop sleep, then coming back to it. I was following the Crossplane Stacks Guide using AWS, and had created a wordpress instance.

### What environment did it happen in?
Crossplane version: helm alpha
AWS Stack version:  `crossplane/stack-aws:v0.1.0`
Mac OS
Kubernetes from Docker Desktop for Mac OS

**Comment by suskin** [comment]
I did check the logs of the AWS infrastructure stack pod, but I did not see anything other than messages declaring that it was reconciling the managed resources.

**Comment by negz** [comment]
> The claims have been around the whole time, and were not deleted and recreated.

Is this also true of the managed resources bound to said claims?

**Comment by suskin** [comment]
> Is this also true of the managed resources bound to said claims?

No. The managed resources seemed to have been deleted and recreated on the Crossplane side, and seemed to have been deleted and recreated on the AWS side as well.

**Comment by negz** [comment]
I'm pretty confident this was an instance of #895, which is now fixed. I'm going to close this - please reopen if you see it happen again.
