### ISSUE TITLE
Determine desired format for Kubernetes provider secrets

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#861]
### What problem are you facing?

Kubernetes cluster connection secrets were previously changed from using the full `kubeconfig` to only necessary fields for connection in #273. However, #841 expands the use of these secrets to include BYO cluster scenarios, meaning that the secret would be "manually" created. It is not clear whether we want to use the current format given this increased functionality.

### How could Crossplane help solve your problem?

Converge on a format that is consistent for all Kubernetes cluster connection secrets. This may not involve any change, but it should be revisited if the BYO cluster scenario proves cumbersome.

**Comment by muvaf** [comment]
I think our connection string should be raw kubeconfig, which is accepted by all k8s clients I can think of, including `kubectl`, `go-client`, `controller-runtime`, `helm` etc.

This is especially important when users just want to use Crossplane for infrastructure and deploy the apps on their own, either via helm or some other tool.

**Comment by vadasambar** [comment]
I am facing an issue where I am able to connect to a GKE provisioned cluster by building `rest.Config` from connection secrets but I am not able to create a kube config that I can use to install my application using `helm`. This is a big problem for us because we will have build a kube config in our code to do helm install.

**Comment by aeli0** [comment]
@hasheddan @muvaf It will be helpful if this issue is fixed. We want to deploy apps only using `helm`. Do you think it can be prioritized for next release?

**Comment by muvaf** [comment]
@vadasambar @aeli0 This is implemented across 3 cloud providers and will be included in the next release!

**Comment by vadasambar** [comment]
Thank you so much @muvaf !
