### ISSUE TITLE
Basic refresh of GitLab Stack to work with Crossplane v0.3.0

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#866]
Refresh the GitLab Stack to use the latest and greatest from Crossplane v0.3.0.

Part of the [San Diego Milestone](tbd)

### What seems to be the problem?
v0.3.0 introduced a lot of awesome new functionality, would like to use the GitLab Stack with the latest and greatest.

### What could Crossplane do to help?
Basic refresh of https://github.com/crossplaneio/gitlab-controller to work with Crossplane v0.3.0.

### What does it look like when we're done?
TBD

### How could this be demonstrated?
TBD

**Comment by negz** [comment]
@prasek I'm pretty sure this is no longer a priority as of 0.7, right? I'm going to close it but please reopen if I'm wrong.
