### ISSUE TITLE
Crossplane Helm chart accepts optional stack=gcp|aws|azure values file attribute

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#867]
Crossplane work to enable [GitLab Auto DevOps integration phase 1](https://gitlab.com/groups/gitlab-org/-/epics/1866#note_216080986)

Part of the [San Diego Milestone](tbd)

### What seems to be the problem?
To support managed service provisioning in GitLab pipelines (DBaaS, cache, etc.), would like to add Crossplane as a GitLab managed app with a selected infrastructure Stack to install: GCP, AWS, or Azure that can be done from the GitLab managed apps GUI.

![image](https://user-images.githubusercontent.com/284840/66261656-62290480-e786-11e9-9684-996ec29524e7.png)

GitLab managed apps are Helm charts that GitLab can install to a connected Kubernetes cluster. The GitLab UI for installing managed apps will be updated to install the Crossplane Helm chart and pass the selected infrastructure stack in a helm values file, so the Crossplane Helm chart can install it along with core Crossplane.

### What could Crossplane do to help?
Update the Crossplane Helm chart to accept an optional stack attribute to install one of the cloud provider stacks (AWS, GCP, Azure)

### What does it look like when we're done?
 - Crossplane Helm chart accepts an optional values file `stack` attribute that if specified will install the associated infrastructure stack along with core Crossplane.
 - Crossplane v0.4.0 helm chart needs to continue supporting Helm 2 installs, since [GitLab 12.5 will continue to require Helm 2](https://gitlab.com/groups/gitlab-org/-/epics/1866#note_227663961).

### How could this be demonstrated?
This can be demoed stand alone by installing the Crossplane Helm chart (using Helm 2) with `--set stack=aws|gcp|azure` or as part of [GitLab #1866 phase 1](https://gitlab.com/groups/gitlab-org/-/epics/1866#note_216080986):
```
helm repo add crossplane-alpha https://charts.crossplane.io/alpha
helm install --set stack=aws|gcp|azure --name crossplane --namespace crossplane-system crossplane-alpha/crossplane
```

Verify the infrastructure stack is installed along with core Crossplane.

### Todo
 * [ ] Update Crossplane v0.4.0 Helm chart that will be published to the alpha channel to accept an optional `stack` attribute for installing one of the infrastructure stacks: AWS, GCP, Azure

**Comment by prasek** [comment]
@jbw976 GitLab 12.5 is going to stick with Helm 2 for GitLab-managed apps, so the Crossplane v0.4.0 helm chart needs to continue working with Helm 2. Updated above to reflect that.

**Comment by turkenh** [comment]
I've opened PR #932 which adds `clusterStacks` option to helm chart allowing one or more infrastructure stacks to be installed along with Crossplane.
 
Currently, it installs cluster stacks in the same namespace as Crossplane (typically `crossplane-system`) and package version for the stacks are always `master`. 

Please let me know if any of above assumptions would not work.

**Comment by infinitecompute** [comment]
@turkenh Has this been added to the public documentation?  If not, lets open another issue for that.

**Comment by jbw976** [comment]
Yes @infinitecompute this has been added to the documentation, see https://crossplane.io/docs/v0.4/install-crossplane.html#installation-with-helm
