### ISSUE TITLE
Set Default values during reconciliation

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#87]
Currently we "assume" the default values for some of the spec properties.
Such values are never reflected back in the specs.

For example: `RDSIntanceSpec.ConnectionSecretRef` - if not provided, we will use
`RDSIntance.Name` and `RDSInstance.Namespace`

Consider creating a first loop pass dedicate for "Finalizer" and "Default Values" only.

**Comment by negz** [comment]
I'm going to optimistically close this out, presuming there aren't other cases beside the example listed here. Every resource now writes its connection secret to an explicity configured connectionSecretRef.
