### ISSUE TITLE
Create a new Wordpress Stack example based on Template Stacks

### ISSUE THREAD

**Issue by displague** [crossplaneio/crossplane#881]
### What problem are you facing?

Example Stacks demonstrate design and usage which aids Stack developers.  With the addition of Template Stacks, a first-class Stack should represent the minimum requirements and some of the more complex concepts that Template Stack offer.

### How could Crossplane help solve your problem?

Today, there is a Sample Wordpress Stack which uses a Kubebuilder based controller to deploy Wordpress using KubernetesCluster, KubernetesApplication, and MySQLInstance Crossplane managed resource claims.

A Template Stack version of this Wordpress Stack should be created in contrast to the controller driven implementation.

The new template stack should deploy the Wordpress using the same sub-resources and the same CRD as the existing stack.

Part of #853

**Comment by jbw976** [comment]
I think this has been superseded by https://github.com/crossplaneio/sample-stack-wordpress/issues/28
