### ISSUE TITLE
Create Rook Yugabyte Cluster CRDs and controllers

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#885]
Part of #862

### What problem are you facing?

`stack-rook` needs the ability to create Rook Yugabyte `Cluster` objects in a target Kubernetes cluster where the Rook operators are installed.

### How could Crossplane help solve your problem?

Because a user should be able to dynamically provision a Rook Yugabyte cluster, the following custom resources are required:

1. Yugabyte `Cluster`
1. Yugabyte `ClusterClass`

The following controllers are required to reconcile these resources:
1. Claim controller that watches `PostgreSQLInstance` claims
1. Managed resource controller for managing `Cluster` resources

**Comment by jbw976** [comment]
Fixed in https://github.com/crossplaneio/stack-rook/pull/1
