### ISSUE TITLE
Cloud resource management patterns document

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#9]
This repository will serve as a useful set of patterns for managing cloud provider resources in kubernetes.  These patterns should be brainstormed and documented in a shared document that serves to capture design elements as well as best practices for developers implementing controllers for new cloud resources.

**Comment by jbw976** [comment]
Related to #289 
Related to #290

**Comment by jbw976** [comment]
What work remains on this? I know we got a great start on https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-reconciler-patterns.md, but what other patterns and practices need to be updated or included into that document?

**Comment by ichekrygin** [comment]
TBH I am not exactly sure. Some pieces seem to be outdated (Conditions), while others may be still relevant. As for the completion, this document (in my understanding) is more of the information/guide-line/best-practices type. I am not sure what is needed (and if it is needed) to become a Pattern type design document.

**Comment by negz** [comment]
I'm optimistically going to call this fixed by https://github.com/crossplaneio/crossplane/pull/840.
