### ISSUE TITLE
Stack-rook docs for crossplane.io

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#903]
### What problem are you facing?

`stack-rook` provides new functionality to Crossplane in that it allows for provisioning in-cluster storage. Because there are differences between how the Rook stack operates and other cloud provider stacks operate, and it will be owned by the Crossplane org for the time being, it is important add documentation to demonstrate concepts and usage for end-users.

### How could Crossplane help solve your problem?

A services guide for Rook should be added to [crossplane.io](https://crossplane.io/docs/v0.3/services-guide.html). It will likely not involve deploying wordpress, but could provide a simple Kubernetes workload example that connects to a Rook-provisioned database.

**Comment by hasheddan** [comment]
@negz I have #964 for the services guide, but may need your expertise on generating the API documentation :)

**Comment by hasheddan** [comment]
Closed by #964
