### ISSUE TITLE
Release process guide / manual

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#911]
part of #864 

### What problem are you facing?

There is no release guide that educates and informs an engineer of Crossplane on how to release a new version of the software.  @jbw976 has run the releases so far but no one else knows how to perform one.

### How could Crossplane help solve your problem?

We should create a new release process guide that provides all the instructions and tips for running a release of the Crossplane software.  This guide should cover how to tag/branch, build and publish, and promote.  It should also cover patch releases as well.

**Comment by jbw976** [comment]
This release guide will be finalized with real world examples/output of the process from running through the real v0.4.0 release.  Therefore, this issue will be fixed first thing in v0.5.0.
