### ISSUE TITLE
Template Stacks UX: overall experience; modeling, design thinking; UX;

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#915]
part of #853

**Comment by suskin** [comment]
I am working on this in [a repository with code examples](https://github.com/suskin/template-stack-experience). I plan to try to create a design document to complement the code examples and Marques's design document, though there is already a chunk of design type discussion in the readme in the examples repo.

**Comment by suskin** [comment]
I've added an example of a [resource pack](https://github.com/suskin/template-stack-experience/tree/master/wordpress-workload/go-templates/resource-pack) which shows how one might create a resource pack to set up the baseline GCP Network resources needed to run Wordpress in GCP. Now that this example is in the repo, I'm going to switch over to getting this into a reviewable format. I expect that will be ready some time on Monday. Interested parties can already begin reviewing by taking a look at the repository though.

**Comment by suskin** [comment]
I've opened a pull request with a design document which refers back to the code examples in #956

**Comment by suskin** [comment]
As mentioned in #1011, I will be updating the design to incorporate some feedback.

**Comment by suskin** [comment]
I've updated the design based on some feedback - see #956
