### ISSUE TITLE
error and event reporting: a practical guide

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#944]
### What problem are you facing?

We have observed that Crossplane would benefit from more error and event reporting, to help with debugging situations. There is some discussion in #858 . As we transition to having a more robust strategy, we'll want to have good examples and patterns we use, so that our codebase is consistent and it's easy for new contributors to adopt our approaches quickly.

### How could Crossplane help solve your problem?

To complement the philosophies and mindset discussed in #858, we will want a set of patterns and best practices for error and event reporting.

Some aspects of such a guide incude:

* Examples of when to log at debug level, and when to log at info level
* Examples of error and event reporting embedded in the samples in the [services developer guide](https://github.com/crossplaneio/crossplane/blob/master/docs/services-developer-guide.md)
* Examples of what to report in an event, how to structure it, and when to report an event

The practical guide should be useful for:

* Developers writing code who want to know what to do
* People reviewing pull requests who want to make sure changes follow our best practices

**Comment by muvaf** [comment]
https://github.com/kubernetes/enhancements/pull/1367 this KEP could be helpful for this work.

**Comment by negz** [comment]
Relates to #331 .
