### ISSUE TITLE
Refresh API docs for 0.4

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#970]
### What problem are you facing?

We're about to release Crossplane 0.4 and https://crossplane.io/docs/master/api.html requires manual work to build new docs.

### How could Crossplane help solve your problem?

Update and run https://github.com/negz/crossdocs to generate new docs. We should probably wait until shortly before the release to make sure everything in flight lands before we do this.

**Comment by jbw976** [comment]
I'm working through documenting the release process right now @negz.  This sounds like something that should be done in `master` before we create the release branch for `v0.4.0`, what do you think?

**Comment by negz** [comment]
@jbw976 That sounds right to me. Ideally we'd automatically update `master` with each merge, but  bumping the docs in master before each release seems like the next best thing.
